table _COUNTRY_NAME_
	isHidden
	lineageTag: 4a25b500-dace-4833-95ff-33ea43ab268d

	measure Country_Name = SELECTEDVALUE(_COUNTRY_NAME_[_COUNTRY_NAME_])
		isHidden
		lineageTag: 092d148d-cfb2-4ee3-bd65-5790f56b7204

		changedProperty = IsHidden

	column _COUNTRY_NAME_
		dataType: string
		isHidden
		lineageTag: 16ce368c-f878-43c1-9382-68c0d0874fbd
		summarizeBy: none
		sourceColumn: _COUNTRY_NAME_

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _COUNTRY_NAME_ = m
		mode: import
		queryGroup: PARAMS
		source = "Ukraine" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Text

