table _CURRENCY_
	isHidden
	lineageTag: 5790d449-3414-4e1e-815f-2b125c315674

	measure Currency_Name = max(_CURRENCY_[_CURRENCY_])
		isHidden
		lineageTag: e3224de7-f44a-4517-937c-d86892ff75c8

		changedProperty = IsHidden

	column _CURRENCY_
		dataType: string
		isHidden
		lineageTag: 83ab3981-49a1-498c-860b-d020201d0ac5
		summarizeBy: none
		sourceColumn: _CURRENCY_

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _CURRENCY_ = m
		mode: import
		queryGroup: PARAMS
		source = "UAH" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

	changedProperty = IsHidden

	annotation PBI_ResultType = Text

	annotation PBI_NavigationStepName = Navigation

