table _M_
	isHidden
	lineageTag: 376233a7-99f2-445f-85b4-443c59febd8b

	measure SumByMeasure =
			
			var measureType=SELECTEDVALUE(SelectMeasures[MeasureName])
			var curType=SELECTEDVALUE(_CURRENCY_[_CURRENCY_])
			return SWITCH(TRUE(),
			        measureType="pcs",sum(Data[Q]),
			        measureType in {curType,curType&"/tabs",curType&"/DDD"},sum(Data[V]),
			        measureType in {"USD","USD/tabs","USD/DDD"},sum(Data[V_USD]),
			        measureType in {"EUR","EUR/tabs","EUR/DDD"},sum(Data[V_EUR]),
			        measureType="tabs",sum(Data[TABS]),
			        measureType="DDD",sum(Data[DDD])
			    )
		isHidden
		lineageTag: 4c4680de-7511-435b-be0b-12f24ce4f1f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Dyn_AC =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([SumByMeasure]),
			            "YTD",TOTALYTD([SumByMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([SumByMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		isHidden
		lineageTag: bc6a1608-e997-461c-8ede-88ab506e9267

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByVol =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([Distr_Sales_AC]),1000000,
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),[Distr_Sales_AC],,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),[Distr_Sales_AC],,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),[Distr_Sales_AC],,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),[Distr_Sales_AC],,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),[Distr_Sales_AC],,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),[Distr_Sales_AC],,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),[Distr_Sales_AC],,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),[Distr_Sales_AC],,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),[Distr_Sales_AC],,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),[Distr_Sales_AC],,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),[Distr_Sales_AC],,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),[Distr_Sales_AC],,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),[Distr_Sales_AC],,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),[Distr_Sales_AC],,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),[Distr_Sales_AC],,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),[Distr_Sales_AC],,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),[Distr_Sales_AC],,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),[Distr_Sales_AC],,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),[Distr_Sales_AC],,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),[Distr_Sales_AC],,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),[Distr_Sales_AC],,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),[Distr_Sales_AC],,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),[Distr_Sales_AC],,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),[Distr_Sales_AC],,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),[Distr_Sales_AC],,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),[Distr_Sales_AC],,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),[Distr_Sales_AC],,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),[Distr_Sales_AC],,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),[Distr_Sales_AC],,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),[Distr_Sales_AC],,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),[Distr_Sales_AC],,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),[Distr_Sales_AC],,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),[Distr_Sales_AC],,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),[Distr_Sales_AC],,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),[Distr_Sales_AC],,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),[Distr_Sales_AC],,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),[Distr_Sales_AC],,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),[Distr_Sales_AC],,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),[Distr_Sales_AC],,Desc,Dense),
			        "Region Level 1",rankx(ALLSELECTED(Areas[LEVEL_1]),[Distr_Sales_AC],,Desc,Dense),
			        "Region Level 2",rankx(ALLSELECTED(Areas[LEVEL_2]),[Distr_Sales_AC],,Desc,Dense),
			        "Region Level 3",rankx(ALLSELECTED(Areas[LEVEL_3]),[Distr_Sales_AC],,Desc,Dense),
			        "Region Level 4",rankx(ALLSELECTED(Areas[LEVEL_4]),[Distr_Sales_AC],,Desc,Dense),
			        "Area",rankx(ALLSELECTED(Areas[AREA_NAME]),[Distr_Sales_AC],,Desc,Dense),
			        "Chain name",rankx(ALLSELECTED(Areas[CHAIN_NAME]),[Distr_Sales_AC],,Desc,Dense),
			        "Legal entity",rankx(ALLSELECTED(Areas[ORG_NAME]),[Distr_Sales_AC],,Desc,Dense),
			        "Pharmacy name",rankx(ALLSELECTED(Areas[CLIENT_NAME]),[Distr_Sales_AC],,Desc,Dense),
			        "Pharmacy address",rankx(ALLSELECTED(Areas[ADDRESS]),[Distr_Sales_AC],,Desc,Dense),
			        "Pharmacy type",rankx(ALLSELECTED(Areas[CLIENT_TYPE_ORG]),[Distr_Sales_AC],,Desc,Dense),
			        "Pharmacy city",rankx(ALLSELECTED(Areas[CITY]),[Distr_Sales_AC],,Desc,Dense)
			    )
			)
		formatString: 0
		isHidden
		lineageTag: 582e3293-f6fa-4dca-ab81-9a10c43149a2

	measure Distr_Sales_AC_Ranked = if([RankByVol]<=[TOP],[Distr_Sales_AC],BLANK())
		formatString: #,0
		isHidden
		lineageTag: d001544b-1ddd-4df1-9928-9b050e941795

	measure Distr_Sales_Dyn_PY = ```
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			VAR PYMaxDate = LOOKUPVALUE(Periods[DatePY], Periods[Period], MAX(Periods[Period]))
			VAR PYMinDate = PYMaxDate - delta + 1 
			return if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			        "Daily",CALCULATE([SumByMeasure],ALL(Periods),TREATAS(VALUES(Periods[DatePY]),Periods[Period])),
			        "YTD",TOTALYTD([SumByMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MTD",TOTALMTD([SumByMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MQT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-1,YEAR)),
			        "MMT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-1,YEAR)),
			        "MAT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR),-1,YEAR)),
			        "Custom",CALCULATE([SumByMeasure],All(Periods),Periods[Period]>=PYMinDate && Periods[Period]<=PYMaxDate)
			     ),BLANK()
			)
			```
		isHidden
		lineageTag: 69c9571f-b6c4-4b0f-9ed5-98004e0c38d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_AC_Total =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return SWITCH(SelectDim,
			    "Corporation",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(ECom[E-com]))
			
			)
		isHidden
		lineageTag: 1c44c5e1-f181-4f0e-9d31-fedf786bb1b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_Dyn_AC = CALCULATE([Distr_Sales_Dyn_AC]/[Market_Sales_Dyn_AC_Total])
		isHidden
		lineageTag: cac56921-b30a-4822-b578-fb6950890112

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_AC_Ranked = if([RankByVol]<=[TOP],[Market_MS_AC],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 935b9b47-d620-431a-ab9c-972a5ee0d788

	measure Market_EI_AC = [Market_MS_AC]/[Market_MS_PY]*100
		isHidden
		lineageTag: 0997961b-4501-44d1-9eca-25f22b355e46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_PY_Total =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return SWITCH(SelectDim,
			    "Corporation",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(ECom[E-com]))
			)
		isHidden
		lineageTag: 297a8720-77da-400a-9c20-4a71b4d00e82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_PY = [Distr_Sales_PY]/[Market_Sales_PY_Total]
		isHidden
		lineageTag: a6dc6b00-39a6-447f-8465-f6e1e52578c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_PY = DIVIDE([Distr_Sales_AC],[Distr_Sales_PY],BLANK())-1
		isHidden
		lineageTag: 38912baa-8506-4562-b5de-7abd7fa131ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_Ranked = if([RankByVol]<=[TOP] && not ISBLANK([Distr_Sales_PY]),[Market_GR_PY],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 096c9a40-93ee-4804-96fd-37a06bef80a4

	measure Distr_Sales_PY_Ranked = if([RankByVol]<=[TOP],[Distr_Sales_PY],BLANK())
		formatString: #,0
		isHidden
		lineageTag: 47f3d2e8-9ae4-4eb4-b378-5d5c3dc94af1

	measure Market_EI_AC_Ranked = if([RankByVol]<=[TOP] && not ISBLANK([Distr_Sales_PY]),[Market_EI_AC],BLANK())
		formatString: 0
		isHidden
		lineageTag: 2d542557-b4a5-4785-a26b-136bcef3c39d

	measure TOP = SELECTEDVALUE('TopN'[TopN])
		formatString: 0
		isHidden
		lineageTag: 1472c829-d939-41b9-9ac6-f1359f0241f3

	measure Market_Rank_AC_Ranked = if([RankByVol]<=[TOP],[RankByVol],BLANK())
		formatString: 0
		isHidden
		lineageTag: 554d7dd2-350a-48ec-b6b2-9df97db74268

	measure Self_Sales_AC = CALCULATE([Distr_Sales_AC],Filter(Groups,Groups[IS_LOCAL]=1))
		isHidden
		lineageTag: 5a089f49-c5cb-40a9-990f-a4cd9da9860b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Version = [Version_High]&"."&[Version_Low]&"."&[Build]
		isHidden
		lineageTag: 17201a7b-e8a9-48cd-9cf2-ed7238268cb7

	measure Selected_Periods_List = ```
			
			var isFilteredPeriods=ISFILTERED(Periods[Period])
			var isMultiPeriods=CALCULATE(DISTINCTCOUNT(Periods[Period]),Filter(Periods,Periods[Year]=[Current_Year]))>1
			var isFilteredSinglePeriods=ISFILTERED(SinglePeriod)
			var isMultiSinglePeriods=DISTINCTCOUNT(SinglePeriod[Period])>1
			return 
			if(isFilteredPeriods,
			        // for select in Periods table
			        if(isMultiPeriods,
			            CALCULATE(CONCATENATEX(Periods,Periods[Period],","),Filter(Periods,Periods[Year]=[Current_Year])),
			            CALCULATE(Format(max(Periods[Period]),"dd.mm.yyyy"),Filter(Periods,Periods[Year]=[Current_Year]))
			        ),
			        // for select in SinglePeriod table
			        if(isFilteredSinglePeriods,
			            if(isMultiSinglePeriods,
			                CONCATENATEX(SinglePeriod,Format(SinglePeriod[Period],"dd.mm.yyyy"),","),Format(max(SinglePeriod[Period]),"dd.mm.yyyy")
			            ), 
			            // else by default
			            Format(max(SinglePeriod[Period]),"dd.mm.yyyy")
			        )
			)
			```
		formatString: 0
		isHidden
		lineageTag: ce24eb56-3a2d-4f4a-9f44-a8c1d383fa58

	measure Current_Year = Int(Left(max(SinglePeriod[PERIOD_ID]),4))
		formatString: 0
		isHidden
		lineageTag: e46e1028-54f0-441f-bf7c-98a599fffee5

	measure Periods_Count =
			
			var CY=[Current_Year]
			return CALCULATE(DISTINCTCOUNT(Periods[PERIOD_ID]),FILTER(Periods,Periods[PT]=0 && Periods[Year]=CY))
		formatString: 0
		isHidden
		lineageTag: 85370b10-d472-4605-8c50-57b0236d462e

	measure Current_Logo_Name =
			
			var SelfLogo=SELECTEDVALUE(Logo[Logo])
			return if(not ISBLANK(SelfLogo),SelfLogo,"")
		isHidden
		lineageTag: 362ddf29-4872-4ec9-af05-80db6b817bfd

	measure Logo = ```
			
			var lo=SELECTEDVALUE(Logo[Logo])
			var lo2=if(ISBLANK(lo),BLANK(),lo)
			var ht=
			"<div><img src="""&lo2&""" 
			    style=""
			        position: absolute;
			        top: 50%;
			        left: 50%;
			        transform: translateX(-50%) translateY(-50%);
			        max-width: 100%;
			        max-height: 100%;
			    "">
			</div>"
			
			return ht
			```
		isHidden
		lineageTag: 630a19c7-1fb1-48e2-a6b5-bda0fa03d53a

	measure Current_Filters = ```
			
			var FilteredAddrMarket=IF(ISFILTERED(AddMarketFilterTable[Addressable market]),"AddrMarket",BLANK())
			var FilteredVTM=IF(ISFILTERED(Drugs[PTM]),"PTM:"&CONCATENATEX(FILTERS(Drugs[PTM]),Drugs[PTM],","),BLANK())
			var FilteredCorporation=IF(ISFILTERED(Drugs[Corporation]),"Corp.:"&CONCATENATEX(FILTERS(Drugs[Corporation]),Drugs[Corporation],","),BLANK())
			var FilteredMarketOrg=IF(ISFILTERED(Drugs[Market Org]),"Market Org:"&CONCATENATEX(FILTERS(Drugs[Market Org]),Drugs[Market Org],","),BLANK())
			var FilteredBrand=IF(ISFILTERED(Drugs[Brand]),"Brand:"&CONCATENATEX(FILTERS(Drugs[Brand]),Drugs[Brand],","),BLANK())
			var FilteredBrand_MarketOrg=IF(ISFILTERED(Drugs[Brand+Market Org]),"Brand+Market Org:"&CONCATENATEX(FILTERS(Drugs[Brand+Market Org]),Drugs[Brand+Market Org],","),BLANK())
			var FilteredBrand_Corporation=IF(ISFILTERED(Drugs[Brand+Corporation]),"Brand+Corporation:"&CONCATENATEX(FILTERS(Drugs[Brand+Corporation]),Drugs[Brand+Corporation],","),BLANK())
			var FilteredSKU=IF(ISFILTERED(Drugs[Full medication name]),"SKU:"&CONCATENATEX(FILTERS(Drugs[Full medication name]),Drugs[Full medication name],","),BLANK())
			var FilteredINN=IF(ISFILTERED(Drugs[INN]),"INN:"&CONCATENATEX(FILTERS(Drugs[INN]),Drugs[INN],","),BLANK())
			var FilteredCompGroupName=IF(ISFILTERED(Groups[GROUP_NAME]),"Comp group name:"&CONCATENATEX(FILTERS(Groups[GROUP_NAME]),Groups[GROUP_NAME],","),BLANK())
			var FilteredCompetitvegroup1=IF(ISFILTERED(Groups[PRODUCT_NAME_TREE.1]),"Comp group L1:"&CONCATENATEX(FILTERS(Groups[PRODUCT_NAME_TREE.1]),Groups[PRODUCT_NAME_TREE.1],","),BLANK())
			var FilteredCompetitvegroup2=IF(ISFILTERED(Groups[PRODUCT_NAME_TREE.2]),"Comp group L2:"&CONCATENATEX(FILTERS(Groups[PRODUCT_NAME_TREE.2]),Groups[PRODUCT_NAME_TREE.2],","),BLANK())
			var FilteredCompetitvegroup3=IF(ISFILTERED(Groups[PRODUCT_NAME_TREE.3]),"Comp group L3:"&CONCATENATEX(FILTERS(Groups[PRODUCT_NAME_TREE.3]),Groups[PRODUCT_NAME_TREE.3],","),BLANK())
			var FilteredCompetitvegroup4=IF(ISFILTERED(Groups[PRODUCT_NAME_TREE.4]),"Comp group L4:"&CONCATENATEX(FILTERS(Groups[PRODUCT_NAME_TREE.4]),Groups[PRODUCT_NAME_TREE.4],","),BLANK())
			var FilteredCompetitvegroup5=IF(ISFILTERED(Groups[PRODUCT_NAME_TREE.5]),"Comp group L5:"&CONCATENATEX(FILTERS(Groups[PRODUCT_NAME_TREE.5]),Groups[PRODUCT_NAME_TREE.5],","),BLANK())
			var FilteredCompGroupTag=IF(ISFILTERED(Tags[TAG]),"Comp group tag:"&CONCATENATEX(FILTERS(Tags[TAG]),Tags[TAG],","),BLANK())
			var FilteredCategory=IF(ISFILTERED(Drugs[CategoryLongName]),"Category:"&CONCATENATEX(FILTERS(Drugs[CategoryLongName]),Drugs[CategoryLongName],","),BLANK())
			var FilteredRx_OTC=IF(ISFILTERED(Drugs[Rx/OTC]),"Rx/OTC:"&CONCATENATEX(FILTERS(Drugs[Rx/OTC]),Drugs[Rx/OTC],","),BLANK())
			var FilteredATC1=IF(ISFILTERED(Drugs[ATC Code (1)]),"ATC 1:"&CONCATENATEX(FILTERS(Drugs[ATC Code (1)]),Drugs[ATC Code (1)],","),BLANK())
			var FilteredATC2=IF(ISFILTERED(Drugs[ATC Code (2)]),"ATC 2:"&CONCATENATEX(FILTERS(Drugs[ATC Code (2)]),Drugs[ATC Code (2)],","),BLANK())
			var FilteredATC3=IF(ISFILTERED(Drugs[ATC Code (3)]),"ATC 3:"&CONCATENATEX(FILTERS(Drugs[ATC Code (3)]),Drugs[ATC Code (3)],","),BLANK())
			var FilteredATC4=IF(ISFILTERED(Drugs[ATC Code (4)]),"ATC 4:"&CONCATENATEX(FILTERS(Drugs[ATC Code (4)]),Drugs[ATC Code (4)],","),BLANK())
			var FilteredATC5=IF(ISFILTERED(Drugs[ATC Code (5)]),"ATC 5:"&CONCATENATEX(FILTERS(Drugs[ATC Code (5)]),Drugs[ATC Code (5)],","),BLANK())
			var FilteredNFC1=IF(ISFILTERED(Drugs[NFC Code (1)]),"NFC 1:"&CONCATENATEX(FILTERS(Drugs[NFC Code (1)]),Drugs[NFC Code (1)],","),BLANK())
			var FilteredNFC2=IF(ISFILTERED(Drugs[NFC Code (2)]),"NFC 2:"&CONCATENATEX(FILTERS(Drugs[NFC Code (2)]),Drugs[NFC Code (2)],","),BLANK())
			var FilteredNFC3=IF(ISFILTERED(Drugs[NFC Code (3)]),"NFC 3:"&CONCATENATEX(FILTERS(Drugs[NFC Code (3)]),Drugs[NFC Code (3)],","),BLANK())
			var FilteredEphMRA1=IF(ISFILTERED(Drugs[EphMRA Code (1)]),"EphMRA 1:"&CONCATENATEX(FILTERS(Drugs[EphMRA Code (1)]),Drugs[EphMRA Code (1)],","),BLANK())
			var FilteredEphMRA2=IF(ISFILTERED(Drugs[EphMRA Code (2)]),"EphMRA 2:"&CONCATENATEX(FILTERS(Drugs[EphMRA Code (2)]),Drugs[EphMRA Code (2)],","),BLANK())
			var FilteredEphMRA3=IF(ISFILTERED(Drugs[EphMRA Code (3)]),"EphMRA 3:"&CONCATENATEX(FILTERS(Drugs[EphMRA Code (3)]),Drugs[EphMRA Code (3)],","),BLANK())
			var FilteredEphMRA4=IF(ISFILTERED(Drugs[EphMRA Code (4)]),"EphMRA 4:"&CONCATENATEX(FILTERS(Drugs[EphMRA Code (4)]),Drugs[EphMRA Code (4)],","),BLANK())
			var FilteredDomestic_Foreign_maker_=IF(ISFILTERED(Drugs[Domestic/Foreign(maker)]),"Domestic/Foreign(maker):"&CONCATENATEX(FILTERS(Drugs[Domestic/Foreign(maker)]),Drugs[Domestic/Foreign(maker)],","),BLANK())
			var FilteredMaker=IF(ISFILTERED(Drugs[Maker]),"Maker:"&CONCATENATEX(FILTERS(Drugs[Maker]),Drugs[Maker],","),BLANK())
			var FilteredCosmetic1=IF(ISFILTERED(Drugs[Cosmetic Name(1)]),"Cosmetic 1:"&CONCATENATEX(FILTERS(Drugs[Cosmetic Name(1)]),Drugs[Cosmetic Name(1)],","),BLANK())
			var FilteredCosmetic2=IF(ISFILTERED(Drugs[Cosmetic Name(2)]),"Cosmetic 2:"&CONCATENATEX(FILTERS(Drugs[Cosmetic Name(2)]),Drugs[Cosmetic Name(2)],","),BLANK())
			var FilteredCosmetic3=IF(ISFILTERED(Drugs[Cosmetic Name(3)]),"Cosmetic 3:"&CONCATENATEX(FILTERS(Drugs[Cosmetic Name(3)]),Drugs[Cosmetic Name(3)],","),BLANK())
			var FilteredCosmetic4=IF(ISFILTERED(Drugs[Cosmetic Name(4)]),"Cosmetic 4:"&CONCATENATEX(FILTERS(Drugs[Cosmetic Name(4)]),Drugs[Cosmetic Name(4)],","),BLANK())
			var FilteredCosmetic5=IF(ISFILTERED(Drugs[Cosmetic Name(5)]),"Cosmetic 5:"&CONCATENATEX(FILTERS(Drugs[Cosmetic Name(5)]),Drugs[Cosmetic Name(5)],","),BLANK())
			var FilteredBad1=IF(ISFILTERED(Drugs[BAD Name(1)]),"Bad 1:"&CONCATENATEX(FILTERS(Drugs[BAD Name(1)]),Drugs[BAD Name(1)],","),BLANK())
			var FilteredBad2=IF(ISFILTERED(Drugs[BAD Name(2)]),"Bad 2:"&CONCATENATEX(FILTERS(Drugs[BAD Name(2)]),Drugs[BAD Name(2)],","),BLANK())
			var FilteredMC1=IF(ISFILTERED(Drugs[MC Name(1)]),"MC 1:"&CONCATENATEX(FILTERS(Drugs[MC Name(1)]),Drugs[MC Name(1)],","),BLANK())
			var FilteredMC2=IF(ISFILTERED(Drugs[MC Name(2)]),"MC 2:"&CONCATENATEX(FILTERS(Drugs[MC Name(2)]),Drugs[MC Name(2)],","),BLANK())
			var FilteredMC3=IF(ISFILTERED(Drugs[MC Name(3)]),"MC 3:"&CONCATENATEX(FILTERS(Drugs[MC Name(3)]),Drugs[MC Name(3)],","),BLANK())
			var FilteredMC4=IF(ISFILTERED(Drugs[MC Name(4)]),"MC 4:"&CONCATENATEX(FILTERS(Drugs[MC Name(4)]),Drugs[MC Name(4)],","),BLANK())
			var FilteredMarketstatus=IF(ISFILTERED(Drugs[Market_Status]),"Market status:"&CONCATENATEX(FILTERS(Drugs[Market_Status]),Drugs[Market_Status],","),BLANK())
			var FilteredArea=IF(ISFILTERED(Areas[LEVEL_1]),"Area:"&CONCATENATEX(FILTERS(Areas[AREA_NAME]),Areas[AREA_NAME],","),BLANK())
			 var FilteredRegionlevel1=IF(ISFILTERED(Areas[LEVEL_1]),"Reg. level 1:"&CONCATENATEX(FILTERS(Areas[LEVEL_1]),Areas[LEVEL_1],","),BLANK())
			 var FilteredRegionlevel2=IF(ISFILTERED(Areas[LEVEL_2]),"Reg. level 2:"&CONCATENATEX(FILTERS(Areas[LEVEL_2]),Areas[LEVEL_2],","),BLANK())
			 var FilteredRegionlevel3=IF(ISFILTERED(Areas[LEVEL_3]),"Reg. level 3:"&CONCATENATEX(FILTERS(Areas[LEVEL_3]),Areas[LEVEL_3],","),BLANK())
			 var FilteredRegionlevel4=IF(ISFILTERED(Areas[LEVEL_4]),"Reg. level 4:"&CONCATENATEX(FILTERS(Areas[LEVEL_4]),Areas[LEVEL_4],","),BLANK())
			var FilteredSalestype=IF(ISFILTERED(ECom[E-com]),"Sales type:"&CONCATENATEX(FILTERS(ECom[E-com]),ECom[E-com],","),BLANK())
			//var FilteredSupplier=IF(ISFILTERED(Suppliers[SUPPLIER_NAME]),"Supplier:"&CONCATENATEX(FILTERS(Suppliers[SUPPLIER_NAME]),Suppliers[SUPPLIER_NAME],","),BLANK())
			var FilteredDrugName=IF(ISFILTERED(Drugs[DRUG_NAME]),"Drug Name:"&CONCATENATEX(FILTERS(Drugs[DRUG_NAME]),Drugs[DRUG_NAME],","),BLANK())
			var FilteredDrugDosage=IF(ISFILTERED(Drugs[doze]),"Drug Dosage:"&CONCATENATEX(FILTERS(Drugs[doze]),Drugs[doze],","),BLANK())
			var FilteredDrugPack=IF(ISFILTERED(Drugs[DRUG_FORM_NUMBER]),"Drug Form №:"&CONCATENATEX(FILTERS(Drugs[DRUG_FORM_NUMBER]),Drugs[DRUG_FORM_NUMBER],","),BLANK())
			
			var tbl={
			    FilteredAddrMarket, 
			    FilteredCorporation,
			    FilteredMarketOrg,
			    FilteredBrand,
			    FilteredBrand_MarketOrg,
			    FilteredBrand_Corporation,
			    FilteredSKU,
			    FilteredINN,
			    FilteredCompetitvegroup1,
			    FilteredCompetitvegroup2,
			    FilteredCompetitvegroup3,
			    FilteredCompetitvegroup4,
			    FilteredCompetitvegroup5,
			    FilteredCompGroupName, 
			    FilteredCompGroupTag,
			    FilteredCategory,
			    FilteredRx_OTC,
			    FilteredATC1,
			    FilteredATC2,
			    FilteredATC3,
			    FilteredATC4,
			    FilteredATC5,
			    FilteredEphMRA1,
			    FilteredEphMRA2,
			    FilteredEphMRA3,
			    FilteredEphMRA4,
			    FilteredNFC1,
			    FilteredNFC2,
			    FilteredNFC3,
			    FilteredDomestic_Foreign_maker_,
			    FilteredMaker,
			    FilteredCosmetic1,
			    FilteredCosmetic2,
			    FilteredCosmetic3,
			    FilteredCosmetic4,
			    FilteredCosmetic5,
			    FilteredBad1,
			    FilteredBad2,
			    FilteredMC1,
			    FilteredMC2,
			    FilteredMC3,
			    FilteredMC4,
			    FilteredMarketstatus,
			 FilteredArea,   
			 FilteredRegionlevel1,
			 FilteredRegionlevel2,
			 FilteredRegionlevel3,
			 FilteredRegionlevel4,
			    FilteredSalestype,
			//    FilteredSupplier,
			    FilteredVTM,
			    FilteredDrugName,
			    FilteredDrugDosage,
			    FilteredDrugPack
			    }
			
			var resultString=CONCATENATEX(FILTER(tbl,[Value]<>BLANK()),[Value],"; ")
			return resultString
			```
		isHidden
		lineageTag: 5ff0f2e0-5015-4370-9945-2e45eabff8e6

	measure Distr_Sales_AC =
			CALCULATE([Distr_Sales_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: b547c9dc-c62e-408b-a603-0a7de15de887

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PY =
			CALCULATE([Distr_Sales_Dyn_PY],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: 61969cd2-da7d-4723-b617-4ed1814b2b79

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_Dyn_PY = [Distr_Sales_Dyn_AC]/[Distr_Sales_Dyn_PY]-1
		isHidden
		lineageTag: e21d6e54-14e3-4e13-b9c1-2c29d60c529d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_AC_Total =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return SWITCH(SelectDim,
			    "Corporation",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Distr_Sales_AC],REMOVEFILTERS(ECom[E-com]))
			)
		isHidden
		lineageTag: d4cfe8eb-c3aa-4235-bfb6-2581eaf6f548

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PY_Total =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return SWITCH(SelectDim,
			    "Corporation",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Distr_Sales_PY],REMOVEFILTERS(ECom[E-com]))
			)
		isHidden
		lineageTag: c7ce902f-4f1f-44d9-ba87-0ea59fc23f8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_AC = CALCULATE([Distr_Sales_AC]/[Market_Sales_AC_Total])
		isHidden
		lineageTag: 40698152-9627-49aa-9c2b-a84c29d9602a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByVol_Dyn_AC =
			
			var CY=[Current_Year]
			return Calculate([SumByVol],FILTER(Periods,[PT]=0 && Periods[Year]=CY))
		isHidden
		lineageTag: 2dcdbfe6-0f60-4918-becc-0e42f8f6d222

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByVol = sum(Data[V])
		isHidden
		lineageTag: 6b4b6eab-d1da-48fa-9b69-42e31b0fda81

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByVol_Dyn_PY =
			
			var CY=[Current_Year]
			return Calculate([SumByVol],FILTER(Periods,[PT]=1 && Periods[Year]=CY))
		isHidden
		lineageTag: bdbe767b-a030-4f12-8fc4-01a92023f38c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Main_Currency_Name = SELECTEDVALUE('_CURRENCY_'[_CURRENCY_])
		isHidden
		lineageTag: cac0d676-209a-4f0b-ac7c-390588ad2bcf

	measure SumByCurrency =
			
			var selectedCurrency=SELECTEDVALUE(SelectCurrency[CurrencyName])
			return SWITCH(selectedCurrency,"USD",[SumByCurrency_USD],"EUR",[SumByCurrency_EUR])
		isHidden
		lineageTag: 6863e481-77fd-4aab-814d-bc858700e8f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByUSD_Dyn_AC =
			
			var CY=[Current_Year]
			return Calculate([SumByCurrency_USD],FILTER(Periods,[PT]=0 && Periods[Year]=CY))
		isHidden
		lineageTag: ffe902d5-8030-4ef4-bfeb-d0457f2d7dc5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByCurrency_USD = sum(Data[V_USD])
		isHidden
		lineageTag: f47c17b5-bd31-4ab5-a90e-ce3a9d6bfc15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByCurrency_EUR = sum(Data[V_EUR])
		isHidden
		lineageTag: b6605f99-facb-4d1c-b3e5-cf0ee1b8083a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByEUR_Dyn_AC =
			
			var CY=[Current_Year]
			return Calculate([SumByCurrency_EUR],FILTER(Periods,[PT]=0 && Periods[Year]=CY))
		isHidden
		lineageTag: 141ff65b-d4f2-4d26-be0b-ed5fad15ec75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByCurreency_Dyn_AC =
			
			var CY=[Current_Year]
			return Calculate([SumByCurrency],FILTER(Periods,[PT]=0 && Periods[Year]=CY))
		isHidden
		lineageTag: 0268f5a4-feca-46e0-9c76-aa5b945c065f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByCurreency_Dyn_PY =
			
			var CY=[Current_Year]
			return Calculate([SumByCurrency],FILTER(Periods,[PT]=1 && Periods[Year]=CY))
		isHidden
		lineageTag: 153b6a9b-a085-4598-b625-5c214401c881

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByPCS_Dyn_AC =
			
			var CY=[Current_Year]
			return Calculate([SumByPCS],FILTER(Periods,[PT]=0 && Periods[Year]=CY))
		isHidden
		lineageTag: 80047e18-3f70-46b5-ba65-d7b4895ef6da

	measure SumByPCS = sum(Data[Q])
		isHidden
		lineageTag: 0aa80221-2160-49be-b938-c6368135ae45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByPCS_Dyn_PY =
			
			var CY=[Current_Year]
			return Calculate([SumByPCS],FILTER(Periods,[PT]=1 && Periods[Year]=CY))
		isHidden
		lineageTag: 6e9c3779-e5b3-4be3-87f7-5f2b4683a0aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Expr_Dyn_AC_By_RX_OTC = ```
			
			var expr=SELECTEDVALUE(SelectExpr[ExprType])
			RETURN SWITCH(expr,
			    "SO",[Distr_Sales_Dyn_AC_All_Periods],
			    "MS",[Distr_Sales_Dyn_AC_All_Periods]/CALCULATE([Distr_Sales_Dyn_AC_All_Periods],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "EI",[Distr_Sales_Dyn_AC_All_Periods]/CALCULATE([Distr_Sales_Dyn_AC_All_Periods],REMOVEFILTERS(Drugs[Rx/OTC]))/
			         ([Market_Sales_Dyn_PY_All_Periods]/CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Rx/OTC])))*100
			)
			
			```
		isHidden
		lineageTag: a3289ff1-fabd-442a-aa89-aaf57073104c

		formatStringDefinition = [ExprFormat]

	measure SumByMeasure_AC_AllPeriods = [SumByMeasure]
		formatString: #,0
		isHidden
		lineageTag: aceaf851-beb4-497b-bb39-a6dc1ed97800

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Distr_Sales_Dyn_AC_All_Periods = CALCULATE([SumByMeasure_AC],REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(PeriodsFilter[Filter]))
		isHidden
		lineageTag: 412b2dd2-870b-4a03-a79e-4b1b5fc2fd7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_AC_Total_Dim =
			SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			    "Corporation",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Distr_Sales_Dyn_AC],REMOVEFILTERS(ECom[E-com]))
			
			)
		isHidden
		lineageTag: c3d81c1c-2a97-4bc2-bc89-01a0ca4356d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_PY_All_Periods = [Distr_Sales_Dyn_PY]
		formatString: 0
		isHidden
		lineageTag: 01d1290d-a2af-4682-bfdf-a7e3058af7da

	measure SumByMeasure_PY_AllPeriods = Calculate([SumByMeasure],FILTER(Periods,[PT]=1),REMOVEFILTERS(PeriodsFilter[SelectPeriod]))
		isHidden
		lineageTag: 0eadc237-eeb6-4820-a143-b4dba3db1a59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExprFormat = SWITCH(SELECTEDVALUE(SelectExpr[ExprType]),"SO","","MS","#0.0%","EI","")
		isHidden
		lineageTag: ab9af8a6-9e51-4523-b21a-99336dddb727

	measure Years_List = if(DISTINCTCOUNT(Periods[Year])>1,Min(Periods[Year])&".."&Max(Periods[Year]),SELECTEDVALUE(Periods[Year]))
		isHidden
		lineageTag: 09a24ade-2d82-43a2-9311-293e1bc28ca8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Expr_Dyn_AC_By_Dom_For = ```
			
			var expr=SELECTEDVALUE(SelectExpr[ExprType])
			RETURN SWITCH(expr,
			    "SO",[Distr_Sales_Dyn_AC_All_Periods],
			    "MS",[Distr_Sales_Dyn_AC_All_Periods]/CALCULATE([Distr_Sales_Dyn_AC_All_Periods],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "EI",[Distr_Sales_Dyn_AC_All_Periods]/CALCULATE([Distr_Sales_Dyn_AC_All_Periods],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)]))/
			         ([Market_Sales_Dyn_PY_All_Periods]/CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])))*100
			)
			
			```
		isHidden
		lineageTag: 510832f6-ef46-49ef-bd51-1b0542da05bb

		formatStringDefinition = [ExprFormat]

	measure Expr_Dyn_AC_By_Cat = ```
			
			var expr=SELECTEDVALUE(SelectExpr[ExprType])
			RETURN SWITCH(expr,
			    "SO",[Distr_Sales_Dyn_AC_All_Periods],
			    "MS",[Distr_Sales_Dyn_AC_All_Periods]/CALCULATE([Distr_Sales_Dyn_AC_All_Periods],REMOVEFILTERS(Drugs[CategoryShortName])),
			    "EI",[Distr_Sales_Dyn_AC_All_Periods]/CALCULATE([Distr_Sales_Dyn_AC_All_Periods],REMOVEFILTERS(Drugs[CategoryShortName]))/
			         ([Market_Sales_Dyn_PY_All_Periods]/CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[CategoryShortName])))*100
			)
			
			```
		isHidden
		lineageTag: 84030f7b-a3a3-45f4-9539-b970740a3f56

		formatStringDefinition = [ExprFormat]

	measure Expr_Dyn_AC_Ranked = ```
			
			var TopNValue=SELECTEDVALUE('TopN'[TOPN])
			var expr=SELECTEDVALUE(SelectExpr[ExprType])
			RETURN SWITCH(expr,
			    "SO",[Distr_Sales_Dyn_AC_Ranked],
			    "MS",[Market_MS_Dyn_AC_Ranked],
			    "EI",[Market_EI_Dyn_AC_Ranked]
			)
			
			```
		isHidden
		lineageTag: 1cea257d-bfb0-4573-9d43-f950fea0ede7

		formatStringDefinition = [ExprFormat]

	measure Distr_Sales_Dyn_AC_Ranked = if([RankByVol_AllPeriods]<=[TOP],[Distr_Sales_Dyn_AC_All_Periods],BLANK())
		isHidden
		lineageTag: 8ae10ae3-a947-4b1c-9749-cea1c10761e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByVol_AllPeriods = [RankByVol_TOTAL]
		formatString: 0
		isHidden
		lineageTag: 281342de-4ed5-4e26-9058-5d7e620e43da

	measure Market_Sales_Dyn_AC_Total_By_All_Periods = [TOTAL]
		isHidden
		lineageTag: 102cf16f-1348-4e01-91b3-efdd779e918e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_Dyn_AC_Ranked = if([RankByVol_AllPeriods]<=[TOP],[Distr_Sales_Dyn_AC_All_Periods]/[Market_Sales_Dyn_AC_Total_Dim],BLANK())
		isHidden
		lineageTag: 5179fc7f-819d-4196-9652-c570715ca4bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_EI_Dyn_AC_Ranked = ```
			
			var TopNValue=SELECTEDVALUE('TopN'[TOPN])
			return if([RankByVol_AllPeriods] <= TopNValue, 
			    ([Distr_Sales_Dyn_AC]/[Market_Sales_Dyn_AC_Total_Dim])/([Distr_Sales_Dyn_PY]/[Market_Sales_Dyn_PY_All_Periods_Total_Dim])*100,BLANK()
			)
			```
		isHidden
		lineageTag: 538e9adf-0601-48b8-98f0-8a3def452e49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_PY_All_Periods_Total_Dim = ```
			SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			    "Corporation",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Market_Sales_Dyn_PY_All_Periods],REMOVEFILTERS(ECom[E-com]))
			
			)
			
			```
		isHidden
		lineageTag: 501ad6b4-20e3-49f4-bc5a-10b247fb13be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_PY = CALCULATE([Distr_Sales_PY],Filter(Groups,Groups[IS_LOCAL]=1))
		isHidden
		lineageTag: f54fc36e-ea55-4ced-9c0b-d80792cdfe58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_AC_Formatted =
			
			var AC=[Self_Sales_AC]
			var mSign=SELECTEDVALUE(SelectMeasures[MeasureName])
			RETURN "AC: "& Format(AC,"### ### ##0")
		isHidden
		lineageTag: 58153ed4-7b6a-446c-9f51-e5083b75b60f

	measure Self_MS_AC = [Self_Sales_AC]/[Distr_Sales_AC]
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 03f61a7f-78c4-40ae-8ff7-5ceed88da0bc

	measure Self_MS_AC_Formatted =
			
			var MS=[Self_MS_AC]
			RETURN "MS,%: "& Format(MS,"0.0%")
		isHidden
		lineageTag: df343825-70e5-4cfc-9636-d0ba15f6d0e7

	measure Self_MS_PY = [Self_Sales_PY]/[Distr_Sales_PY]
		isHidden
		lineageTag: 881cbe4c-6edf-4c96-a6cb-14efff7ef2a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_EI_AC_Formatted =
			
			var EI=[Self_EI_AC]
			return "EI: "&format(EI,"# ##0")
		isHidden
		lineageTag: 70dec67d-c45c-483a-83f3-8677b87dc123

	measure Self_EI_AC = [Self_MS_AC]/[Self_MS_PY]*100
		formatString: 0
		isHidden
		lineageTag: 7e968390-394a-4181-a18c-da76b4478ad3

	measure Market_GR_PP = DIVIDE([Distr_Sales_AC],[Market_Sales_PP],blank())-1
		isHidden
		lineageTag: 0541edef-4615-4681-87df-5fde4159eca7

	measure Market_Sales_PP =
			
			var singlePeriodId=[Single_Period_Id]
			return CALCULATE([Market_Sales_Dyn_PP],Periods[setperiod]=singlePeriodId)
		isHidden
		lineageTag: 28fe69ae-6543-4329-a08a-098952e502d9

	measure SelfMO_ID =
			
			var SelfMO_ID=SELECTEDVALUE(SelfMOID[value])
			var customMO_ID=SELECTEDVALUE(SelectSelfMO[Market Org ID])
			var currentSelfMOID=if(customMO_ID=0,SelfMO_ID,customMO_ID)
			return currentSelfMOID
		formatString: 0
		isHidden
		lineageTag: cc356bda-2a81-4cee-bcc3-b179f335bdaf

	measure SelfMO_Name =
			"Self"
			//var selfMOName=SELECTEDVALUE(SelectSelfMO[Market Org])
			//return if(selfMOName="-- Default --","Self",selfMOName)
			//return if(not ISBLANK(selfMOName),selfMOName,LOOKUPVALUE(CompanyRoles[SelfMO_Name],CompanyRoles[AdminAsUser],1))
		isHidden
		lineageTag: 5b70ff77-9bb0-4a3f-a92e-d0f15de00e98

	measure SelfMO_Sales_Dyn_AC = CALCULATE([Distr_Sales_Dyn_AC],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: ba1a4698-e1a0-40a9-b6c9-7f6bd7a2d82c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_AC = CALCULATE([Distr_Sales_AC],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: 77259971-cb48-4431-8179-616222faa2b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_Dyn_PY = CALCULATE([Distr_Sales_Dyn_PY],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: 15e32374-b37a-494e-8d51-29aed2498d34

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_PY = CALCULATE([Distr_Sales_PY],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: 604ffffc-037a-4156-aea5-98adbb6c4f54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_PP = CALCULATE([Market_Sales_PP],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: ec87568a-f73e-40d1-a5b0-3964167b3382

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_Dyn_PP = CALCULATE([Market_Sales_Dyn_PP],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: f07fb726-e7c4-4ef6-8a18-5a1a8cf6bf24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_GR_PY = 1// if([SelfMO_Sales_PY]=0,BLANK(),[SelfMO_Sales_AC]/[SelfMO_Sales_PY]-1)
		isHidden
		lineageTag: d78af5e2-61ec-4010-95b7-27fccebb3f9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_GR_PP = DIVIDE([SelfMO_Sales_AC],[SelfMO_Sales_PP],BLANK())-1
		isHidden
		lineageTag: 9602af9c-ef8d-4132-a4d6-69aab39c37c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PCS_Dyn_AC = CALCULATE([SumByVol],Filter(Periods,Periods[PT]=0 && Periods[Year]=[Current_Year]))
		isHidden
		lineageTag: 30a97b36-8743-420f-af8b-cf8b5dd02584

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PCS_AC =
			CALCULATE([SumByPCS_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period])||ISFILTERED(Periods[MonthNum]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: 874e2875-7179-4637-8949-32d5e6b8142c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PCS_PY =
			CALCULATE([SumByPCS_Dyn_PY],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period])||ISFILTERED(Periods[MonthNum]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: 9efae8d1-1cd0-4328-a2da-f8a1159b0dd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_AC = DIVIDE([Distr_Sales_AC], [Market_Sales_PriceDivider_AC], BLANK())
		isHidden
		lineageTag: b0215397-9418-4a94-b86b-e50db4053a10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_VOL_AC =
			
			var singlePeriodId=[Single_Period_Id]
			return CALCULATE([SumByVol_Dyn_AC],Periods[setperiod]=singlePeriodId)
		isHidden
		lineageTag: ccd412d5-9670-484c-a246-a2d31649c574

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_VOL_PY =
			
			var singlePeriodId=[Single_Period_Id]
			return CALCULATE([SumByVol_Dyn_PY],Periods[setperiod]=singlePeriodId)
		isHidden
		lineageTag: e403feca-0c27-4186-ae7c-250e78c72a85

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_PY = DIVIDE([Distr_Sales_PY], [Market_Sales_PriceDivider_PY], BLANK())
		isHidden
		lineageTag: 36399060-6145-4b72-a8df-2824dac68826

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PCS_AC_Ranked = if([RankByVol]<=[TOP],[Market_Sales_PCS_AC],BLANK())
		isHidden
		lineageTag: 798f20ea-147b-4e42-b443-759e36486e13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PCS_PY_Ranked = if([RankByVol]<=[TOP],[Market_Sales_PCS_PY],BLANK())
		isHidden
		lineageTag: 3349df8a-7cc9-473c-bdb9-f857ca990cb9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_AC_Ranked = if([RankByVol]<=[TOP],[Market_Price_AC],BLANK())
		isHidden
		lineageTag: 724951f0-1bd6-4daa-9e26-ff37ff260de5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_PY_Ranked = if([RankByVol]<=[TOP],[Market_Price_PY],BLANK())
		isHidden
		lineageTag: 67092150-d608-4c5c-a0c7-c2dffa0858e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Empty_Space = " "
		isHidden
		lineageTag: dfca4256-6c32-42d1-9b2b-71e1cfa0a967

	measure Self_GR_AC_Formatted_With_Accent =
			
			var GR=[Self_GR_AC]
			var R=UNICHAR(128992)
			var G=UNICHAR(128994)
			RETURN if(GR<0,R,G)&"Self GR: "&Format(GR,"+0.0%;-#0.0%")
		isHidden
		lineageTag: 5f1087db-5385-436a-a40e-6d9b7fdba796

	measure Self_EI_AC_Formatted_With_Accent =
			
			var EI=[Self_EI_AC]
			var R=UNICHAR(128992)
			var G=UNICHAR(128994)
			RETURN if(EI<99.9,R,G)&"Self EI: "&Format(EI,"# ##0")
		isHidden
		lineageTag: 1bd747d8-7225-4699-ba3c-03682e25add0

	measure Self_Sales_Dyn_AC = CALCULATE([Distr_Sales_Dyn_AC],Filter(Groups,Groups[IS_LOCAL]=1))
		isHidden
		lineageTag: 8bdc7a8e-0161-4c25-bbcc-5f38123c003f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_Dyn_PY = CALCULATE([Distr_Sales_Dyn_PY],Filter(Groups,Groups[IS_LOCAL]=1))
		isHidden
		lineageTag: 6dd86d1b-0c6f-4b51-adb9-1159308ad328

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Price_AC = CALCULATE([Market_Price_AC],filter(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: 76cd884a-4dde-4897-9be1-e5fe8e768418

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Price_PY = CALCULATE([Market_Price_PY],filter(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: bc61f065-5138-460f-b53f-59ad552a5cab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_PCS_AC =
			CALCULATE([SumByPCS_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period])||ISFILTERED(Periods[MonthNum]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    ),
			    Filter(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID])
			)
		isHidden
		lineageTag: b3d0d595-b334-40c1-b09d-3de0eda5e24f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_PCS_PY =
			CALCULATE([SumByPCS_Dyn_PY],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period])||ISFILTERED(Periods[MonthNum]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    ),
			    Filter(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID])
			)
		isHidden
		lineageTag: ab6d72a9-a88f-4074-8d35-01b6af7a95fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_MS_AC = ([SelfMO_Sales_AC]/[Distr_Sales_AC])
		formatString: 0.00000
		isHidden
		lineageTag: 7ac03bbb-585e-4577-9652-ae934667b11a

	measure SelfMO_MS_PY = ([SelfMO_Sales_PY]/[Distr_Sales_PY])
		formatString: 0.00000
		isHidden
		lineageTag: 71d04d7f-1099-46ac-8dc3-440bf1c679e7

	measure SelfMO_EI_AC = Divide([SelfMO_MS_AC],[SelfMO_MS_PY],0)*100
		isHidden
		lineageTag: e0a3ea7d-39ff-4269-8d9e-a8a1f7b33d7c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_EI_PY = Divide([SelfMO_MS_PY],[SelfMO_MS_PPY],0)*100
		isHidden
		lineageTag: 5b8da4c4-da89-4776-923f-b0cb30647443

	measure SelfMO_MS_PPY = ([SelfMO_Sales_PPY]/[Market_Sales_PPY])
		isHidden
		lineageTag: 69465634-8be7-4225-9393-c2968eeb1c77

	measure SelfMO_Sales_PPY = CALCULATE([Market_Sales_PPY],FILTER(DrugsID,DrugsID[Market Org ID]=[SelfMO_ID]))
		isHidden
		lineageTag: e299483a-639d-4e23-8f26-045a2671effc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PPY =
			CALCULATE([Distr_Sales_Dyn_PPY],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: 3920b326-f0ab-4d8b-96f2-7e2242898461

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Dyn_PPY =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			VAR DeltaWeekDay = WEEKDAY(SelectedDate, 2) - WEEKDAY(EDATE(SelectedDate, -12), 2)
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			        "Daily",CALCULATE([SumByMeasure],ALL(Periods),DATEADD(DATEADD(Periods[Period],-2,YEAR),DeltaWeekDay,DAY)),
			        "YTD", Calculate(TOTALYTD([SumByMeasure], Periods[Period], ALL(Periods)),DATEADD(Periods[Period],-2,YEAR)),
			        "MTD",Calculate(TOTALMTD([SumByMeasure], Periods[Period], ALL(Periods)),DATEADD(Periods[Period],-2,YEAR)),
			        "MQT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-2,YEAR)),
			        "MMT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-2,YEAR)),
			        "MAT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-2,YEAR),-2,YEAR)),
			        "Custom",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY),-2,YEAR))
			    ),BLANK()
			)
		isHidden
		lineageTag: 6d9aa56b-4db2-44e4-bcfc-4c415a0d8dc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByVol_AC_AllPeriods =
			
			var curType=SELECTEDVALUE(_CURRENCY_[_CURRENCY_])
			return CALCULATE([SumByMeasure_AC],SelectMeasures[MeasureName]=curType)
		formatString: #,0
		isHidden
		lineageTag: 3281b445-602e-4730-b61f-1533fbf88397

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SumByEUR_AC_AllPeriods = CALCULATE([SumByMeasure_AC],SelectMeasures[MeasureName]="EUR")
		formatString: #,0
		isHidden
		lineageTag: 98633e4e-31c5-4069-9f56-fc54aa1ac4e5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SumByUSD_AC_AllPeriods = CALCULATE([SumByMeasure_AC],SelectMeasures[MeasureName]="USD")
		formatString: #,0
		isHidden
		lineageTag: a57c2b2e-d200-490c-b5f9-afc2b32b5eeb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SumByPCS_AC_AllPeriods = CALCULATE([SumByMeasure_AC],SelectMeasures[MeasureName]="pcs")
		formatString: #,0
		isHidden
		lineageTag: fca036c1-7ab5-441d-921b-458d58392c01

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SumByUSD_Dyn_PY =
			
			var CY=[Current_Year]
			return Calculate([SumByCurrency_USD],FILTER(Periods,[PT]=1 && Periods[Year]=CY))
		isHidden
		lineageTag: bc9eb35f-777d-4a08-9ad3-18201db1372b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByEUR_Dyn_PY =
			
			var CY=[Current_Year]
			return Calculate([SumByCurrency_EUR],FILTER(Periods,[PT]=1 && Periods[Year]=CY))
		isHidden
		lineageTag: 2e6e3aee-e8eb-4306-a355-cf53328ee3b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_VOL_GR_AC_AllPeriods = ([SumByVol_AC_AllPeriods]/[SumByVol_PY_AllPeriods]-1)
		isHidden
		lineageTag: c20403c5-3a14-4579-a1ee-13e06f11009b

	measure SumByVol_PY_AllPeriods = Calculate([SumByVol],FILTER(Periods,[PT]=1))
		isHidden
		lineageTag: e6ca43f9-ca61-4d59-9ce5-ec0edd841d43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_VOL_Min =
			
			var G=FILTER(SUMMARIZECOLUMNS(Periods[Year],Periods[IS_MAX_YEAR],"GR",DIVIDE([SumByVol_AC_AllPeriods],[SumByVol_PY_AllPeriods],0)-1),[GR]>-1 && Periods[IS_MAX_YEAR]="0")
			return minx(G,[GR])
		isHidden
		lineageTag: dd994b5f-5ad3-46d1-b290-06812f15e904

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_VOL_Max =
			
			var G=FILTER(SUMMARIZECOLUMNS(Periods[Year],Periods[IS_MAX_YEAR],"GR",DIVIDE([SumByVol_AC_AllPeriods],[SumByVol_PY_AllPeriods],0)-1),[GR]>-1 && Periods[IS_MAX_YEAR]="0")
			return maxx(G,[GR])
		isHidden
		lineageTag: c85a88d2-d6d2-43c9-b3a5-b56f4b6e7849

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_VOL = DIVIDE([SumByVol_Dyn_AC],[SumByVol_Dyn_PY],0)-1
		isHidden
		lineageTag: ce0eeb63-1af9-4822-a2c5-8b3208821016

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByBrandVol = RANKX(ALLSELECTED(Drugs[Brand]),[Distr_Sales_AC])
		formatString: 0
		isHidden
		lineageTag: 97587d21-110c-47ce-af0d-cdc65807ebf3

	measure Market_Sales_AC_Ranked_By_Brand = if([RankByBrandVol]<=[TOP],[Distr_Sales_AC],BLANK())
		isHidden
		lineageTag: 61166ae8-9927-4854-80b1-44274dd06eb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Rank_AC_Ranked_By_Brand = if([RankByBrandVol]<=[TOP],[RankByBrandVol],BLANK())
		formatString: 0
		isHidden
		lineageTag: 7c16ff16-d039-44b4-96fb-3dfe66cfd46f

	measure Market_Sales_PY_Ranked_By_Brand = if([RankByBrandVol]<=[TOP],[Distr_Sales_PY],BLANK())
		isHidden
		lineageTag: 037938c8-7e6e-4317-bcde-c7f972d1a0a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Brand_MS_AC_Ranked_By_Brand = if([RankByBrandVol]<=[TOP],[Brand_MS_AC],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 92208727-a7c1-4b32-b5d2-9fc723297f91

	measure Brand_MS_AC = [Distr_Sales_AC]/CALCULATE([Distr_Sales_AC],REMOVEFILTERS(Drugs[Brand]))
		isHidden
		lineageTag: cbb3eb9d-35a6-400a-8ef1-1d5aa48b45d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Brand_GR_AC_Ranked = if([RankByBrandVol]<=[TOP] && not ISBLANK([Distr_Sales_PY]),[Market_GR_PY],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 95c9140c-0877-4e6a-930b-eaefb90cd9ba

	measure Brand_EI_AC_Ranked = if([RankByBrandVol]<=[TOP] && not ISBLANK([Distr_Sales_PY]),[Brand_EI_AC],BLANK())
		isHidden
		lineageTag: 11426d6f-56cd-46ee-915f-80d214fe35e1

	measure Brand_MS_PY = [Distr_Sales_PY]/CALCULATE([Distr_Sales_PY],REMOVEFILTERS(Drugs[Brand]))
		isHidden
		lineageTag: 0859e95a-3db4-47b9-98d7-94c73a7f1a91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Brand_EI_AC = [Brand_MS_AC]/[Brand_MS_PY]*100
		isHidden
		lineageTag: 2d551b28-dc6a-4132-8a49-74ad8ab2e297

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_AC_Ranked_By_Brand = if([RankByBrandSelfMOVol]<=[TOP],[SelfMO_Sales_AC],BLANK())
		isHidden
		lineageTag: d2d962cd-6c27-430a-8965-df084f22b109

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByBrandSelfMOVol = RANKX(ALLSELECTED(Drugs[Brand]),[SelfMO_Sales_AC])
		formatString: 0
		isHidden
		lineageTag: 4350fa96-3672-42bd-b43a-111d84de316e

	measure SelfMO_Sales_PY_Ranked_By_Brand = if([RankByBrandSelfMOVol]<=[TOP],[SelfMO_Sales_PY],BLANK())
		isHidden
		lineageTag: add51fa1-e593-4144-8718-d9a23d333a04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Brand_MS_AC_Ranked_By_Brand = if([RankByBrandSelfMOVol]<=[TOP],[SelfMO_Brand_MS_AC],BLANK())
		isHidden
		lineageTag: 3047a371-f26b-42f7-b63d-ecf6a18ef858

	measure SelfMO_Brand_MS_AC = [SelfMO_Sales_AC]/CALCULATE([SelfMO_Sales_AC],REMOVEFILTERS(Drugs[Brand]))
		isHidden
		lineageTag: 2c02549d-ebe0-4aaf-9373-db65d0f42132

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Brand_MS_PY = [SelfMO_Sales_PY]/CALCULATE([SelfMO_Sales_PY],REMOVEFILTERS(Drugs[Brand]))
		isHidden
		lineageTag: f366c47a-afbe-45e7-9832-84ab14f51e76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Brand_EI_AC = [SelfMO_Brand_MS_AC]/[SelfMO_Brand_MS_PY]*100
		isHidden
		lineageTag: c74f2d20-199e-4791-98c0-3842fbfe665d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Brand_EI_AC_Ranked = if([RankByBrandSelfMOVol]<=[TOP] && not ISBLANK([SelfMO_Sales_AC]),[SelfMO_Brand_EI_AC],BLANK())
		isHidden
		lineageTag: 26e60405-e062-4117-a6f1-e37c0900d631

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Brand_GR_AC_Ranked = if([RankByBrandSelfMOVol]<=[TOP] && not ISBLANK([SelfMO_Sales_PY]),[Market_GR_PY],BLANK())
		isHidden
		lineageTag: 270af47e-6f83-4ddd-ad3e-618bcc80bfe6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByBrandGR = RANKX(ALLSELECTED(Drugs[Brand]),[SelfMO_GR_PY])
		formatString: 0
		isHidden
		lineageTag: a5923ec8-859b-46e2-8501-9f71727b788f

	measure SelfMO_Brand_GR_AC_Ranked_By_GR = if([RankByBrandGR]<=[TOP] && not ISBLANK([SelfMO_Sales_PY]),[Market_GR_PY],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 2f36043d-3867-4947-bd43-b879a95a89c5

	measure SelfMO_Brand_GR_Ranked_Top_Bottom =
			
			var tRank=RANKX(ALLSELECTED(Drugs[Brand]),[SelfMO_GR_PY])
			return if([SelfMO_Sales_AC] && tRank <= [TOP] , [SelfMO_GR_PY],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 9ceec403-ad17-4fba-9b8b-c904b8037fc1

	measure Market_GR_USD_Min =
			
			var G=FILTER(SUMMARIZECOLUMNS(Periods[Year],Periods[IS_MAX_YEAR],"GR",DIVIDE([SumByUSD_AC_AllPeriods],[SumByUSD_PY_AllPeriods],0)-1),[GR]>-1 && Periods[IS_MAX_YEAR]="0")
			return minx(G,[GR])
		isHidden
		lineageTag: c85e6bba-8d7b-4426-a68d-b038c9b35d6f

	measure SumByUSD_PY_AllPeriods = Calculate([SumByCurrency_USD],FILTER(Periods,[PT]=1))
		isHidden
		lineageTag: 254c073d-1078-4c0c-9c9a-8b653f37658d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_GR_AC = ([Self_Sales_AC]/[Self_Sales_PY]-1)
		isHidden
		lineageTag: 227d70d5-7c07-484b-84d9-d6668bde8c53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_EI_AC_Ranked_By_Group =
			
			var groupL=SELECTEDVALUE(GroupLevel[LevelName])
			 return if(
			    switch(groupL,
			        "1",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),[Self_Sales_AC],,DESC),
			        "2",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),[Self_Sales_AC],,DESC),
			        "3",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),[Self_Sales_AC],,DESC)
			    )<=[TOP],[Self_EI_AC],BLANK()
			)
		formatString: 0
		isHidden
		lineageTag: f1f06b4a-18e8-4008-9d0f-c965690f5c73

	measure Self_GR_AC_Ranked_By_Group =
			
			var groupL=SELECTEDVALUE(GroupLevel[LevelName])
			 return if(
			    switch(groupL,
			        "1",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),[Self_Sales_AC],,DESC),
			        "2",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),[Self_Sales_AC],,DESC),
			        "3",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),[Self_Sales_AC],,DESC),
			        "4",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),[Self_Sales_AC],,DESC),
			        "5",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),[Self_Sales_AC],,DESC)
			    )<=[TOP],[Self_GR_AC],BLANK()
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 987fb359-2e5e-474a-8ee8-03b46b07f343

	measure SelfMO_Sales_AC_Ranked_By_Group =
			
			var groupL=SELECTEDVALUE(GroupLevel[GroupLevel Fields])
			var ranked=switch(groupL,
			    "1",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),[SelfMO_Sales_AC],,DESC),
			    "2",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),[SelfMO_Sales_AC],,DESC),
			    "3",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),[SelfMO_Sales_AC],,DESC),
			    "4",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),[SelfMO_Sales_AC],,DESC),
			    "5",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),[SelfMO_Sales_AC],,DESC)
			)
			return if(ranked<=[TOP] && not ISBLANK([SelfMO_Sales_PY]),[SelfMO_Sales_AC],BLANK())
		isHidden
		lineageTag: c597a29c-c6c6-4ba6-a59c-fd578f93719a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_PY_Ranked = if([RankByVol]<=[TOP],[Market_MS_PY],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: cd429628-c111-42f5-9ec3-2df2f4b11c17

	measure MPY = [Distr_Sales_PY]/[Market_Sales_PY_Total]
		isHidden
		lineageTag: 0de22262-7107-453c-a9bc-0e13aa13cf76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GroupsMO_ID =
			
			var smid=SELECTEDVALUE(GroupsOrgID[value])
			var customMOID=SELECTEDVALUE(SelectSelfMO[Market Org ID])//works only if users is admin
			var currentSelfMOID=if(ISBLANK(smid),customMOID,selfmoid)
			return currentSelfMOID
		formatString: 0
		isHidden
		lineageTag: 80f83aab-03d3-42fb-b3eb-9b28dd900525

	measure Self_Sales_AC_Ranked_By_Group_WinLoss =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),([Market_WinLoss_AC]),,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),([Market_WinLoss_AC]),,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),([Market_WinLoss_AC]),,Desc,Dense)
			    )<=[TOP] ||
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Competitve group 1",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Competitve group 2",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Competitve group 3",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),-([Market_WinLoss_AC]),,Desc,Dense)
			    )<=[TOP],[Market_WinLoss_AC],BLANK()
			)
		isHidden
		lineageTag: cf8e3359-2a87-491e-9096-54af800db0f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_WinLoss_AC = ([Market_MS_AC]-[Market_MS_PY])*[Market_Sales_AC_Total]
		isHidden
		lineageTag: 06a401d2-7384-47e7-984a-1a32f2e7e085

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Addr_Sales_AC = CALCULATE([Distr_Sales_AC],Filter(Groups,Groups[IS_LOCAL] in {0,1}))
		isHidden
		lineageTag: 7027e20c-7322-4d13-8d16-8f5971dc8d36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero_AC_WinLoss = if(ISBLANK([Self_Sales_AC_Ranked_By_Group_WinLoss]),blank(),0)
		formatString: 0
		isHidden
		lineageTag: ecb089bf-c97c-4aa4-906e-c5f1ddeec9d6

	measure Self_Sales_AC_AGGR =
			SWITCH(
			    SELECTEDVALUE(AggrDim[AGGR_TYPE]),
			        "Month",CALCULATE([Self_Sales_AC],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"Month"}),
			        "YTD",CALCULATE([Self_Sales_AC],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"YTD"}),
			        "MAT",CALCULATE([Self_Sales_AC],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"YTD"})
			)
		isHidden
		lineageTag: cc6b1966-e985-40e7-ab91-1a3c438fedda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_PY_AGGR =
			SWITCH(
			    SELECTEDVALUE(AggrDim[AGGR_TYPE]),
			        "Month",CALCULATE([Self_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"Month"}),
			        "YTD",CALCULATE([Self_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"YTD"}),
			        "MAT",CALCULATE([Self_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"YTD"})
			)
		isHidden
		lineageTag: 1acb727f-1d6f-4efd-b957-3ee19642e717

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_AC_AGGR_Month = CALCULATE([Self_Sales_AC],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"Month"})
		isHidden
		lineageTag: 0293a3f2-2422-4d99-babc-cfc80d33521f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_AC_AGGR_YTD = CALCULATE([Self_Sales_AC],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"YTD"})
		isHidden
		lineageTag: ec023011-d562-4eec-a941-c4f4cea4ba56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_AC_AGGR_MAT = CALCULATE([Self_Sales_AC],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"MAT"})
		isHidden
		lineageTag: d58026ab-ba83-4e0b-bc60-0833cc0c3211

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_PY_AGGR_Month = CALCULATE([Self_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"Month"})
		isHidden
		lineageTag: d7fffcc5-064d-4550-9b57-aff6bfb5eea9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_PY_AGGR_MAT = CALCULATE([Self_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"MAT"})
		isHidden
		lineageTag: 2b9e2e68-609a-47cc-9719-a0c436db8711

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_Sales_PY_AGGR_YTD = CALCULATE([Self_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE] in {"YTD"})
		isHidden
		lineageTag: 2fac684a-18f1-475c-b89d-2583cf9bbaed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_Ranked2 = if([RankByVol]<=[TOP] && not ISBLANK([Market_Sales_PY]),[Market_GR_AC],BLANK())
		isHidden
		lineageTag: 794dd4ea-b9b4-434f-947c-0b7ed463cbc8

	measure RankByVolBottomN =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([Distr_Sales_AC]),1000000,
			    SWITCH(SelectDim,
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),-[Distr_Sales_AC],,DESC,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),-[Distr_Sales_AC],,DESC,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),-[Distr_Sales_AC],,DESC,Dense),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),-[Distr_Sales_AC],,DESC,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),-[Distr_Sales_AC],,DESC,Dense)
			    )
			)
		formatString: 0
		isHidden
		lineageTag: 64cbb7b8-ffd3-4510-a8a0-99fd2ed3a18e

	measure SelfMO_GR_AC_Ranked_By_Brand_WinLoss_Month =
			
			if(
			    rankx(ALLSELECTED(Drugs[Brand]),CALCULATE([SelfMO_Sales_AC]-[SelfMO_Sales_PY],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="Week"),,DESC,Dense)<=[TOP]||
			    rankx(ALLSELECTED(Drugs[Brand]),CALCULATE([SelfMO_Sales_PY]-[SelfMO_Sales_AC],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="Week"),,DESC,Dense)<=[TOP],
			    CALCULATE([SelfMO_Sales_AC]-[SelfMO_Sales_PY],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="Week"),BLANK()
			)
		isHidden
		lineageTag: 4c659b18-26a2-41ad-b237-65d3999d73b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero_AC_Self_GR_AC_Ranked_By_Brand_WinLoss_Month = if(ISBLANK([SelfMO_GR_AC_Ranked_By_Brand_WinLoss_Month]),blank(),0)
		formatString: 0
		isHidden
		lineageTag: 4fe8ae8b-4b30-4ccd-bf97-34fffb514f95

	measure SelfMO_GR_AC_Ranked_By_Brand_WinLoss_YTD =
			
			if(
			    rankx(ALLSELECTED(Drugs[Brand]),CALCULATE([SelfMO_Sales_AC]-[SelfMO_Sales_PY],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="YTD"),,DESC,Dense)<=[TOP]||
			    rankx(ALLSELECTED(Drugs[Brand]),CALCULATE([SelfMO_Sales_PY]-[SelfMO_Sales_AC],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="YTD"),,DESC,Dense)<=[TOP],
			    CALCULATE([SelfMO_Sales_AC]-[SelfMO_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="YTD"),
			    BLANK()
			)
		isHidden
		lineageTag: bd7af7ab-bf97-42b3-98de-28d3e3668d25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero_AC_Self_GR_AC_Ranked_By_Brand_WinLoss_YTD = if(ISBLANK([SelfMO_GR_AC_Ranked_By_Brand_WinLoss_YTD]),blank(),0)
		formatString: 0
		isHidden
		lineageTag: dde937f5-3890-4959-bee5-588e033898ec

	measure SelfMO_GR_AC_Ranked_By_Brand_WinLoss_MAT =
			
			if(
			    rankx(ALLSELECTED(Drugs[Brand]),CALCULATE([SelfMO_Sales_AC]-[SelfMO_Sales_PY],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="MAT"),,DESC,Dense)<=[TOP]||
			    rankx(ALLSELECTED(Drugs[Brand]),CALCULATE([SelfMO_Sales_PY]-[SelfMO_Sales_AC],all(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="MAT"),,DESC,Dense)<=[TOP],
			    CALCULATE([SelfMO_Sales_AC]-[SelfMO_Sales_PY],ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]="MAT"),
			    BLANK()
			)
		isHidden
		lineageTag: 0b1bb4a2-3b1b-490b-b101-af3da7415d4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero_AC_Self_GR_AC_Ranked_By_Brand_WinLoss_MAT = if(ISBLANK([SelfMO_GR_AC_Ranked_By_Brand_WinLoss_MAT]),blank(),0)
		formatString: 0
		isHidden
		lineageTag: 1ae2b8d4-1083-48a7-ad4c-ec6627ac22b5

	measure Current_Data_Type = var s="Distr" return s
		isHidden
		lineageTag: 84f2c11e-4f30-446a-9b0e-548c0c8e7a13

	measure Self_GR_AC_Ranked_By_WinLoss =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),[Market_WinLoss_AC],,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),[Market_WinLoss_AC],,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),[Market_WinLoss_AC],,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),[Market_WinLoss_AC],,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),[Market_WinLoss_AC],,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),[Market_WinLoss_AC],,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),[Market_WinLoss_AC],,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),[Market_WinLoss_AC],,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),[Market_WinLoss_AC],,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),[Market_WinLoss_AC],,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),[Market_WinLoss_AC],,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),[Market_WinLoss_AC],,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),[Market_WinLoss_AC],,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),[Market_WinLoss_AC],,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),[Market_WinLoss_AC],,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),[Market_WinLoss_AC],,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),[Market_WinLoss_AC],,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),[Market_WinLoss_AC],,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),[Market_WinLoss_AC],,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),[Market_WinLoss_AC],,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),[Market_WinLoss_AC],,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),[Market_WinLoss_AC],,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),[Market_WinLoss_AC],,Desc,Dense)
			    )<=[TOP] ||
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),-[Market_WinLoss_AC],,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),-[Market_WinLoss_AC],,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Competitve group 1",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Competitve group 2",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Competitve group 3",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),-[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),-[Market_WinLoss_AC],,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),-[Market_WinLoss_AC],,Desc,Dense)
			    )<=[TOP],DIVIDE([Distr_Sales_AC],[Distr_Sales_PY])-1,BLANK()
			)
		isHidden
		lineageTag: 4207e58c-cebd-4cc9-bf68-7640a816b4b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IsExportFieldSelected = CALCULATE ( IF ( ISFILTERED ( ExportFields[ExportFields Fields] ), 1, 0 ), ALLSELECTED ( ExportFields ) )
		formatString: 0
		isHidden
		lineageTag: c234db2d-e042-4893-85cd-46790ef591b8

	measure IsExportExprSelected = CALCULATE ( IF ( ISFILTERED ( ExportExpr[ExportExpr Fields] ), 2, 0 ), ALLSELECTED ( ExportExpr ) )
		formatString: 0
		isHidden
		lineageTag: f17441bd-ce44-4ac6-838b-6a902f0e410f

	measure Market_EI_AC_Ranked_By_WinLoss =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),([Market_WinLoss_AC]),,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),([Market_WinLoss_AC]),,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),([Market_WinLoss_AC]),,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),([Market_WinLoss_AC]),,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),([Market_WinLoss_AC]),,Desc,Dense)
			    )<=[TOP] ||
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Competitve group 1",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Competitve group 2",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Competitve group 3",rankx(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),-([Market_WinLoss_AC]),,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),-([Market_WinLoss_AC]),,Desc,Dense)
			    )<=[TOP],[Market_EI_AC],BLANK()
			)
		isHidden
		lineageTag: 256ac8f0-fa48-407e-8701-8650a821922c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Delta_EI = [SelfMO_EI_AC]-[SelfMO_EI_PY]
		isHidden
		lineageTag: e16981bc-a22f-45b8-9e0c-53f684301152

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_GR_AC_Ranked = if([RankByVol]<=[TOP] && not ISBLANK([Distr_Sales_PY]),[Market_GR_PY],BLANK())
		isHidden
		lineageTag: ddc31cd1-5e57-41a3-9b77-00b37384ab51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_Sales_AC_Ranked = if([RankBySelfMOVol]<=[TOP],[SelfMO_Sales_AC],BLANK())
		isHidden
		lineageTag: be173041-4320-4e51-9c6a-bcf487d3bdf0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankBySelfMOVol =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([SelfMO_Sales_AC]),1000000,
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),[SelfMO_Sales_AC],,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),[SelfMO_Sales_AC],,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),[SelfMO_Sales_AC],,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),[SelfMO_Sales_AC],,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),[SelfMO_Sales_AC],,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),[SelfMO_Sales_AC],,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),[SelfMO_Sales_AC],,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),[SelfMO_Sales_AC],,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Market status",rankx(ALLSELECTED(Drugs[Market_Status]),[SelfMO_Sales_AC],,Desc,Dense),
			        "Sales type",rankx(ALLSELECTED(ECom[E-com]),[SelfMO_Sales_AC],,Desc,Dense)
			    )
			)
		formatString: 0
		isHidden
		lineageTag: eab5583d-994e-4bf4-bc76-53174de60c58

	measure SelfMO_Sales_PY_Ranked = if([RankBySelfMOVol]<=[TOP],[SelfMO_Sales_PY],BLANK())
		isHidden
		lineageTag: d54c29d3-0cca-4c19-863b-ba7dfe979f45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_GR_AC_Ranked = if([RankBySelfMOVol]<=[TOP] && not ISBLANK([SelfMO_Sales_PY]),[SelfMO_GR_PY],BLANK())
		isHidden
		lineageTag: 51441b17-ef04-4a34-950c-50ddbe52e702

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByCurrency_AC_AllPeriods = Calculate([SumByCurrency],FILTER(Periods,[PT]=0))
		isHidden
		lineageTag: ee64dcb5-f715-43f9-a62b-579eeaeedef0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByCurrency_PY_AllPeriods = Calculate([SumByCurrency],FILTER(Periods,[PT]=1))
		isHidden
		lineageTag: 1579bfdf-48cf-4c4d-9282-07cded2c121a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelfMO_GR_AC_Ranked_By_Brand_WinLoss =
			
			if(
			    rankx(ALLSELECTED(Drugs[Brand]),[SelfMO_Sales_AC]-[SelfMO_Sales_PY],,DESC,Dense)<=[TOP]||
			    rankx(ALLSELECTED(Drugs[Brand]),[SelfMO_Sales_PY]-[SelfMO_Sales_AC],,DESC,Dense)<=[TOP],
			    [SelfMO_Sales_AC]-[SelfMO_Sales_PY],BLANK()
			)
		isHidden
		lineageTag: e3ef4c27-a546-42e0-81e2-10a685e91221

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero_AC_Self_GR_AC_Ranked_By_Brand_WinLoss = if(ISBLANK([SelfMO_GR_AC_Ranked_By_Brand_WinLoss]),blank(),0)
		formatString: 0
		isHidden
		lineageTag: b7543bd7-38eb-428b-938b-5c1ff62027d3

	measure SumByTABS_AC_AllPeriods = CALCULATE([SumByMeasure_AC],SelectMeasures[MeasureName]="tabs")
		isHidden
		lineageTag: 676777ff-64af-4b64-a308-34dac64a9ab8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByTABS = sum(Data[TABS])
		isHidden
		lineageTag: 4f6cf1c6-41f5-4685-ba4f-37201e3d9710

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByDDD_AC_AllPeriods = CALCULATE([SumByMeasure_AC],SelectMeasures[MeasureName]="DDD")
		isHidden
		lineageTag: c656f131-7acc-45a9-9652-e00002bb8041

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByDDD = sum(Data[DDD])
		isHidden
		lineageTag: 5c061440-eaac-42d3-94d3-02f84735d849

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceEUR_AC_AllPeriods = ([SumByEUR_AC_AllPeriods]/[SumByPCS_AC_AllPeriods])
		isHidden
		lineageTag: 9484fd3b-8003-4519-917d-28ec51e1b34c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceVOL_AC_AllPeriods = ([SumByVol_AC_AllPeriods]/[SumByPCS_AC_AllPeriods])
		isHidden
		lineageTag: ba01d9c1-dcd2-4221-83a9-30367dd1090e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceUSD_AC_AllPeriods = ([SumByUSD_AC_AllPeriods]/[SumByPCS_AC_AllPeriods])
		isHidden
		lineageTag: 8bddf393-445c-4a60-a341-c391f43d8a6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Expr_Dyn_AC_Ranked_Paginated = ```
			
			var expr=SELECTEDVALUE(SelectExpr[ExprType])
			RETURN SWITCH(expr,
			    "SO",[Market_Sales_Dyn_AC_Ranked_Paginated],
			    "MS",[Market_MS_Dyn_AC_Ranked_Paginated],
			    "EI",[Market_EI_Dyn_AC_Ranked_Paginated]
			)
			
			```
		isHidden
		lineageTag: 1a8de77b-7ac1-4a3e-9d9d-600ff37811ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			return if(currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_Dyn_AC_All_Periods],BLANK())
		isHidden
		lineageTag: 1ee88813-80b4-4ac2-89ba-31ddb704a550

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_EI_Dyn_AC_Ranked_Paginated = ```
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			return if(currentRank>=beginTop && currentRank<=endTop,([Distr_Sales_Dyn_AC_All_Periods]/[Market_Sales_Dyn_AC_Total_Dim])/([Market_Sales_Dyn_PY_All_Periods]/[Market_Sales_Dyn_PY_All_Periods_Total_Dim])*100,BLANK())
			
			```
		isHidden
		lineageTag: 51a441e1-5f94-4ce2-9ce6-294d629cac7f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_Dyn_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			return if(currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_Dyn_AC_All_Periods]/[Market_Sales_Dyn_AC_Total_Dim],BLANK())
		isHidden
		lineageTag: a945365e-188f-40ff-b95d-4bf5967ab03a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Paginated_Top_Dyn =
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var pagesCount=QUOTIENT([Dim_Count],itemsPerPage)+1
			var s="Top {FROM}..{TO}, page {PAGE} of {PAGES}"
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			return SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(ss,"{FROM}",beginTop),"{TO}",endTop),"{PAGE}",currentPage),"{PAGES}",pagesCount)
		isHidden
		lineageTag: 9bd6426f-6517-4673-8131-64805656f332

	measure Is_Page_Exists = QUOTIENT([Dim_Count],[TOP])+1-SELECTEDVALUE(SelectPages[Value])
		formatString: 0
		isHidden
		lineageTag: 6f5cf490-3d83-4ac4-b2b0-400279f5503f

	measure Dim_Pages_Count = Int([Dim_Count]/[TOP])+1
		formatString: 0
		isHidden
		lineageTag: d57deae4-bdee-4c31-9559-b31620b3a8e9

	measure Market_Sales_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_AC],BLANK())
		isHidden
		lineageTag: 99be397d-37c3-4782-9763-0bc986e80551

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Rank_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,currentRank,BLANK())
		formatString: 0
		isHidden
		lineageTag: ed2b6f2a-ebce-4e62-a432-650e47ec730b

	measure Market_GR_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,DIVIDE([Distr_Sales_AC],[Distr_Sales_PY])-1,BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 3aefad99-c8fa-47b6-8706-452bedf93de8

	measure Market_MS_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,[Market_MS_AC],BLANK())
		isHidden
		lineageTag: 2e18b0e6-5b2c-4549-bc1f-57285310091f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_EI_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop && not ISBLANK([Distr_Sales_PY]),[Market_EI_AC],BLANK())
		isHidden
		lineageTag: 412c0da1-6c98-47f7-ae6d-9e65ece383a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PY_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_PY],BLANK())
		isHidden
		lineageTag: 15ea128f-3e64-4cd8-8e79-cd34884728f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Self_GR_EI_Formatted_WithAccent = [Self_GR_AC_Formatted_With_Accent]&" "&[Self_EI_AC_Formatted_With_Accent]
		isHidden
		lineageTag: 43680824-7480-454a-8467-e5734aaf71a5

	measure Paginated_Top =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var pagesCount=QUOTIENT([Dim_Count],itemsPerPage)+1
			var s="Top {FROM}..{TO}, page {PAGE} of {PAGES}"
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			return SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(ss,"{FROM}",beginTop),"{TO}",endTop),"{PAGE}",currentPage),"{PAGES}",pagesCount)
		isHidden
		lineageTag: 4b3c6b0b-c46d-4f45-b108-9217623182d2

	measure Dim_Count =
			SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			    "Corporation",DISTINCTCOUNT(Drugs[Corporation]),
			    "Market Org",DISTINCTCOUNT(Drugs[Market Org]),
			    "Brand",DISTINCTCOUNT(Drugs[Brand]),
			    "Brand+Market Org",DISTINCTCOUNT(Drugs[Brand+Market Org]),
			    "Brand+Corporation",DISTINCTCOUNT(Drugs[Brand+Corporation]),
			    "SKU",DISTINCTCOUNT(Drugs[Full medication name]),
			    "INN",DISTINCTCOUNT(Drugs[INN]),
			    "Comp group L1",DISTINCTCOUNT(Groups[PRODUCT_NAME_TREE.1]),
			    "Comp group L2",DISTINCTCOUNT(Groups[PRODUCT_NAME_TREE.2]),
			    "Comp group L3",DISTINCTCOUNT(Groups[PRODUCT_NAME_TREE.3]),
			    "Comp group L4",DISTINCTCOUNT(Groups[PRODUCT_NAME_TREE.4]),
			    "Comp group L5",DISTINCTCOUNT(Groups[PRODUCT_NAME_TREE.5]),
			    "Category",DISTINCTCOUNT(Drugs[CategoryLongName]),
			    "Rx/OTC",DISTINCTCOUNT(Drugs[Rx/OTC]),
			    "ATC 1",DISTINCTCOUNT(Drugs[ATC Code (1)]),
			    "ATC 2",DISTINCTCOUNT(Drugs[ATC Code (2)]),
			    "ATC 3",DISTINCTCOUNT(Drugs[ATC Code (3)]),
			    "ATC 4",DISTINCTCOUNT(Drugs[ATC Code (4)]),
			    "ATC 5",DISTINCTCOUNT(Drugs[ATC Code (5)]),
			    "EphMRA 1",DISTINCTCOUNT(Drugs[EphMRA Code (1)]),
			    "EphMRA 2",DISTINCTCOUNT(Drugs[EphMRA Code (2)]),
			    "EphMRA 3",DISTINCTCOUNT(Drugs[EphMRA Code (3)]),
			    "EphMRA 4",DISTINCTCOUNT(Drugs[EphMRA Code (4)]),
			    "NFC 1",DISTINCTCOUNT(Drugs[NFC Code (1)]),
			    "NFC 2",DISTINCTCOUNT(Drugs[NFC Code (2)]),
			    "NFC 3",DISTINCTCOUNT(Drugs[NFC Code (3)]),
			    "Domestic/Foreign(maker)",DISTINCTCOUNT(Drugs[Domestic/Foreign(maker)]),
			    "Maker",DISTINCTCOUNT(Drugs[Maker]),
			    "Cosmetic 1",DISTINCTCOUNT(Drugs[Cosmetic Name(1)]),
			    "Cosmetic 2",DISTINCTCOUNT(Drugs[Cosmetic Name(2)]),
			    "Cosmetic 3",DISTINCTCOUNT(Drugs[Cosmetic Name(3)]),
			    "Cosmetic 4",DISTINCTCOUNT(Drugs[Cosmetic Name(4)]),
			    "Cosmetic 5",DISTINCTCOUNT(Drugs[Cosmetic Name(5)]),
			    "Bad 1",DISTINCTCOUNT(Drugs[BAD Name(1)]),
			    "Bad 2",DISTINCTCOUNT(Drugs[BAD Name(2)]),
			    "MC 1",DISTINCTCOUNT(Drugs[MC Name(1)]),
			    "MC 2",DISTINCTCOUNT(Drugs[MC Name(2)]),
			    "MC 3",DISTINCTCOUNT(Drugs[MC Name(3)]),
			    "MC 4",DISTINCTCOUNT(Drugs[MC Name(4)]),
			    "Market status",DISTINCTCOUNT(Drugs[Market_Status]),
			    "Sales type",DISTINCTCOUNT(ECom[E-com])
			)
		formatString: 0
		isHidden
		lineageTag: 7b6f7a65-d560-403c-97dc-33d3b97a7463

	measure Is_Page_Dyn_Exists = QUOTIENT([Dim_Count],[TOP])+1-SELECTEDVALUE(SelectPagesDyn[Value])
		formatString: 0
		isHidden
		lineageTag: ac3b3bbf-2135-415e-aed4-ac51be8ed563

	measure Market_Sales_Dyn_SummaryTable_AC =
			
			var FieldsCount=COUNTROWS(DISTINCT(ExportFields[ExportFields]))
			return if(FieldsCount>0,[Distr_Sales_AC],BLANK())
		isHidden
		lineageTag: 572e5e59-0a3f-4d5d-a4af-1077a9df6115

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Header_Filters_With_Pages =
			
			var cf=[Current_Filters]
			return if(len(cf)>0,cf&", ","")&[Paginated_Top]
		isHidden
		lineageTag: c6c62984-d2ff-45df-bcbb-4df69e26e7bd

	measure SelfMO_Rank_AC_Ranked = if([RankBySelfMOVol]<=[TOP],[RankBySelfMOVol],BLANK())
		formatString: 0
		isHidden
		lineageTag: 38b647bc-51a0-4856-b4bf-38031873d236

	measure SelfMO_EI_PP = Divide([SelfMO_MS_AC],[SelfMO_MS_PP],0)*100
		isHidden
		lineageTag: aace6d4f-586d-4940-8055-58dbe452cceb

	measure SelfMO_MS_PP = ([SelfMO_Sales_PP]/[Market_Sales_PP])
		formatString: 0.00000
		isHidden
		lineageTag: f22654ca-fc9d-4677-8b75-3938e0544c07

	measure SelfMO_Delta_EI_PP = [SelfMO_EI_AC]-[SelfMO_EI_PP]
		isHidden
		lineageTag: 7f373703-f73a-43d7-b93b-5cc91f3209c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IsGroupIsSelf = if(SELECTEDVALUE(Groups[ORGANIZATION])=[GroupsMO_ID],1,0)
		formatString: 0
		isHidden
		lineageTag: 48c5671d-8dec-4990-b58e-be1e90d6ba8a

	measure PRT_Dyn_AC = DIVIDE([Clients_With_Stock_Dyn_AC], [Stock_Clients_Count_Total_Dyn_AC])
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: eda8c5f2-baee-4924-8495-b446d5dc5376

	measure PRTByMeasure = CALCULATE(DISTINCTCOUNT(DataStock[CLIENT_ID]),[Distr_Stock_Dyn_AC]>0)/calculate(DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]))
		isHidden
		lineageTag: fa55f4ce-cd80-4bd8-b1c5-790089c71b58

	measure RankByPRT_AllPeriods = [TOTAL_PRT]
		isHidden
		lineageTag: 125d910d-fc9a-4e91-aca8-d621320aac52

	measure PRTBMeasure_AC_AllPeriods = CALCULATE([PRTByMeasure],Periods[PT]="0",ALLSELECTED(Periods[PeriodDate]))
		isHidden
		lineageTag: 01bb278d-1117-49d9-b593-09c1677fd803

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_Dyn_AC_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankBySKUVol_AllPeriods]
			return if(currentRank>=beginTop && currentRank<=endTop,[PRT_Dyn_AC_All_Periods],BLANK())
		formatString: 0.0
		isHidden
		lineageTag: 12d837a1-3dae-4d25-813c-dd0417adb995

	measure Is_Page_Dyn_Exists_PRT = QUOTIENT(DISTINCTCOUNT(Drugs[Full medication name]),[TOP])+1-SELECTEDVALUE(SelectPagesDyn[Value])
		formatString: 0
		isHidden
		lineageTag: 83d7e25c-01c2-45d4-b2a8-add629a1e6ce

	measure RankBySKUVol = RANKX(ALLSELECTED(Drugs[Full medication name]),[Distr_Sales_AC])
		formatString: 0
		isHidden
		lineageTag: fdb63070-d3be-4780-a7a4-d8cddf68cf27

	measure RankBySKUVol_AllPeriods =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([Market_Sales_Dyn_AC_Total_By_All_Periods]),1000000,
			        rankx(ALLSELECTED(Drugs[Full medication name]),[Market_Sales_Dyn_AC_Total_By_All_Periods],,DESC,Dense)
			)
		formatString: 0
		isHidden
		lineageTag: 8c25bfe7-f03b-4ea9-86db-c9bc53a0c6e4

	measure PRT_Dyn_AC_All_Periods = Calculate([PRTByMeasure],FILTER(Periods,[PT]=0))
		isHidden
		lineageTag: c426db1d-cff0-4f23-88e5-fee49eb65918

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Paginated_Top_Dyn_SKU =
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var pagesCount=QUOTIENT(DISTINCTCOUNT(Drugs[Full medication name]),itemsPerPage)+1
			var s="Top {FROM}..{TO}, page {PAGE} of {PAGES}"
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			return SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(ss,"{FROM}",beginTop),"{TO}",endTop),"{PAGE}",currentPage),"{PAGES}",pagesCount)
		isHidden
		lineageTag: 6285e170-b3c8-4962-a550-da3fc8396553

	measure PRT_Dyn_PY_All_Periods = Calculate([PRTByMeasure],FILTER(Periods,[PT]=1))
		isHidden
		lineageTag: 75af7e0b-ec11-4651-bee3-208fbd6e19b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_Dyn_PY_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPagesDyn[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankBySKUVol_AllPeriods]
			return if(currentRank>=beginTop && currentRank<=endTop && not ISBLANK([PRT_Dyn_AC_All_Periods]),[PRT_Dyn_PY_All_Periods],BLANK())
		isHidden
		lineageTag: 704d455a-d549-47ae-9920-b21399152b4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Years_List_All = [Years_List]
		isHidden
		lineageTag: 78320726-6a80-4da9-b1d5-b3a724710bcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_AC_AGGR =
			
			var currentAggr=SELECTEDVALUE(AggrDim[AGGR_TYPE])
			return if(ISFILTERED(Periods[Period])||ISFILTERED(Periods[MonthNum]),
			            CALCULATE([Market_Sales_Dyn_AC], ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]=currentAggr),
			            if(ISFILTERED(SinglePeriod),
			                CALCULATE([Market_Sales_Dyn_AC], ALL(Periods[AGGR_TYPE]),Periods[setperiod] in values(SinglePeriod[PERIOD_ID]) && Periods[AGGR_TYPE]=currentAggr),
			                CALCULATE([Market_Sales_Dyn_AC], ALL(Periods[AGGR_TYPE]),Periods[setperiod]=max(SinglePeriod[PERIOD_ID]) && Periods[AGGR_TYPE]=currentAggr)
			            )
			        )
		isHidden
		lineageTag: 13023372-36e9-487d-9c6f-580976f67fa3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_AC_AGGR_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,[Market_Sales_AC_AGGR],BLANK())
		isHidden
		lineageTag: 8d099fb4-9fb0-49c9-af63-5e440afff5fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_AGGR = ([Market_Sales_AC_AGGR]/[Market_Sales_PY_AGGR])-1
		isHidden
		lineageTag: 8c8a3dec-2a32-4369-9cf2-ce0ca4ecf953

	measure Market_Sales_PY_AGGR =
			
			var currentAggr=SELECTEDVALUE(AggrDim[AGGR_TYPE])
			return if(ISFILTERED(Periods[Period])||ISFILTERED(Periods[MonthNum]),
			            CALCULATE([Market_Sales_Dyn_PY], ALL(Periods[AGGR_TYPE]),Periods[AGGR_TYPE]=currentAggr),
			            if(ISFILTERED(SinglePeriod),
			                CALCULATE([Market_Sales_Dyn_PY], ALL(Periods[AGGR_TYPE]),Periods[setperiod] in values(SinglePeriod[PERIOD_ID]) && Periods[AGGR_TYPE]=currentAggr),
			                CALCULATE([Market_Sales_Dyn_PY], ALL(Periods[AGGR_TYPE]),Periods[setperiod]=max(SinglePeriod[PERIOD_ID]) && Periods[AGGR_TYPE]=currentAggr)
			            )
			        )
		isHidden
		lineageTag: 8e636c85-8ed2-4e8f-a1d9-8fea92802ce7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_AGGR_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,DIVIDE([Market_Sales_AC_AGGR],[Market_Sales_PY_AGGR])-1,BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 18f445d8-b668-496e-913d-84466655a16f

	measure Market_MS_AC_AGGR = CALCULATE([Market_Sales_AC_AGGR]/[Market_Sales_AC_AGGR_Total])
		isHidden
		lineageTag: 62835cba-06ca-458f-af09-b6317c335a49

	measure Market_MS_AC_AGGR_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop,[Market_MS_AC_AGGR],BLANK())
		isHidden
		lineageTag: c357b8a8-9184-4174-9597-ceb07070fd7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_AC_AGGR_Total =
			
			var aggr=SELECTEDVALUE(AggrDim[AGGR_TYPE])
			return CALCULATE([Market_Sales_AC_Total],all(AggrDim[AGGR_TYPE]),Periods[AGGR_TYPE] in {aggr})
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 58bb1778-ca4e-4958-9505-1b1428ca1d12

	measure Market_Sales_PY_AGGR_Total =
			
			var aggr=SELECTEDVALUE(AggrDim[AGGR_TYPE])
			return CALCULATE([Market_Sales_PY_Total],all(AggrDim[AGGR_TYPE]),Periods[AGGR_TYPE] in {aggr})
		isHidden
		lineageTag: a61bde9b-0560-4267-ae02-6630a3961fc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_EI_AC_AGGR = [Market_MS_AC_AGGR]/[Market_MS_PY_AGGR]*100
		isHidden
		lineageTag: 3567eff6-585b-4579-8b58-57dd23895f8d

	measure Market_MS_PY_AGGR = [Market_Sales_PY_AGGR]/[Market_Sales_PY_AGGR_Total]
		isHidden
		lineageTag: 8362f294-e7ed-4f4c-abb1-16eb6503b0d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_EI_AC_AGGR_Ranked_Paginated =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			return if(currentRank>=beginTop && currentRank<=endTop && not ISBLANK([Market_Sales_PY_AGGR]),[Market_EI_AC_AGGR],BLANK())
		formatString: 0
		isHidden
		lineageTag: 2edf73d1-0053-4c65-be65-25c44f01931e

	measure IS_Ecom_Allow = CALCULATE(MIN(DataTypes[DataType]), FILTER(DataTypes,DataTypes[DataType]="ECOM"))
		isHidden
		lineageTag: 03a2cfa0-b174-4550-bca6-a572c0b75377

	measure Expr_Dyn_AC_Ranked_Paginated_TopN_Self = ```
			
			var expr=SELECTEDVALUE(SelectExpr[ExprType])
			RETURN SWITCH(expr,
			    "SO",[Market_Sales_Dyn_AC_Ranked_Paginated_TopN_Self],
			    "MS",[Market_MS_Dyn_AC_Ranked_Paginated_TopN_Self],
			    "EI",[Market_EI_Dyn_AC_Ranked_Paginated_TopN_Self],
			    "GR",[Market_GR_Dyn_AC_Ranked_Paginated_TopN_Self]
			)
			
			```
		isHidden
		lineageTag: c1f06ab7-cb0c-48c8-9571-76cc72d40eec

	measure Market_Sales_Dyn_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_TOTAL]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Distr_Sales_Dyn_AC],BLANK())
		isHidden
		lineageTag: 6d3836cb-357f-4b3f-9938-4ab543e20d56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByVol_AllPeriods_TopN_Self =
			[RankByVol_TOTAL_TopN_Self]
			// var id1=SELECTEDVALUE(Drugs[Market Org ID])
			// var drugsTable=Filter(ALLSELECTED(Drugs),Drugs[Market Org ID]=[SelfMO_ID])
			// return if(id1<>[SelfMO_ID],blank(),
			//     if(SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			//         "SKU",RANKX(drugsTable,CALCULATE([Market_Sales_Dyn_AC],REMOVEFILTERS(PeriodsFilter),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(PeriodsFilter[Filter]),ALLEXCEPT(Drugs,Drugs[Full medication name])),,DESC,Dense),
			//         "Brand",RANKX(drugsTable,CALCULATE([Market_Sales_Dyn_AC],REMOVEFILTERS(PeriodsFilter),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(PeriodsFilter[Filter]),ALLEXCEPT(Drugs,Drugs[Brand])),,DESC,Dense),
			//         "Market Org",RANKX(drugsTable,CALCULATE([Market_Sales_Dyn_AC],REMOVEFILTERS(PeriodsFilter),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(PeriodsFilter[Filter]),ALLEXCEPT(Drugs,Drugs[Market Org])),,DESC,Dense),
			//         "Brand+Market Org",RANKX(drugsTable,CALCULATE([Market_Sales_Dyn_AC],REMOVEFILTERS(PeriodsFilter),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(PeriodsFilter[Filter]),ALLEXCEPT(Drugs,Drugs[Brand+Market Org])),,DESC,Dense),
			//         "Corporation",RANKX(drugsTable,CALCULATE([Market_Sales_Dyn_AC],REMOVEFILTERS(PeriodsFilter),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(Periods[Period]),REMOVEFILTERS(PeriodsFilter[Filter]),ALLEXCEPT(Drugs,Drugs[Corporation])),,DESC,Dense),
			//         BLANK()
			//     ) =1,1,BLANK())
			// )
		formatString: 0
		isHidden
		lineageTag: 0174aae5-c222-4fe5-a326-c10438ab950e

	measure Market_MS_Dyn_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Distr_Sales_Dyn_AC]/[Market_Sales_Dyn_AC_Total_Dim],BLANK())
		isHidden
		lineageTag: 206d2ec4-df09-4c2f-a914-2fbcb0ce5b2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_EI_Dyn_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,
			    ([Distr_Sales_Dyn_AC]/[Market_Sales_Dyn_AC_Total_Dim])
			    /
			    ([Distr_Sales_Dyn_PY]/[Market_Sales_Dyn_PY_Total_Dim])*100,
			    BLANK()
			)
		isHidden
		lineageTag: 6b92e003-7afb-4df6-b081-4aa0ff0cfaac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Distr_Sales_AC],BLANK())
		isHidden
		lineageTag: 50b0586b-ef18-4cd6-8659-d257381cb6db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByVol_TopN_Self =
			[RankByVol_TOTAL_TopN_Self]
			// var id1=SELECTEDVALUE(Drugs[Market Org ID])
			// var drugsTable=Filter(ALLSELECTED(Drugs),Drugs[Market Org ID]=[SelfMO_ID])
			// return if(id1<>[SelfMO_ID],blank(),
			//     if(SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			//         "SKU",RANKX(drugsTable,CALCULATE([Market_Sales_AC],ALLEXCEPT(Drugs,Drugs[Full medication name]),REMOVEFILTERS(PeriodsFilter[Filter])),,DESC,Dense),
			//         "Brand",RANKX(drugsTable,CALCULATE([Market_Sales_AC],ALLEXCEPT(Drugs,Drugs[Brand],Drugs[Market Org]),REMOVEFILTERS(PeriodsFilter[Filter])),,DESC,Dense),
			//         "Market Org",RANKX(drugsTable,CALCULATE([Market_Sales_AC],ALLEXCEPT(Drugs,Drugs[Market Org]),REMOVEFILTERS(PeriodsFilter[Filter])),,DESC,Dense),
			//         "Brand+Market Org",RANKX(drugsTable,CALCULATE([Market_Sales_AC],ALLEXCEPT(Drugs,Drugs[Brand+Market Org]),REMOVEFILTERS(PeriodsFilter[Filter])),,DESC,Dense),
			//         "Corporation",RANKX(drugsTable,CALCULATE([Market_Sales_AC],ALLEXCEPT(Drugs,Drugs[Corporation]),REMOVEFILTERS(PeriodsFilter[Filter])),,DESC,Dense),
			//         BLANK()
			//     )=1,1,BLANK())
			// )
		formatString: 0
		isHidden
		lineageTag: 0aed5495-28ec-4914-826c-1ddbf4460356

	measure Market_Sales_PY_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Distr_Sales_PY],BLANK())
		isHidden
		lineageTag: e0d2ad2e-b7bd-4482-9427-35df4f180e82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if(currentRank>=beginTop && currentRank<=endTop||currentRankSelf=1,DIVIDE([Distr_Sales_AC],[Distr_Sales_PY])-1,BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: e1b7bb83-721c-4b90-91ec-246813f25373

	measure Market_Rank_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if(currentRank>=beginTop && currentRank<=endTop||selfRank=1,currentRank,BLANK())
		formatString: 0
		isHidden
		lineageTag: 2ab35b0e-c419-4da5-8a40-840a2cc1e7c4

	measure Market_MS_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if(currentRank>=beginTop && currentRank<=endTop||selfRank=1,[Market_MS_AC],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 949a34f5-9d33-4b51-9cfe-92d14ea7dffb

	measure Market_EI_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if(((currentRank>=beginTop && currentRank<=endTop)||selfRank=1) && not ISBLANK([Distr_Sales_PY]),[Market_EI_AC],BLANK())
		isHidden
		lineageTag: 136f34e0-feaa-4b47-b8b3-289dcdc3fba0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_AC_AGGR_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||selfRank=1,[Market_Sales_AC_AGGR],BLANK())
		isHidden
		lineageTag: 13cb3f44-6143-4bd7-89a1-7adf9f2755ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_AGGR_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||selfRank=1,DIVIDE([Market_Sales_AC_AGGR],[Market_Sales_PY_AGGR])-1,BLANK())
		isHidden
		lineageTag: 7f372593-4c5c-4d8d-8ecb-7c129a19e0d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_MS_AC_AGGR_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||selfRank=1,[Market_MS_AC_AGGR],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: ef267981-ea3f-423d-a7ca-0608eeb8ccb6

	measure Market_EI_AC_AGGR_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var selfRank=[RankByVol_TopN_Self]
			return if(((currentRank>=beginTop && currentRank<=endTop)||selfRank=1) && not ISBLANK([Market_Sales_PY_AGGR]),[Market_EI_AC_AGGR],BLANK())
		isHidden
		lineageTag: c14d19be-ceef-41b2-a128-d769f716c0d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MS_Vol_Dyn_AC_AllPeriods = CALCULATE([SumByVol_AC_AllPeriods])/CALCULATE([SumByVol_AC_AllPeriods],REMOVEFILTERS(Drugs))
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 7a9be232-344c-4651-87af-88b6a36a5556

	measure Market_Sales_Dyn_AC_Total_AllPeriods = CALCULATE([Market_Sales_Dyn_AC_Total_By_All_Periods],REMOVEFILTERS(Drugs))
		isHidden
		lineageTag: 283cc149-2fd5-4b59-a3d3-c86e1f76cd3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MS_Vol_Dyn_PY_AllPeriods = CALCULATE([SumByVol_PY_AllPeriods])/CALCULATE([SumByVol_PY_AllPeriods],REMOVEFILTERS(Drugs))
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: f13e4d9d-f68e-4a3f-94ac-075268215ba6

	measure EI_Vol_Dyn_AC_AllPeriods = ([MS_Vol_Dyn_AC_AllPeriods]/[MS_Vol_Dyn_PY_AllPeriods])*100
		formatString: 0
		isHidden
		lineageTag: f1017257-7ce8-4279-ba48-df8e662ef145

	measure SelfMO_Name_For_Header =
			
			var selfMOName=SELECTEDVALUE(SelectSelfMO[Market Org])
			var s="self"
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			return if(selfMOName in {"-- Default --","-- Disable --"},ss,selfMOName)
		isHidden
		lineageTag: 5cda13b8-4964-4885-a94a-e4fe587500bb

	measure Market_Sales_AC_Ranked_TopN_Self =
			
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if(currentRank<=[TOP]||currentRankSelf>=1,[Distr_Sales_AC],BLANK())
		isHidden
		lineageTag: 386b559b-f9d8-4d83-959b-add8ad1f6c93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Rank_AC_Ranked_TopN_Self = if([RankByVol]<=[TOP]||[RankByVol_TopN_Self]=1,[RankByVol],BLANK())
		formatString: 0
		isHidden
		lineageTag: 682ff3ea-d931-4bf5-914c-d992d488b0ef

	measure Market_Sales_PY_Ranked_TopN_Self =
			
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if(currentRank<=[TOP]||currentRankSelf>=1,[Distr_Sales_PY],BLANK())
		isHidden
		lineageTag: be7669b0-4a7a-4730-a3bb-f58e328e78b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_AC_Ranked_TopN_Self = if(([RankByVol]<=[TOP]||[RankByVol_TopN_Self]=1) && not ISBLANK([Distr_Sales_PY]),[Market_GR_PY],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 3b926779-a701-427c-ae25-d1bb2c0f26c5

	measure Market_Price_Dyn_AC = DIVIDE([Distr_Sales_Dyn_AC], [Market_Sales_PriceDivider_AC], BLANK())
		isHidden
		lineageTag: 694ee2b0-f713-493b-95c7-86d1a38ccbcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Market_Price_AC],BLANK())
		isHidden
		lineageTag: cc1cde7e-6fd9-4e23-a75b-dff472303fe6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_PY_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Market_Price_PY],BLANK())
		isHidden
		lineageTag: 58be67c2-5da5-4b7b-adbe-4f98c718da8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_Dyn_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Market_Price_Dyn_AC],BLANK())
		isHidden
		lineageTag: 164063cc-8c80-4d1a-a13b-37079bc29f0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PCS_Dyn_AC_All_Periods = [SumByPCS_AC_AllPeriods]
		isHidden
		lineageTag: a13e31d6-0ddc-4587-92ad-1a3d8bf634cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_Dyn_AC_All_Periods = Divide([Distr_Sales_Dyn_AC_All_Periods],[Market_Sales_PriceDivider_Dyn_AC_All_Periods],BLANK())
		isHidden
		lineageTag: 6d0246c4-6597-47ff-954d-6cc6881b323b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_Dyn_PY_All_Periods = Divide([Market_Sales_Dyn_PY_All_Periods],[Market_Sales_PriceDivider_Dyn_PY_All_Periods],BLANK())
		isHidden
		lineageTag: 9c843be8-2356-4637-bf64-f35449bab6d1

	measure Market_Sales_PCS_Dyn_PY_All_Periods = [SumByPCS_PY_AllPeriods]
		isHidden
		lineageTag: e6bf99b5-3362-4b57-a493-250b5fcb99f9

	measure SumByPCS_PY_AllPeriods = Calculate([SumByPCS],FILTER(Periods,[PT]=1))
		isHidden
		lineageTag: 098b5d9c-2a9f-4615-b196-ebe4a68819a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Price_Dyn_PY_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Market_Price_Dyn_PY],BLANK())
		isHidden
		lineageTag: e10676fb-9cfe-4272-b721-4978b46cb470

	measure ExprType_SO = "SO"
		isHidden
		lineageTag: c15ef671-cdfc-4d7b-af55-23c0f82918af

	measure Market_Price_GR_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol]
			var currentRankSelf=[RankByVol_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,if([Market_Price_PY]>0,DIVIDE([Market_Price_AC],[Market_Price_PY])-1,BLANK()),BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: c679eb8c-2fe2-4e06-85cf-35375e30084f

	measure SumByMeasure_PriceDivider =
			
			var measureType=SELECTEDVALUE(SelectMeasures[MeasureName])
			var curType=SELECTEDVALUE(_CURRENCY_[_CURRENCY_])
			return SWITCH(TRUE(),
			        measureType in {"pcs",curType,"USD","EUR"},sum(Data[Q]),
			        measureType in {curType&"/tabs","USD/tabs","EUR/tabs"},sum(Data[TABS]),
			        measureType in {curType&"/DDD","USD/DDD","EUR/DDD"},sum(Data[DDD]),
			        FALSE(),1
			    )
		isHidden
		lineageTag: 20f9201a-2b1f-42bd-9804-74a8bd4ccd1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByMeasure_PriceDivider_AC_AllPeriods = [SumByMeasure_PriceDivider]
		isHidden
		lineageTag: 300655da-780f-4fa5-8586-88bcac072a3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_Dyn_AC =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([SumByMeasure_PriceDivider]),
			            "YTD",TOTALYTD([SumByMeasure_PriceDivider],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([SumByMeasure_PriceDivider],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		isHidden
		lineageTag: 9ed37499-9ef4-4d50-97e3-87161b1326b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_Dyn_PY = ```
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			VAR PYMaxDate = LOOKUPVALUE(Periods[DatePY], Periods[Period], MAX(Periods[Period]))
			VAR PYMinDate = PYMaxDate - delta + 1 
			return if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			        "Daily",CALCULATE([SumByMeasure_PriceDivider],ALL(Periods),TREATAS(VALUES(Periods[DatePY]),Periods[Period])),
			        "YTD",TOTALYTD([SumByMeasure_PriceDivider], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MTD",TOTALMTD([SumByMeasure_PriceDivider], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MQT",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-1,YEAR)),
			        "MMT",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-1,YEAR)),
			        "MAT",CALCULATE([SumByMeasure_PriceDivider],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR),-1,YEAR)),
			        "Custom",CALCULATE([SumByMeasure_PriceDivider],All(Periods),Periods[Period]>=PYMinDate && Periods[Period]<=PYMaxDate)
			     ),BLANK()
			)
			```
		isHidden
		lineageTag: a0b3e30e-8cc2-4d84-81d2-ab2d86ea6d04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_Dyn_PP = CALCULATE([SumByMeasure_PriceDivider],Filter(Periods,Periods[PT]=2 && Periods[Year]=[Current_Year]))
		isHidden
		lineageTag: 3b2265b6-3382-40b1-bbb6-8d7ea8d0c53b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_AC =
			CALCULATE([Market_Sales_PriceDivider_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: 6da0406e-70bf-4a57-aa7d-3d1abac8d9c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_PY =
			CALCULATE([Market_Sales_PriceDivider_Dyn_PY],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		isHidden
		lineageTag: e43ce6f3-1306-4d99-9e69-c9e0b28758b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_Dyn_AC_All_Periods = [Market_Sales_PriceDivider_Dyn_AC]
		isHidden
		lineageTag: 8eacbc0e-a0b3-4779-a65b-08fc20018c05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SumByMeasure_PriceDivider_PY_AllPeriods = [SumByMeasure_PriceDivider_AC_AllPeriods]
		isHidden
		lineageTag: 497c8d6d-eb66-4955-b373-62b086743f15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_PriceDivider_Dyn_PY_All_Periods = [Market_Sales_PriceDivider_Dyn_PY]
		isHidden
		lineageTag: c2c72e16-9770-4906-9729-c7604ac1d68a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure rankx_1 =
			
			var id1=SELECTEDVALUE(Drugs[Market Org ID])
			var drugsTable=DISTINCT(SELECTCOLUMNS(Filter(ALLSELECTED(Drugs),Drugs[Market Org ID]=[SelfMO_ID]),"Market Org",Drugs[Market Org],"DRUGS_ID",Drugs[DRUGS_ID]))
			return if(id1<>[SelfMO_ID],blank(),
			     RANKX(drugsTable,CALCULATE([Distr_Sales_AC],(ALLEXCEPT(Drugs,Drugs[Market Org]))),,DESC,Dense)
			)
		formatString: 0
		isHidden
		lineageTag: 08d60de1-1256-4829-92e6-c9221780e0a8

	measure IsSelfMOItem =
			
			var selectedMO=SELECTEDVALUE(Drugs[Market Org ID])
			return if(selectedMO=[SelfMO_ID],1,0)
		formatString: 0
		isHidden
		lineageTag: 17a23a9b-7d63-4e85-baef-07b92fcbf4d8

	measure Build = "6"
		isHidden
		lineageTag: 2048358e-c644-4a4c-b828-2c40eb029b3d

	measure Is_Group_Not_Empty =
			
			var groupLevel1=SELECTEDVALUE(GroupLevel[LevelName])
			var currentGroup=SWITCH(groupLevel1,
			    "1",SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1]),
			    "2",SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2]),
			    "3",SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])
			)
			return if(ISBLANK(currentGroup),0,1)
		formatString: 0
		isHidden
		lineageTag: 0f66ef46-5db2-4873-842c-b030c98a0872

	measure Release = "0"
		isHidden
		lineageTag: c29528fa-4f71-4a48-a223-41fc79832a12

	measure Version_High = "1"
		isHidden
		lineageTag: ea868e6b-92dc-41cb-b6ac-941c06d16e58

	measure Version_Low = "7"
		isHidden
		lineageTag: 53275107-608a-445b-9485-e4436266b649

	measure Count_AC_AllPeriods = DISTINCTCOUNT(Drugs[DRUGS_ID])
		formatString: 0
		isHidden
		lineageTag: cd8a7dc1-30fd-4037-9b74-1e1c2901ef8f

	measure Export_SRO_Dyn_AC = if([IsExportPRTAllow],CALCULATE(max(Data[SRO]),FILTER(Periods,[PT]=0)),BLANK())
		isHidden
		lineageTag: 6cd1ec81-b427-463f-833d-10ab22e9e0e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Export_WSRO_Dyn_AC = if ([IsExportPRTAllow],CALCULATE(max(Data[SRO_W]),FILTER(Periods,[PT]=0)),BLANK())
		isHidden
		lineageTag: 11494d9e-c81d-402e-beba-2c591420b30d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Export_PRT_Dyn_AC = if ([IsExportPRTAllow],CALCULATE(max(Data[PENETRATION]),FILTER(Periods,[PT]=0)),BLANK())
		isHidden
		lineageTag: d7f8e61c-a237-4f06-a636-b58bc31759b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Export_WPRT_Dyn_AC = if ([IsExportPRTAllow],CALCULATE(max(Data[PENETRATION_W]),FILTER(Periods,[PT]=0)),BLANK())
		isHidden
		lineageTag: b4cafa97-6a18-421b-a8ff-db9790a88298

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IsExportPRTAllow =
			
			var isPeriodSelected=COUNTROWS(FILTER(ExportFields,ExportFields[ExportFieldName]="Period"))=1
			var isSKUSelected=COUNTROWS(FILTER(ExportFields,ExportFields[ExportFieldName]="SKU"))=1
			RETURN if(isPeriodSelected && isSKUSelected,TRUE(),FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isHidden
		lineageTag: cbcc6c30-3688-422b-a8dc-0dfcd3adb271

	measure Current_Data_Type_SM = var s="distr" return s
		isHidden
		lineageTag: 82d0d30b-dfa6-4b8a-8f7e-bd2e1c52ef57

	measure Current_Aggr_Type = ```
			
			var AggrType1=SELECTEDVALUE(Aggr[AGGR_TYPE])
			return if(AggrType1="Custom","sum of "&SELECTEDVALUE(SelectAggrLength[Value])&" days",AggrType1)
			
			```
		isHidden
		lineageTag: 23d055f6-ce25-450d-a071-2c4c95ada710

	measure SumByMeasure_AC = ```
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			return 
			SWITCH(AggrType,
			            "Daily",CALCULATE([SumByMeasure]),
			            "YTD",TOTALYTD([SumByMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([SumByMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			```
		formatString: 0
		isHidden
		lineageTag: dcd66f1d-9c53-4ea9-b3da-00aadf2b6441

	measure SumByMeasure_PY = ```
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			VAR PYMaxDate = LOOKUPVALUE(Periods[DatePY], Periods[Period], MAX(Periods[Period]))
			VAR PYMinDate = PYMaxDate - delta + 1 
			return SWITCH(AggrType,
			        "Daily",CALCULATE([SumByMeasure],ALL(Periods),TREATAS(VALUES(Periods[DatePY]),Periods[Period])),
			        "YTD",TOTALYTD([SumByMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MTD",TOTALMTD([SumByMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MQT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-1,YEAR)),
			        "MMT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-1,YEAR)),
			        "MAT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR),-1,YEAR)),
			        "Custom",CALCULATE([SumByMeasure],All(Periods),Periods[Period]>=PYMinDate && Periods[Period]<=PYMaxDate)
			     )
			
			```
		isHidden
		lineageTag: 735137db-d62d-4270-91cb-d3c6124bb56f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Sales_Dyn_PY_Total_Dim =
			SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			    "Corporation",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Corporation])),
			    "Market Org",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Market Org])),
			    "Brand",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Brand])),
			    "Brand+Market Org",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Brand+Market Org])),
			    "Brand+Corporation",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Brand+Corporation])),
			    "SKU",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Full medication name])),
			    "INN",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[INN])),
			    "Comp group L1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.1])),
			    "Comp group L2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.2])),
			    "Comp group L3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.3])),
			    "Comp group L4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.4])),
			    "Comp group L5",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Groups[PRODUCT_NAME_TREE.5])),
			    "Category",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[CategoryLongName])),
			    "Rx/OTC",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Rx/OTC])),
			    "ATC 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (1)])),
			    "ATC 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (2)])),
			    "ATC 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (3)])),
			    "ATC 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (4)])),
			    "ATC 5",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[ATC Code (5)])),
			    "EphMRA 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (1)])),
			    "EphMRA 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (2)])),
			    "EphMRA 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (3)])),
			    "EphMRA 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[EphMRA Code (4)])),
			    "NFC 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[NFC Code (1)])),
			    "NFC 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[NFC Code (2)])),
			    "NFC 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[NFC Code (3)])),
			    "Domestic/Foreign(maker)",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Domestic/Foreign(maker)])),
			    "Maker",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Maker])),
			    "Cosmetic 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(1)])),
			    "Cosmetic 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(2)])),
			    "Cosmetic 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(3)])),
			    "Cosmetic 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(4)])),
			    "Cosmetic 5",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Cosmetic Name(5)])),
			    "Bad 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[BAD Name(1)])),
			    "Bad 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[BAD Name(2)])),
			    "MC 1",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(1)])),
			    "MC 2",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(2)])),
			    "MC 3",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(3)])),
			    "MC 4",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[MC Name(4)])),
			    "Market status",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(Drugs[Market_Status])),
			    "Sales type",CALCULATE([Distr_Sales_Dyn_PY],REMOVEFILTERS(ECom[E-com]))
			
			)
		isHidden
		lineageTag: a503b0fa-c149-4e4c-82d3-238d30b2a9d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Years_Range =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var minYear=CALCULATE(min(Periods[Year]),filter(Periods,Periods[Period]>=SelectedDate - PeriodLength + 1))
			var maxYear=CALCULATE(max(Periods[Year]),filter(Periods,Periods[Period]<=SelectedDate))
			return if(minYear=maxYear,minYear,minYear&".."&maxYear)
		isHidden
		lineageTag: 985f2121-c84b-4eb4-b9ad-f19cae060684

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Measure
		isHidden
		lineageTag: d5ebf38e-2236-42f1-abf3-583f1fdc22e3

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Market_Price_Dyn_PY = DIVIDE([Distr_Sales_Dyn_PY], [Market_Sales_PriceDivider_PY], BLANK())
		isHidden
		lineageTag: 4f4e1409-6b95-411f-b1a9-114b14810122

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Price_GR_PY = DIVIDE([Market_Price_AC],[Market_Price_PY],BLANK())-1
		isHidden
		lineageTag: 8d80cfa4-9419-4259-a876-a75e1a17c1f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Price_GR_PP = DIVIDE([Market_Price_AC],[Market_Price_PP],blank())-1
		isHidden
		lineageTag: d90bc1cf-3459-4120-8b1a-03a67b41493a

	measure TOTAL = ```
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR AggrType = SELECTEDVALUE(Aggr[AGGR_TYPE])
			VAR delta = SELECTEDVALUE(SelectAggrLength[Value])
			
			RETURN
			    SWITCH(
			        AggrType,
			        "Daily", 
			            CALCULATE(
			                [SumByMeasure],
			                Periods[Period] = SelectedDate,
			                REMOVEFILTERS(Periods)
			            ),
			        "YTD", 
			            CALCULATE(
			                TOTALYTD([SumByMeasure], Periods[Period], ALL(Periods)),
			                Periods[Period] <= SelectedDate,
			                REMOVEFILTERS(Periods)
			            ),
			        "MTD", 
			            CALCULATE(
			                TOTALMTD([SumByMeasure], Periods[Period], ALL(Periods)),
			                Periods[Period] <= SelectedDate,
			                REMOVEFILTERS(Periods)
			            ),
			        "MQT", 
			            CALCULATE(
			                [SumByMeasure], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -90, DAY)
			            ),
			        "MMT", 
			            CALCULATE(
			                [SumByMeasure], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -30, DAY)
			            ),
			        "MAT", 
			            CALCULATE(
			                [SumByMeasure], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -1, YEAR)
			            ),
			        "Custom", 
			            CALCULATE(
			                [SumByMeasure], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -1 * delta, DAY)
			            ),
			        BLANK()
			    )
			
			```
		isHidden
		lineageTag: 9efcef57-748b-48fd-a8f7-80cafb8759cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByVol_TOTAL =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([TOTAL]),1000000,
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),[TOTAL],,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),[TOTAL],,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),[TOTAL],,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),[TOTAL],,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),[TOTAL],,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),[TOTAL],,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),[TOTAL],,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),[TOTAL],,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),[TOTAL],,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),[TOTAL],,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),[TOTAL],,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),[TOTAL],,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),[TOTAL],,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),[TOTAL],,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),[TOTAL],,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),[TOTAL],,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),[TOTAL],,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),[TOTAL],,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),[TOTAL],,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),[TOTAL],,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),[TOTAL],,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),[TOTAL],,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),[TOTAL],,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),[TOTAL],,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),[TOTAL],,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),[TOTAL],,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),[TOTAL],,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),[TOTAL],,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),[TOTAL],,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),[TOTAL],,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),[TOTAL],,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),[TOTAL],,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),[TOTAL],,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),[TOTAL],,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),[TOTAL],,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),[TOTAL],,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),[TOTAL],,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),[TOTAL],,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),[TOTAL],,Desc,Dense),
			        "Region Level 1",rankx(ALLSELECTED(Areas[LEVEL_1]),[TOTAL],,Desc,Dense),
			        "Region Level 2",rankx(ALLSELECTED(Areas[LEVEL_2]),[TOTAL],,Desc,Dense),
			        "Region Level 3",rankx(ALLSELECTED(Areas[LEVEL_3]),[TOTAL],,Desc,Dense),
			        "Region Level 4",rankx(ALLSELECTED(Areas[LEVEL_4]),[TOTAL],,Desc,Dense),
			        "Area",rankx(ALLSELECTED(Areas[AREA_NAME]),[TOTAL],,Desc,Dense),
			        "Chain name",rankx(ALLSELECTED(Areas[CHAIN_NAME]),[TOTAL],,Desc,Dense),
			        "Legal entity",rankx(ALLSELECTED(Areas[ORG_NAME]),[TOTAL],,Desc,Dense),
			        "Pharmacy name",rankx(ALLSELECTED(Areas[CLIENT_NAME]),[TOTAL],,Desc,Dense),
			        "Pharmacy address",rankx(ALLSELECTED(Areas[ADDRESS]),[TOTAL],,Desc,Dense),
			        "Pharmacy type",rankx(ALLSELECTED(Areas[CLIENT_TYPE_ORG]),[TOTAL],,Desc,Dense),
			        "Pharmacy city",rankx(ALLSELECTED(Areas[CITY]),[TOTAL],,Desc,Dense)
			    )
			)
		formatString: 0
		isHidden
		lineageTag: 2d9ef1b6-d4fe-4abc-87e2-b0314273db52

	measure Market_Sales_Dyn_PY_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_TOTAL]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,[Distr_Sales_Dyn_PY],BLANK())
		isHidden
		lineageTag: 03e89e0d-2543-4bb6-a811-8cea84c72505

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByVol_TOTAL_TopN_Self = ```
			
			VAR SelfMO = [SelfMO_ID]  -- Своя маркетуюча організація (не з SELECTEDVALUE!)
			VAR CurrentMO = SELECTEDVALUE(Drugs[Market Org ID])  -- Маркетуюча в поточному рядку таблиці
			VAR DisabledSelfMO=SELECTEDVALUE(SelectSelfMO[Disabled])
			RETURN 
			IF(
			    DisabledSelfMO = 1 || SelfMO = BLANK() || SelfMO <> CurrentMO,  -- Якщо зараз не "своя" маркетуюча, повертаємо BLANK()
			    BLANK(),
			    IF(
			        SWITCH(
			            SELECTEDVALUE('Dimensions'[DimName]),
			            "SKU", RANKX(
			                FILTER(ALLSELECTED(Drugs), Drugs[Market Org ID] = SelfMO), 
			                [TOTAL], 
			                , DESC, Dense
			            ),
			            "Brand", RANKX(
			                FILTER(ALLSELECTED(Drugs), Drugs[Market Org ID] = SelfMO), 
			                [TOTAL], 
			                , DESC, Dense
			            ),
			            "Market Org", RANKX(
			                FILTER(ALLSELECTED(Drugs), Drugs[Market Org ID] = SelfMO), 
			                [TOTAL], 
			                , DESC, Dense
			            ),
			            "Brand+Market Org", RANKX(
			                FILTER(ALLSELECTED(Drugs), Drugs[Market Org ID] = SelfMO), 
			                [TOTAL], 
			                , DESC, Dense
			            ),
			            "Corporation", RANKX(
			                FILTER(ALLSELECTED(Drugs), Drugs[Market Org ID] = SelfMO), 
			                [TOTAL], 
			                , DESC, Dense
			            ),
			            BLANK()
			        ) = 1,
			        1,
			        BLANK()
			    )
			)
			
			// RankByVol_TOTAL_TopN_Self = 
			// var id1=SELECTEDVALUE(Drugs[Market Org ID])
			// var drugsTable=Filter(ALLSELECTED(Drugs),Drugs[Market Org ID]=[SelfMO_ID])
			// return if(id1<>[SelfMO_ID],blank(),
			//     if(SWITCH(SELECTEDVALUE('Dimensions'[DimName]),
			//         "SKU",RANKX(drugsTable,CALCULATE([TOTAL],ALLEXCEPT(Drugs,Drugs[Full medication name])),,DESC,Dense),
			//         "Brand",RANKX(drugsTable,CALCULATE([TOTAL],ALLEXCEPT(Drugs,Drugs[Brand])),,DESC,Dense),
			//         "Market Org",RANKX(drugsTable,CALCULATE([TOTAL],ALLEXCEPT(Drugs,Drugs[Market Org])),,DESC,Dense),
			//         "Brand+Market Org",RANKX(drugsTable,CALCULATE([TOTAL],ALLEXCEPT(Drugs,Drugs[Brand+Market Org])),,DESC,Dense),
			//         "Corporation",RANKX(drugsTable,CALCULATE([TOTAL],ALLEXCEPT(Drugs,Drugs[Corporation])),,DESC,Dense),
			//         BLANK()
			//     )=1,1,BLANK())
			// )
			```
		formatString: 0
		isHidden
		lineageTag: db0f3fa0-28d4-4451-b2ca-289dd8ab1b10

	measure PriceDDD_AC_AllPeriods = ([SumByDDD_AC_AllPeriods]/[SumByPCS_AC_AllPeriods])
		isHidden
		lineageTag: e20d44a6-0c48-46c8-ae82-1ddd92616f37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceTABS_AC_AllPeriods = ([SumByTABS_AC_AllPeriods]/[SumByPCS_AC_AllPeriods])
		isHidden
		lineageTag: edff8f85-11be-4dcf-963f-99d8fcd33f31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_GR_Dyn_AC_Ranked_Paginated_TopN_Self =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RankByVol_AllPeriods]
			var currentRankSelf=[RankByVol_AllPeriods_TopN_Self]
			return if((currentRank>=beginTop && currentRank<=endTop)||currentRankSelf=1,
			    if(
			        not ISBLANK([Distr_Sales_Dyn_AC_All_Periods]) && [Market_Sales_Dyn_PY_All_Periods]<>0,
			        (([Distr_Sales_Dyn_AC_All_Periods]/[Market_Sales_Dyn_PY_All_Periods])-1),
			        BLANK()
			    ),
			    BLANK()
			)
		isHidden
		lineageTag: 8607a919-f15a-4370-becf-b8442df1c1fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VisitsFactMeasure = sum(VisitsFact[VISITS_COUNT])
		formatString: 0
		lineageTag: 03d304e7-6c3b-463b-9a24-4b6e1a6031ec

	measure Visits_Dyn_AC =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([VisitsFactMeasure]),
			            "YTD",TOTALYTD([VisitsFactMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([VisitsFactMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([VisitsFactMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([VisitsFactMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([VisitsFactMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([VisitsFactMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		formatString: 0
		lineageTag: 30983a4c-5011-4ee6-90f8-9e24c108e9cb

	measure Visits_Dyn_PY = ```
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			VAR PYMaxDate = LOOKUPVALUE(Periods[DatePY], Periods[Period], MAX(Periods[Period]))
			VAR PYMinDate = PYMaxDate - delta + 1 
			return if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			        "Daily",CALCULATE([VisitsFactMeasure],ALL(Periods),TREATAS(VALUES(Periods[DatePY]),Periods[Period])),
			        "YTD",TOTALYTD([VisitsFactMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MTD",TOTALMTD([VisitsFactMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MQT",CALCULATE([VisitsFactMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-1,YEAR)),
			        "MMT",CALCULATE([VisitsFactMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-1,YEAR)),
			        "MAT",CALCULATE([VisitsFactMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR),-1,YEAR)),
			        "Custom",CALCULATE([VisitsFactMeasure],All(Periods),Periods[Period]>=PYMinDate && Periods[Period]<=PYMaxDate)
			     ),BLANK()
			)
			```
		formatString: 0
		lineageTag: e81037ac-c0e4-43a7-a354-dae4b957f7f0

	measure Visits_AC =
			CALCULATE([Visits_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		formatString: 0
		lineageTag: 260c9a70-f8cb-4975-b2a7-603ce0cc8c66

	measure Visits_PY =
			CALCULATE([Visits_Dyn_PY],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		formatString: 0
		lineageTag: 7452fd22-7588-4e4d-b027-98ae866a4460

	measure Visits_AC_Ranked =
			
			var currentRank=[RankByVisits]
			return if([IsTotalByDim]||currentRank<=[TOP],[Visits_AC],BLANK())
		lineageTag: 9651c7f8-646a-44e7-abb9-d1c7b308d4e7

	measure RankByVisits =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([Visits_AC]),1000000,
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),ROUND([Visits_AC],4),,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),ROUND([Visits_AC],4),,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Comp Group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),ROUND([Visits_AC],4),,DESC, Dense)),
			        "Comp Group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),ROUND([Visits_AC],4),,DESC, Dense)),
			        "Comp Group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),ROUND([Visits_AC],4),,DESC, Dense)),
			        "Comp Group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),ROUND([Visits_AC],4),,DESC, Dense)),
			        "Comp Group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),ROUND([Visits_AC],4),,DESC, Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),ROUND([Visits_AC],4),,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),ROUND([Visits_AC],4),,Desc,Dense),
			        "Region Level 1",rankx(ALLSELECTED(Areas[LEVEL_1]),[Visits_AC],,Desc,Dense),
			        "Region Level 2",rankx(ALLSELECTED(Areas[LEVEL_2]),[Visits_AC],,Desc,Dense),
			        "Region Level 3",rankx(ALLSELECTED(Areas[LEVEL_3]),[Visits_AC],,Desc,Dense),
			        "Region Level 4",rankx(ALLSELECTED(Areas[LEVEL_4]),[Visits_AC],,Desc,Dense),
			        "Area",rankx(ALLSELECTED(Areas[AREA_NAME]),[Visits_AC],,Desc,Dense),
			        "Chain name",rankx(ALLSELECTED(Areas[CHAIN_NAME]),[Visits_AC],,Desc,Dense),
			        "Legal entity",rankx(ALLSELECTED(Areas[ORG_NAME]),[Visits_AC],,Desc,Dense),
			        "Pharmacy name",rankx(ALLSELECTED(Areas[CLIENT_NAME]),[Visits_AC],,Desc,Dense),
			        "Pharmacy address",rankx(ALLSELECTED(Areas[ADDRESS]),[Visits_AC],,Desc,Dense),
			        "Pharmacy type",rankx(ALLSELECTED(Areas[CLIENT_TYPE_ORG]),[Visits_AC],,Desc,Dense),
			        "Pharmacy city",rankx(ALLSELECTED(Areas[CITY]),[Visits_AC],,Desc,Dense)
			    )
			)
		lineageTag: b11d909b-35ee-4b71-b1ce-c75062a7f1be

	measure IsTotalByDim = ```
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return SWITCH(SelectDim,
			        "Corporation",ISINSCOPE(Drugs[Corporation])=FALSE,
			        "Market Org",ISINSCOPE(Drugs[Market Org])=FALSE,
			        "Brand",ISINSCOPE(Drugs[Brand])=FALSE,
			        "Brand+Market Org",ISINSCOPE(Drugs[Brand+Market Org])=FALSE,
			        "Brand+Corporation",ISINSCOPE(Drugs[Brand+Corporation])=FALSE,
			        "SKU",ISINSCOPE(Drugs[Full medication name])=FALSE,
			        "INN",ISINSCOPE(Drugs[INN])=FALSE,
			        "Comp Group L1",ISINSCOPE(Groups[PRODUCT_NAME_TREE.1])=FALSE,
			        "Comp Group L2",ISINSCOPE(Groups[PRODUCT_NAME_TREE.2])=FALSE,
			        "Comp Group L3",ISINSCOPE(Groups[PRODUCT_NAME_TREE.3])=FALSE,
			        "Comp Group L4",ISINSCOPE(Groups[PRODUCT_NAME_TREE.4])=FALSE,
			        "Comp Group L5",ISINSCOPE(Groups[PRODUCT_NAME_TREE.5])=FALSE,
			        "Category",ISINSCOPE(Drugs[CategoryLongName])=FALSE,
			        "Rx/OTC",ISINSCOPE(Drugs[Rx/OTC])=FALSE,
			        "ATC 1",ISINSCOPE(Drugs[ATC Code (1)])=FALSE,
			        "ATC 2",ISINSCOPE(Drugs[ATC Code (2)])=FALSE,
			        "ATC 3",ISINSCOPE(Drugs[ATC Code (3)])=FALSE,
			        "ATC 4",ISINSCOPE(Drugs[ATC Code (4)])=FALSE,
			        "ATC 5",ISINSCOPE(Drugs[ATC Code (5)])=FALSE,
			        "EphMRA 1",ISINSCOPE(Drugs[EphMRA Code (1)])=FALSE,
			        "EphMRA 2",ISINSCOPE(Drugs[EphMRA Code (2)])=FALSE,
			        "EphMRA 3",ISINSCOPE(Drugs[EphMRA Code (3)])=FALSE,
			        "EphMRA 4",ISINSCOPE(Drugs[EphMRA Code (4)])=FALSE,
			        "NFC 1",ISINSCOPE(Drugs[NFC Code (1)])=FALSE,
			        "NFC 2",ISINSCOPE(Drugs[NFC Code (2)])=FALSE,
			        "NFC 3",ISINSCOPE(Drugs[NFC Code (3)])=FALSE,
			        "Domestic/Foreign(maker)",ISINSCOPE(Drugs[Domestic/Foreign(maker)])=FALSE,
			        "Maker",ISINSCOPE(Drugs[Maker])=FALSE,
			        "Cosmetic 1",ISINSCOPE(Drugs[Cosmetic Name(1)])=FALSE,
			        "Cosmetic 2",ISINSCOPE(Drugs[Cosmetic Name(2)])=FALSE,
			        "Cosmetic 3",ISINSCOPE(Drugs[Cosmetic Name(3)])=FALSE,
			        "Cosmetic 4",ISINSCOPE(Drugs[Cosmetic Name(4)])=FALSE,
			        "Cosmetic 5",ISINSCOPE(Drugs[Cosmetic Name(5)])=FALSE,
			        "Bad 1",ISINSCOPE(Drugs[BAD Name(1)])=FALSE,
			        "Bad 2",ISINSCOPE(Drugs[BAD Name(2)])=FALSE,
			        "MC 1",ISINSCOPE(Drugs[MC Name(1)])=FALSE,
			        "MC 2",ISINSCOPE(Drugs[MC Name(2)])=FALSE,
			        "MC 3",ISINSCOPE(Drugs[MC Name(3)])=FALSE,
			        "MC 4",ISINSCOPE(Drugs[MC Name(4)])=FALSE,
			        "Market status",ISINSCOPE(Drugs[Market_Status])=FALSE,
			        "Sales type",ISINSCOPE(ECom[E-com])=FALSE()
				
			    )
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 01e2f745-13ae-4d5a-9b82-2004c0b85f5a

	measure Visits_PY_Ranked =
			
			var currentRank=[RankByVisits]
			return if([IsTotalByDim]||currentRank<=[TOP],[Visits_PY],BLANK())
		formatString: 0
		lineageTag: 92b78421-520f-4b12-83a5-9772e0f76e0d

	measure Distr_Dyn_AC =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([DistrSumMeasure]),
			            "YTD",TOTALYTD([DistrSumMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([DistrSumMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([DistrSumMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([DistrSumMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([DistrSumMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([DistrSumMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		lineageTag: 43286fb2-6da2-4a92-83a4-7ccf3694c8a9

	measure DistrPlanByMeasure =
			
			var measureType=SELECTEDVALUE(SelectMeasures[MeasureName])
			var curType=SELECTEDVALUE(_CURRENCY_[_CURRENCY_])
			return SWITCH(TRUE(),
			        measureType="pcs",sum(DataPlan[Q]),
			        measureType in {curType,curType&"/tabs",curType&"/DDD"},sum(DataPlan[V]),
			        measureType in {"USD","USD/tabs","USD/DDD"},sum(DataPlan[V_USD]),
			        measureType in {"EUR","EUR/tabs","EUR/DDD"},sum(DataPlan[V_EUR]),
			        measureType="tabs",sum(DataPlan[TABS]),
			        measureType="DDD",sum(DataPlan[DDD])
			    )
		lineageTag: 04d516fc-5d7a-4354-b736-bd4e83d3e926

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Dyn_PL =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([DistrPlanByMeasure]),
			            "YTD",TOTALYTD([DistrPlanByMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([DistrPlanByMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		lineageTag: 95d20d73-648f-44ab-b4dc-62cb1458f519

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PL =
			CALCULATE([Distr_Sales_Dyn_PL],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: 382c7954-0c5d-43b1-a3e1-04de76fcc783

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PL_Ranked = if([RankByVol]<=[TOP],[Distr_Sales_PL],BLANK())
		lineageTag: 7b74c02e-f8fe-4497-bbdf-fc1bd39ec3da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Dyn_PE = Divide([Distr_Sales_Dyn_AC],[Distr_Sales_Dyn_PL],BLANK())
		lineageTag: ddfdccc8-de5b-45ee-a297-c23c9ff0a84f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PE =
			CALCULATE([Distr_Sales_Dyn_PE],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: fcb24ac4-d757-4b58-b16f-e73a900c3666

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PE_Ranked = if([RankByVol]<=[TOP],[Distr_Sales_PE],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ba96e9fa-1da2-433b-baba-080c52a4af40

	measure Visits_Rank_AC_Ranked =
			
			var currentRank=[RankByVisits]
			return if([IsTotalByDim]||currentRank<=[TOP],currentRank,BLANK())
		formatString: 0
		lineageTag: 0cec6f3d-64c4-48d8-aa59-83d6eb3b073f

	measure Distr_Sales_Month_AC =
			CALCULATE([Distr_Sales_Dyn_AC_WO_Window],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			)
		lineageTag: e8a42391-0d66-4c3b-b2ae-9638acbc5347

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Dyn_AC_WO_Window =
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			return SWITCH(AggrType,
			        "Daily",CALCULATE([SumByMeasure]),
			        "YTD",TOTALYTD([SumByMeasure],Periods[Period],All(Periods)),
			        "MTD",TOTALMTD([SumByMeasure],Periods[Period],All(Periods)),
			        "MQT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			        "MMT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			        "MAT",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			        "Custom",CALCULATE([SumByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			)
		lineageTag: 74dd7b3b-a555-4a9d-86d6-059e5f03916e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Month_PY =
			CALCULATE([Distr_Sales_Dyn_PY_WO_Window],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			)
		lineageTag: 783bbb40-b94e-43b7-940a-ddbe2a9183aa

	measure 'Measure 2'
		lineageTag: 2ba87e7a-f517-4039-a47a-058c169a3974

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Distr_Sales_Dyn_PY_WO_Window = ```
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			VAR PYMaxDate = LOOKUPVALUE(Periods[DatePY], Periods[Period], MAX(Periods[Period]))
			VAR PYMinDate = PYMaxDate - delta + 1 
			return  SWITCH(AggrType,
			        "Daily",CALCULATE([SumByMeasure],ALL(Periods),TREATAS(VALUES(Periods[DatePY]),Periods[Period])),
			        "YTD",TOTALYTD([SumByMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MTD",TOTALMTD([SumByMeasure], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MQT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-1,YEAR)),
			        "MMT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-1,YEAR)),
			        "MAT",CALCULATE([SumByMeasure],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR),-1,YEAR)),
			        "Custom",CALCULATE([SumByMeasure],All(Periods),Periods[Period]>=PYMinDate && Periods[Period]<=PYMaxDate)
			     )
			
			```
		lineageTag: 659fda7e-a1b7-4977-baf7-1fc027356858

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_GR_Month_PY = if(ISBLANK([Distr_Sales_Month_PY]),BLANK(),DIVIDE([Distr_Sales_Month_AC],[Distr_Sales_Month_PY],BLANK())-1)
		lineageTag: efb2688d-42f7-44a6-9222-760b8065c621

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Promo_Month_AC =
			CALCULATE([Promo_Dyn_AC_WO_Window],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			)
		lineageTag: 0265eba0-eef6-4781-bf2c-1ee8ea6f18e4

	measure Promo_Dyn_AC_WO_Window =
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			return SWITCH(AggrType,
			        "Daily",CALCULATE([Promo]),
			        "YTD",TOTALYTD([Promo],Periods[Period],All(Periods)),
			        "MTD",TOTALMTD([Promo],Periods[Period],All(Periods)),
			        "MQT",CALCULATE([Promo],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			        "MMT",CALCULATE([Promo],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			        "MAT",CALCULATE([Promo],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			        "Custom",CALCULATE([Promo],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			)
		lineageTag: ae83f34d-410e-4b20-ad2f-8ffc9e0796ab

	measure Promo = sum(VisitsFact[VISITS_COUNT])
		formatString: 0
		lineageTag: 4a130bad-7a8e-466f-aded-907e999dc0b0

	measure Promo_Month_PY =
			CALCULATE([Promo_Dyn_PY_WO_Window],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			)
		lineageTag: 41a94d63-9b53-40b4-8078-53a5696f8122

	measure Promo_Dyn_PY_WO_Window = ```
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			VAR PYMaxDate = LOOKUPVALUE(Periods[DatePY], Periods[Period], MAX(Periods[Period]))
			VAR PYMinDate = PYMaxDate - delta + 1 
			return  SWITCH(AggrType,
			        "Daily",CALCULATE([Promo],ALL(Periods),TREATAS(VALUES(Periods[DatePY]),Periods[Period])),
			        "YTD",TOTALYTD([Promo], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MTD",TOTALMTD([Promo], DATEADD(Periods[Period], -1, YEAR), ALL(Periods)),
			        "MQT",CALCULATE([Promo],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY),-1,YEAR)),
			        "MMT",CALCULATE([Promo],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY),-1,YEAR)),
			        "MAT",CALCULATE([Promo],All(Periods),DATEADD(DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR),-1,YEAR)),
			        "Custom",CALCULATE([Promo],All(Periods),Periods[Period]>=PYMinDate && Periods[Period]<=PYMaxDate)
			     )
			
			```
		formatString: 0
		lineageTag: 444283d1-6f47-47a7-9543-231c1c370d20

	measure Promo_GR_Month_PY = if(ISBLANK([Promo_Dyn_PY_WO_Window]),BLANK(),DIVIDE([Promo_Dyn_AC_WO_Window],[Promo_Dyn_PY_WO_Window],BLANK())-1)
		lineageTag: 243ca8b1-12cf-4be3-a837-eacfcd9e14c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VisitsPlanByMeasure = sum(VisitsPlan[VISITS_COUNT])
		lineageTag: a2b01f5b-b42b-4622-95ed-3a4dd5c5b786

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_Dyn_PL =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([VisitsPlanByMeasure]),
			            "YTD",TOTALYTD([VisitsPlanByMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([VisitsPlanByMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		lineageTag: 33e03fc7-1d68-4101-91bd-ba81c0f44c0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PL =
			CALCULATE([Visits_Dyn_PL],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: 4870b209-dae8-4564-b7c4-0bede9cb33cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PL_Ranked = if([RankByVisits]<=[TOP],[Visits_PL],BLANK())
		lineageTag: a7cf7290-36fa-444c-82f1-820633e12035

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_Dyn_PE = Divide([Visits_Dyn_AC],[Visits_Dyn_PL],BLANK())
		lineageTag: 59ef2963-7ec4-448c-801a-a0971fd624d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PE =
			CALCULATE([Visits_Dyn_PE],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: 989486c8-e907-474c-af73-0b5b7e71487d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PE_Ranked = if([RankByVisits]<=[TOP],[Visits_PE],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0f6f1ef4-f6e4-46fd-b247-f3dc1d8d7db9

	measure Distr_Sales_Month_PL =
			
			CALCULATE(
			CALCULATE([Distr_Sales_Dyn_PL_WO_Window],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			),Aggr[AGGR_TYPE]="MTD")
		lineageTag: bedc4656-604f-4e54-aa39-a96f622b5265

	measure Distr_Sales_Dyn_PL_WO_Window =
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			return SWITCH(AggrType,
			        "Daily",CALCULATE([DistrPlanByMeasure]),
			        "YTD",TOTALYTD([DistrPlanByMeasure],Periods[Period],All(Periods)),
			        "MTD",TOTALMTD([DistrPlanByMeasure],Periods[Period],All(Periods)),
			        "MQT",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			        "MMT",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			        "MAT",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			        "Custom",CALCULATE([DistrPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			)
		lineageTag: ca79a202-1962-4b5f-8a73-4918d602deac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Month_PE = DIVIDE([Distr_Sales_Month_AC],[Distr_Sales_Month_PL],BLANK())
		lineageTag: 2297d338-8b22-4912-bb99-ec5cb59d401b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_Month_dPL = ([Distr_Sales_Month_AC]-[Distr_Sales_Month_PL])
		lineageTag: 7e130d1c-7c34-4692-a06a-1c49eb5478a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Promo_Month_dPL = ([Promo_Month_AC]-[Promo_Month_PL])
		lineageTag: 0494cc53-e6f9-4085-a6e6-31f6010e9029

	measure Promo_Month_PL =
			
			CALCULATE(
			CALCULATE([Promo_Dyn_PL_WO_Window],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			),Aggr[AGGR_TYPE]="MTD")
		formatString: 0
		lineageTag: b3a91af1-1a58-4685-b7d5-6b1b62660ed1

	measure Promo_Dyn_PL_WO_Window =
			
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			return SWITCH(AggrType,
			        "Daily",CALCULATE([VisitsPlanByMeasure]),
			        "YTD",TOTALYTD([VisitsPlanByMeasure],Periods[Period],All(Periods)),
			        "MTD",TOTALMTD([VisitsPlanByMeasure],Periods[Period],All(Periods)),
			        "MQT",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			        "MMT",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			        "MAT",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			        "Custom",CALCULATE([VisitsPlanByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			)
		lineageTag: c2432759-4bd3-4d19-9264-40e548fc967d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Promo_Month_PE = DIVIDE([Promo_Month_AC],[Promo_Month_PL],BLANK())
		lineageTag: bf243301-f9cc-473b-908d-ba381a847f16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Stock_AC =
			CALCULATE([Distr_Stock_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		formatString: 0
		lineageTag: a3e2e941-a43b-4911-9923-636e7a4b83d1

	measure Distr_Stock_Dyn_AC =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period],MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			var AggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var delta=SELECTEDVALUE(SelectAggrLength[Value])
			var CDate=SELECTEDVALUE(Periods[Period])
			RETURN if(CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(AggrType,
			            "Daily",CALCULATE([SumStockByMeasure]),
			            "YTD",TOTALYTD([SumStockByMeasure],Periods[Period],All(Periods)),
			            "MTD",TOTALMTD([SumStockByMeasure],Periods[Period],All(Periods)),
			            "MQT",CALCULATE([SumStockByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-90,DAY)),
			            "MMT",CALCULATE([SumStockByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-30,DAY)),
			            "MAT",CALCULATE([SumStockByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1,YEAR)),
			            "Custom",CALCULATE([SumStockByMeasure],All(Periods),DATESINPERIOD(Periods[Period],LASTDATE(Periods[Period]),-1*delta,DAY))
			    )
			    ,BLANK()
			)
		lineageTag: 172772cc-1b0c-4cf3-ab02-4c88e35ba3a2

	measure SumStockByMeasure =
			
			var measureType=SELECTEDVALUE(SelectMeasures[MeasureName])
			var curType=SELECTEDVALUE(_CURRENCY_[_CURRENCY_])
			return SWITCH(TRUE(),
			        measureType="pcs",sum(DataStock[PCS]
			    ))
		lineageTag: 90d882fd-f0de-4db9-b747-f39d5e534178

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Stock_AC_Ranked =
			
			var currentRank=[RankByStock]
			return if([IsTotalByDim]||currentRank<=[TOP],[Distr_Stock_AC],BLANK())
		lineageTag: a82fd23a-2b6f-4fe0-9c18-adcdb2b136af

	measure RankByStock =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([Distr_Stock_AC]),1000000,
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Comp Group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),ROUND([Distr_Stock_AC],4),,DESC, Dense)),
			        "Comp Group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),ROUND([Distr_Stock_AC],4),,DESC, Dense)),
			        "Comp Group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),ROUND([Distr_Stock_AC],4),,DESC, Dense)),
			        "Comp Group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),ROUND([Distr_Stock_AC],4),,DESC, Dense)),
			        "Comp Group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),ROUND([Distr_Stock_AC],4),,DESC, Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),ROUND([Distr_Stock_AC],4),,Desc,Dense),
			         "Region Level 1",rankx(ALLSELECTED(Areas[LEVEL_1]),[Distr_Stock_AC],,Desc,Dense),
			        "Region Level 2",rankx(ALLSELECTED(Areas[LEVEL_2]),[Distr_Stock_AC],,Desc,Dense),
			        "Region Level 3",rankx(ALLSELECTED(Areas[LEVEL_3]),[Distr_Stock_AC],,Desc,Dense),
			        "Region Level 4",rankx(ALLSELECTED(Areas[LEVEL_4]),[Distr_Stock_AC],,Desc,Dense),
			        "Area",rankx(ALLSELECTED(Areas[AREA_NAME]),[Distr_Stock_AC],,Desc,Dense),
			        "Chain name",rankx(ALLSELECTED(Areas[CHAIN_NAME]),[Distr_Stock_AC],,Desc,Dense),
			        "Legal entity",rankx(ALLSELECTED(Areas[ORG_NAME]),[Distr_Stock_AC],,Desc,Dense),
			        "Pharmacy name",rankx(ALLSELECTED(Areas[CLIENT_NAME]),[Distr_Stock_AC],,Desc,Dense),
			        "Pharmacy address",rankx(ALLSELECTED(Areas[ADDRESS]),[Distr_Stock_AC],,Desc,Dense),
			        "Pharmacy type",rankx(ALLSELECTED(Areas[CLIENT_TYPE_ORG]),[Distr_Stock_AC],,Desc,Dense),
			        "Pharmacy city",rankx(ALLSELECTED(Areas[CITY]),[Distr_Stock_AC],,Desc,Dense)
			    )
			)
		formatString: 0
		lineageTag: c7f386d1-0c61-45cd-9fe5-ed4389ab436e

	measure Distr_Stock_Rank_AC_Ranked =
			
			var currentRank=[RankByStock]
			return if([IsTotalByDim]||currentRank<=[TOP],currentRank,BLANK())
		formatString: 0
		lineageTag: 67eb58a9-a2dd-4287-be72-6498ed31f6c1

	measure Distr_Sales_Month_AC_Periods_Count = ```
			
			    COUNTROWS(Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[PeriodMonth] in values(SinglePeriod[PeriodMonth]),
			            Periods[PeriodMonth]=max(SinglePeriod[PeriodMonth]))
			        )
			    )
			)
			```
		formatString: 0
		lineageTag: 007bd64b-8074-4df1-9bde-befcd4328e84

	measure Distr_Sales_Month_AC_Current_Period = DAY(max(SinglePeriod[Period]))
		formatString: 0
		lineageTag: 8e720eb8-fd29-477c-8cb3-4b2a356f86b8

	measure Distr_Sales_Month_FC = divide([Distr_Sales_Month_AC],[Distr_Sales_Month_AC_Current_Period])*[Distr_Sales_Month_AC_Periods_Count]
		lineageTag: ec344b16-4ec5-442f-ad58-d88eecd95d14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PE_Month_FC = divide([Distr_Sales_Month_FC],[Distr_Sales_Month_PL],BLANK())
		lineageTag: 938c499f-9839-48b1-a788-558a9bb482cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_AC_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales AC"),[Distr_Sales_AC],BLANK())
		lineageTag: 81c9add1-9714-4761-863c-07e56dd77fa9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_dPY_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales ΔPY"),[Distr_Sales_dPY],BLANK())
		lineageTag: 0fcb83d2-12c5-4461-aa9a-e0dbf56789d3

	measure Distr_Sales_dPY = ([Distr_Sales_AC]-[Distr_Sales_PY])
		lineageTag: 114a5296-38b6-41c6-80cf-d977ba6fc1b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_GR_PY =
			
			var ac=[Distr_Sales_AC]
			var py=[Distr_Sales_PY]
			return if(isblank(ac)||ISBLANK(py),blank(),DIVIDE(ac,py,0)-1)
		lineageTag: c51a1ffa-3881-4939-840d-7cf07b2c2750

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_GR_PY_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales ΔPY%"),[Distr_GR_PY],BLANK())
		lineageTag: ad22a1ac-66ee-4602-a34c-16d8fdcf9273

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PL_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales PL"),[Distr_Sales_PL],BLANK())
		lineageTag: 69a3a9c1-357c-4739-817b-c78b950d6017

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PE_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales PE%"),[Distr_Sales_PE],BLANK())
		lineageTag: f80cb01e-065d-41ce-af03-767d93761e62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_AC_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo AC"),[Visits_AC],BLANK())
		formatString: 0
		lineageTag: 7144eeaf-818d-435b-a8d8-6394052d82f9

	measure Visits_PL_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo PL"),[Visits_PL],BLANK())
		lineageTag: 7412d21f-25bc-4761-b6ae-4f1ba9e0a9a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PE_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo PE%"),[Visits_PE],BLANK())
		lineageTag: ebaa84a1-74d2-49a6-b436-2a422f631ccd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_MS_AC_In_Areas =
			
			var lev=SELECTEDVALUE(RegionLevel[RegionLevelName])
			return switch(lev,
			    "Level 1",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_1]))),
			    "Level 2",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_2]))),
			    "Level 3",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_3]))),
			    "Level 4",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_4])))
			)
		lineageTag: f9eb2e27-f2f9-40e9-b48b-e44d861990c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_MS_AC_In_Areas_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr TS%"),[Distr_MS_AC_In_Areas],BLANK())
		lineageTag: e6cb9aad-6edf-4e81-a30b-37d6243f49c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_AC_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_AC],BLANK())
		lineageTag: 8cf8d2d9-2e38-47c5-88a6-f94ddd82e151

	measure RegionRankByVol = ```
			
			var lev=SELECTEDVALUE(RegionLevel[RegionLevelName])
			return if(ISBLANK([Distr_Sales_AC]),BLANK(),
			    switch(lev,
			        "Level 1",rankx(ALLSELECTED(Areas[LEVEL_1]),[Distr_Sales_AC],,DESC,Dense),
			        "Level 2",rankx(ALLSELECTED(Areas[LEVEL_2]),[Distr_Sales_AC],,DESC,Dense),
			        "Level 3",rankx(ALLSELECTED(Areas[LEVEL_3]),[Distr_Sales_AC],,DESC,Dense),
			        "Level 4",rankx(ALLSELECTED(Areas[LEVEL_4]),[Distr_Sales_AC],,DESC,Dense)
			        
			    )
			)
			```
		formatString: 0
		lineageTag: ef33986f-b677-4832-ab7c-d7881638cbe8

	measure IsTotalByDimRegion =
			
			var SelectDim=SELECTEDVALUE(RegionLevel[RegionLevelName])
			return SWITCH(SelectDim,
			        "Level 1",ISINSCOPE(Areas[LEVEL_1])=FALSE,
			        "Level 2",ISINSCOPE(Areas[LEVEL_2])=FALSE,
			        "Level 3",ISINSCOPE(Areas[LEVEL_3])=FALSE,
			        "Level 4",ISINSCOPE(Areas[LEVEL_4])=FALSE
			    )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 937fde38-cd2a-4eee-bc95-9553f295cc91

	measure Distr_Sales_AC_Ranked_By_Region_Paginated_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales AC"),[Distr_Sales_AC_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: 2016ee54-b894-4503-8134-9b56f5669015

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_dPY_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_dPY],BLANK())
		lineageTag: 84369530-331c-40e7-871e-f0c48ca00db3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_dPY_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales ΔPY"),[Distr_Sales_dPY_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: 6bf8a10b-ed95-43c3-94c4-ee8be61186f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_GR_PY_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Distr_GR_PY],BLANK())
		lineageTag: 10fcf0ed-623f-4629-ae13-85d7b0d9de42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_GR_PY_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales ΔPY%"),[Distr_Sales_GR_PY_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: ee29e575-5c18-4854-855e-2f3b8f9a0643

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PL_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]|| currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_PL],BLANK())
		lineageTag: 0351f7b1-88af-4fff-808e-0c103ba179db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PL_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales PL"),[Distr_Sales_PL_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: 10735196-422f-4bbb-80ec-88735b4d38ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PE_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_PE],BLANK())
		lineageTag: cf547d69-75d4-4d9d-bbc9-49089993d1be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PE_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales PE%"),[Distr_Sales_PE_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: 44b1398f-93f8-4aa3-94ae-71af9afa6462

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_AC_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Visits_AC],BLANK())
		formatString: 0
		lineageTag: aff12348-f026-402b-b902-0cf41406c260

	measure Visits_AC_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo AC"),[Visits_AC_Ranked_By_Region_Paginated_TopN],BLANK())
		formatString: 0
		lineageTag: f7de5de6-e6d5-4e48-bb2c-2ca8fb5c5f1b

	measure Visits_PL_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Visits_PL],BLANK())
		lineageTag: 83735d54-1dd2-42a0-98fd-0123e09ffffc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PL_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo PL"),[Visits_PL_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: e38a9e93-1124-4552-ba54-c42ea76859dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PE_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Visits_PE],BLANK())
		lineageTag: cc7eb84b-421a-4914-bbf8-c50f72079168

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_PE_Ranked_By_Region_Paginated_TopN_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo PE%"),[Visits_PE_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: 436ff9b1-faba-42a3-aaa9-e314ed890f76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PY_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,[Distr_Sales_PY],BLANK())
		lineageTag: 2c2cab40-2f1e-4f2a-9c75-101326f40fd0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Sales_PY_Ranked_By_Region_Paginated_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr Sales PY"),[Distr_Sales_PY_Ranked_By_Region_Paginated_TopN],BLANK())
		lineageTag: cc94448e-c415-4f2c-8e6d-9687843dbb76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_MS_In_Regions_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,
			    switch(SELECTEDVALUE(RegionLevel[RegionLevelName]),
			        "Level 1",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_1]))),
			        "Level 2",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_2]))),
			        "Level 3",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_3]))),
			        "Level 4",DIVIDE([Distr_Sales_AC],CALCULATE([Distr_Sales_AC],ALLSELECTED(Areas[LEVEL_4])))
			    ),
			BLANK())
		lineageTag: b61c8528-c2cf-48bf-875b-cd0a87fafbe8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_MS_In_Regions_Paginated_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Distr TS%"),[Distr_MS_In_Regions_Paginated_TopN],BLANK())
		lineageTag: 6b1c9144-250c-48ec-8e30-3ae5a9c18cd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Stock_Dyn_PWD =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			VAR AggrType = SELECTEDVALUE(Aggr[AGGR_TYPE])
			VAR Delta = SELECTEDVALUE(SelectAggrLength[Value])
			VAR CDate = SELECTEDVALUE(Periods[Period])
			
			VAR PWDMaxDate = CDate - 7
			VAR PWDMinDate = PWDMaxDate - Delta + 1
			
			RETURN
			IF(
			    CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(
			        AggrType,
			        "Daily",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                Periods[Period] = CDate - 7
			            ),
			        "YTD",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                DATESYTD(DATEADD(Periods[Period], -7, DAY))
			            ),
			        "MTD",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                DATESMTD(DATEADD(Periods[Period], -7, DAY))
			            ),
			        "MQT",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                DATEADD(
			                    DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -90, DAY),
			                    -7,
			                    DAY
			                )
			            ),
			        "MMT",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                DATEADD(
			                    DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -30, DAY),
			                    -7,
			                    DAY
			                )
			            ),
			        "MAT",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                DATEADD(
			                    DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -1, YEAR),
			                    -7,
			                    DAY
			                )
			            ),
			        "Custom",
			            CALCULATE(
			                [SumStockByMeasure],
			                ALL(Periods),
			                Periods[Period] >= PWDMinDate &&
			                Periods[Period] <= PWDMaxDate
			            )
			    ),
			    BLANK()
			)
		lineageTag: f770417b-f052-49d2-9298-84aae881b4ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Stock_PWD =
			CALCULATE([Distr_Stock_Dyn_PWD],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: 15d171d5-d544-4dfc-8dbb-3ea49e218b64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Stock_PWD_Ranked = if([RankByStock]<=[TOP],[Distr_Stock_PWD],BLANK())
		lineageTag: 18380abf-9957-4fd4-a235-c21db1f5eb9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Stock_Rank_AC_Ranked = if([RankByStock]<=[TOP],[RankByStock],BLANK())
		formatString: 0
		lineageTag: 5560658e-766f-4948-b0af-0c5bd059b0cf

	measure Stock_GR_PWD =
			
			var ac=[Distr_Stock_AC]
			var pwd=[Distr_Stock_PWD]
			return if(isblank(ac)||ISBLANK(pwd),blank(),DIVIDE(ac,pwd,0)-1)
		lineageTag: 7f238270-7c12-45ce-8ff4-761b932a072e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Distr_Stock_GR_PWD_Ranked = if([RankByStock]<=[TOP],[Stock_GR_PWD],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 849bc547-1118-4baa-802e-07368a7675a0

	measure Stock_dPWD =
			
			var ac=[Distr_Stock_AC]
			var pwd=[Distr_Stock_PWD]
			return ac-pwd
		lineageTag: 5dcd3a3b-ecab-4edf-9b01-33b7b9bc6db3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_With_Stock_Dyn_AC =
			
			COUNTROWS(
			    FILTER(
			        VALUES(DataStock[CLIENT_ID]),
			        CALCULATE([Distr_Stock_Dyn_AC]) > 0
			    )
			)
		formatString: 0
		lineageTag: 1357bd80-eba4-4e9d-b67b-ee71cc471a8c

	measure Stock_Clients_Count_Total_Dyn_AC =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			VAR AggrType = SELECTEDVALUE(Aggr[AGGR_TYPE])
			VAR delta = SELECTEDVALUE(SelectAggrLength[Value])
			VAR CDate = SELECTEDVALUE(Periods[Period])
			RETURN
			IF(
			    CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(
			        AggrType,
			        "Daily",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID])
			            ),
			        "YTD",
			            TOTALYTD(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                Periods[Period],
			                ALL(Periods)
			            ),
			        "MTD",
			            TOTALMTD(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                Periods[Period],
			                ALL(Periods)
			            ),
			        "MQT",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -90, DAY)
			            ),
			        "MMT",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -30, DAY)
			            ),
			        "MAT",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -1, YEAR)
			            ),
			        "Custom",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -1 * delta, DAY)
			            )
			    ),
			    BLANK()
			)
		formatString: 0
		lineageTag: cc2b71eb-b282-4d8a-8fb5-aaf13a9ad338

	measure PRT_Dyn_AC_Ranked = if([RankByVol]<=[TOP],[PRT_Dyn_AC],BLANK())
		lineageTag: f477c96b-ab57-44dd-b855-0d1449d943a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_Dyn_PWD = DIVIDE([Clients_With_Stock_Dyn_PWD], [Clients_Total_Dyn_PWD])
		lineageTag: aa5917c7-0ef8-49dd-b291-7fbf03e1cb7d

	measure Clients_With_Stock_Dyn_PWD =
			
			COUNTROWS(
			    FILTER(
			        VALUES(DataStock[CLIENT_ID]),
			        CALCULATE([Distr_Stock_Dyn_PWD]) > 0
			    )
			)
		lineageTag: 16e1ed29-c084-43bd-b723-84f714089ddc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_Total_Dyn_PWD =
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR PeriodLength = SELECTEDVALUE(PeriodsFilter[ID])
			VAR AggrType = SELECTEDVALUE(Aggr[AGGR_TYPE])
			VAR Delta = SELECTEDVALUE(SelectAggrLength[Value])
			VAR CDate = SELECTEDVALUE(Periods[Period])
			
			VAR PWDMaxDate = CDate - 7
			VAR PWDMinDate = PWDMaxDate - Delta + 1
			
			RETURN
			IF(
			    CDate >= SelectedDate - PeriodLength + 1 && CDate <= SelectedDate,
			    SWITCH(
			        AggrType,
			        "Daily",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                Periods[Period] = CDate - 7
			            ),
			        "YTD",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATESYTD(DATEADD(Periods[Period], -7, DAY))
			            ),
			        "MTD",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATESMTD(DATEADD(Periods[Period], -7, DAY))
			            ),
			        "MQT",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATEADD(
			                    DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -90, DAY),
			                    -7,
			                    DAY
			                )
			            ),
			        "MMT",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATEADD(
			                    DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -30, DAY),
			                    -7,
			                    DAY
			                )
			            ),
			        "MAT",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                DATEADD(
			                    DATESINPERIOD(Periods[Period], LASTDATE(Periods[Period]), -1, YEAR),
			                    -7,
			                    DAY
			                )
			            ),
			        "Custom",
			            CALCULATE(
			                DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID]),
			                ALL(Periods),
			                Periods[Period] >= PWDMinDate &&
			                Periods[Period] <= PWDMaxDate
			            )
			    ),
			    BLANK()
			)
		formatString: 0
		lineageTag: 23c20354-e40c-4f79-ae46-03b38959764e

	measure PRT_Dyn_PWD_Ranked = if([RankByVol]<=[TOP],[PRT_Dyn_PWD],BLANK())
		lineageTag: bffaefde-c6eb-4e2d-b60f-2ce3179fa32b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_AC =
			CALCULATE([PRT_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 56b469cf-492e-4aaa-9d40-820ad6aa33f4

	measure PRT_AC_Ranked =
			
			var currentRank=[RankByPRT]
			return if([IsTotalByDim]||currentRank<=[TOP],[PRT_AC],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d2c8f2b4-e840-4bd6-a342-f845c03fa46b

	measure PRT_PWD =
			CALCULATE([PRT_Dyn_PWD],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: f10bdd6b-29be-4312-a2d8-9624408ae1d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_PWD_Ranked =
			
			var currentRank=[RankByPRT]
			return if([IsTotalByDim]||currentRank<=[TOP],[PRT_PWD],BLANK())
		lineageTag: cc7d0f3c-6dc4-4203-85ad-b1550f70e670

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_Dyn_AC_Ranked_All_Periods = if([RankByVol_AllPeriods]<=[TOP],[PRT_Dyn_AC],BLANK())
		lineageTag: 5996430c-153b-45b4-abc5-23789ce7280a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RankByPRT =
			
			var SelectDim=SELECTEDVALUE('Dimensions'[DimName])
			return if(ISBLANK([PRT_AC]),1000000,
			    SWITCH(SelectDim,
			        "Corporation",rankx(ALLSELECTED(Drugs[Corporation]),[PRT_AC],,Desc,Dense),
			        "Market Org",rankx(ALLSELECTED(Drugs[Market Org]),[PRT_AC],,Desc,Dense),
			        "Brand",rankx(ALLSELECTED(Drugs[Brand]),[PRT_AC],,Desc,Dense),
			        "Brand+Market Org",rankx(ALLSELECTED(Drugs[Brand+Market Org]),[PRT_AC],,Desc,Dense),
			        "Brand+Corporation",rankx(ALLSELECTED(Drugs[Brand+Corporation]),[PRT_AC],,Desc,Dense),
			        "SKU",rankx(ALLSELECTED(Drugs[Full medication name]),[PRT_AC],,Desc,Dense),
			        "INN",rankx(ALLSELECTED(Drugs[INN]),[PRT_AC],,Desc,Dense),
			        "Comp group L1",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.1])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.1]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.1])),[PRT_AC],,Desc,Dense)),
			        "Comp group L2",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.2]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.2])),[PRT_AC],,Desc,Dense)),
			        "Comp group L3",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.3])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.3]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.3])),[PRT_AC],,Desc,Dense)),
			        "Comp group L4",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.4])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.4]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.4])),[PRT_AC],,Desc,Dense)),
			        "Comp group L5",IF(ISBLANK(SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.5])),1000000,RANKX(FILTER(ALLSELECTED(Groups[PRODUCT_NAME_TREE.5]),NOT ISBLANK(Groups[PRODUCT_NAME_TREE.5])),[PRT_AC],,Desc,Dense)),
			        "Category",rankx(ALLSELECTED(Drugs[CategoryLongName]),[PRT_AC],,Desc,Dense),
			        "Rx/OTC",rankx(ALLSELECTED(Drugs[Rx/OTC]),[PRT_AC],,Desc,Dense),
			        "ATC 1",rankx(ALLSELECTED(Drugs[ATC Code (1)]),[PRT_AC],,Desc,Dense),
			        "ATC 2",rankx(ALLSELECTED(Drugs[ATC Code (2)]),[PRT_AC],,Desc,Dense),
			        "ATC 3",rankx(ALLSELECTED(Drugs[ATC Code (3)]),[PRT_AC],,Desc,Dense),
			        "ATC 4",rankx(ALLSELECTED(Drugs[ATC Code (4)]),[PRT_AC],,Desc,Dense),
			        "ATC 5",rankx(ALLSELECTED(Drugs[ATC Code (5)]),[PRT_AC],,Desc,Dense),
			        "EphMRA 1",rankx(ALLSELECTED(Drugs[EphMRA Code (1)]),[PRT_AC],,Desc,Dense),
			        "EphMRA 2",rankx(ALLSELECTED(Drugs[EphMRA Code (2)]),[PRT_AC],,Desc,Dense),
			        "EphMRA 3",rankx(ALLSELECTED(Drugs[EphMRA Code (3)]),[PRT_AC],,Desc,Dense),
			        "EphMRA 4",rankx(ALLSELECTED(Drugs[EphMRA Code (4)]),[PRT_AC],,Desc,Dense),
			        "NFC 1",rankx(ALLSELECTED(Drugs[NFC Code (1)]),[PRT_AC],,Desc,Dense),
			        "NFC 2",rankx(ALLSELECTED(Drugs[NFC Code (2)]),[PRT_AC],,Desc,Dense),
			        "NFC 3",rankx(ALLSELECTED(Drugs[NFC Code (3)]),[PRT_AC],,Desc,Dense),
			        "Domestic/Foreign(maker)",rankx(ALLSELECTED(Drugs[Domestic/Foreign(maker)]),[PRT_AC],,Desc,Dense),
			        "Maker",rankx(ALLSELECTED(Drugs[Maker]),[PRT_AC],,Desc,Dense),
			        "Cosmetic 1",rankx(ALLSELECTED(Drugs[Cosmetic Name(1)]),[PRT_AC],,Desc,Dense),
			        "Cosmetic 2",rankx(ALLSELECTED(Drugs[Cosmetic Name(2)]),[PRT_AC],,Desc,Dense),
			        "Cosmetic 3",rankx(ALLSELECTED(Drugs[Cosmetic Name(3)]),[PRT_AC],,Desc,Dense),
			        "Cosmetic 4",rankx(ALLSELECTED(Drugs[Cosmetic Name(4)]),[PRT_AC],,Desc,Dense),
			        "Cosmetic 5",rankx(ALLSELECTED(Drugs[Cosmetic Name(5)]),[PRT_AC],,Desc,Dense),
			        "Bad 1",rankx(ALLSELECTED(Drugs[BAD Name(1)]),[PRT_AC],,Desc,Dense),
			        "Bad 2",rankx(ALLSELECTED(Drugs[BAD Name(2)]),[PRT_AC],,Desc,Dense),
			        "MC 1",rankx(ALLSELECTED(Drugs[MC Name(1)]),[PRT_AC],,Desc,Dense),
			        "MC 2",rankx(ALLSELECTED(Drugs[MC Name(2)]),[PRT_AC],,Desc,Dense),
			        "MC 3",rankx(ALLSELECTED(Drugs[MC Name(3)]),[PRT_AC],,Desc,Dense),
			        "MC 4",rankx(ALLSELECTED(Drugs[MC Name(4)]),[PRT_AC],,Desc,Dense),
			        "Region Level 1",rankx(ALLSELECTED(Areas[LEVEL_1]),[PRT_AC],,Desc,Dense),
			        "Region Level 2",rankx(ALLSELECTED(Areas[LEVEL_2]),[PRT_AC],,Desc,Dense),
			        "Region Level 3",rankx(ALLSELECTED(Areas[LEVEL_3]),[PRT_AC],,Desc,Dense),
			        "Region Level 4",rankx(ALLSELECTED(Areas[LEVEL_4]),[PRT_AC],,Desc,Dense),
			        "Area",rankx(ALLSELECTED(Areas[AREA_NAME]),[PRT_AC],,Desc,Dense),
			        "Chain name",rankx(ALLSELECTED(Areas[CHAIN_NAME]),[PRT_AC],,Desc,Dense),
			        "Legal entity",rankx(ALLSELECTED(Areas[ORG_NAME]),[PRT_AC],,Desc,Dense),
			        "Pharmacy name",rankx(ALLSELECTED(Areas[CLIENT_NAME]),[PRT_AC],,Desc,Dense),
			        "Pharmacy address",rankx(ALLSELECTED(Areas[ADDRESS]),[PRT_AC],,Desc,Dense),
			        "Pharmacy type",rankx(ALLSELECTED(Areas[CLIENT_TYPE_ORG]),[PRT_AC],,Desc,Dense),
			        "Pharmacy city",rankx(ALLSELECTED(Areas[CITY]),[PRT_AC],,Desc,Dense)
			    )
			)
		formatString: 0
		lineageTag: a8f1cf8c-16c8-4512-be9c-29068bd4ffa6

	measure TOTAL_PRT = ```
			
			VAR SelectedDate = SELECTEDVALUE(SinglePeriod[Period], MAX(SinglePeriod[Period]))
			VAR AggrType = SELECTEDVALUE(Aggr[AGGR_TYPE])
			VAR delta = SELECTEDVALUE(SelectAggrLength[Value])
			
			RETURN
			    SWITCH(
			        AggrType,
			        "Daily", 
			            CALCULATE(
			                [PRT_Dyn_AC],
			                Periods[Period] = SelectedDate,
			                REMOVEFILTERS(Periods)
			            ),
			        "YTD", 
			            CALCULATE(
			                TOTALYTD([PRT_Dyn_AC], Periods[Period], ALL(Periods)),
			                Periods[Period] <= SelectedDate,
			                REMOVEFILTERS(Periods)
			            ),
			        "MTD", 
			            CALCULATE(
			                TOTALMTD([PRT_Dyn_AC], Periods[Period], ALL(Periods)),
			                Periods[Period] <= SelectedDate,
			                REMOVEFILTERS(Periods)
			            ),
			        "MQT", 
			            CALCULATE(
			                [PRT_Dyn_AC], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -90, DAY)
			            ),
			        "MMT", 
			            CALCULATE(
			                [PRT_Dyn_AC], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -30, DAY)
			            ),
			        "MAT", 
			            CALCULATE(
			                [PRT_Dyn_AC], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -1, YEAR)
			            ),
			        "Custom", 
			            CALCULATE(
			                [PRT_Dyn_AC], 
			                ALL(Periods),
			                DATESINPERIOD(Periods[Period], SelectedDate, -1 * delta, DAY)
			            ),
			        BLANK()
			    )
			
			```
		lineageTag: eb6404ca-9954-42ec-832e-63c26538e044

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_Count = DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID])
		formatString: 0
		lineageTag: bbab39d6-f775-4fff-9403-4ccf87ffb19a

	measure Clients_Count_Stock = DISTINCTCOUNT(StockClientsPeriods[CLIENT_ID])
		formatString: 0
		lineageTag: df48a564-031d-406d-9bc5-58fd4cd381b2

	measure PRT_dPWD =
			
			var gr_ac=[PRT_AC]
			var gr_pwd=[PRT_PWD]
			var gr=(gr_ac-gr_pwd)*100
			return gr
		lineageTag: 4fe5f5a5-a508-4244-a57b-0ab7d2df1fd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Stock_Clients_Count_Total_AC =
			CALCULATE([Stock_Clients_Count_Total_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		formatString: 0
		lineageTag: f642d108-501a-49c8-b0de-c01b6286f15b

	measure Stock_Clients_Count_WO_Stock_AC =
			CALCULATE([Stock_Clients_Count_WO_Stock_Dyn_AC],
			    Filter(Periods,
			        IF(ISFILTERED(Periods[Period]),Periods[setperiod]>0,
			        if(ISFILTERED(SinglePeriod),
			            Periods[setperiod] in values(SinglePeriod[PERIOD_ID]),
			            Periods[setperiod]=max(SinglePeriod[PERIOD_ID]))
			        )
			    )
			)
		lineageTag: 451717e5-b108-4315-959e-f45aa9e4e20b

	measure Stock_Clients_Count_WO_Stock_Dyn_AC = [Stock_Clients_Count_Total_Dyn_AC]-[Clients_With_Stock_Dyn_AC]
		formatString: 0
		lineageTag: 5b3a7261-8c1e-482b-9c6d-9a3898e59547

	measure PRT_AC_Ranked_By_Region_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if(not([IsTotalByDimRegion])&&(currentRank>=beginTop && currentRank<=endTop),[PRT_AC],BLANK())
		lineageTag: b730077c-5ab4-4cb3-a77c-a98602bc3e31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_AC_Ranked_By_Region_Paginated_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Penetration AC,%"),[Distr_Sales_AC_Ranked_By_Region_Paginated_TopN]/100,BLANK())
		lineageTag: c40e94f8-29fa-4de3-8a43-5fd3083e19c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Promo_MS_In_Regions_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||currentRank>=beginTop && currentRank<=endTop,
			    switch(SELECTEDVALUE(RegionLevel[RegionLevelName]),
			        "Level 1",DIVIDE([Visits_AC],CALCULATE([Visits_AC],ALLSELECTED(Areas[LEVEL_1]))),
			        "Level 2",DIVIDE([Visits_AC],CALCULATE([Visits_AC],ALLSELECTED(Areas[LEVEL_2]))),
			        "Level 3",DIVIDE([Visits_AC],CALCULATE([Visits_AC],ALLSELECTED(Areas[LEVEL_3]))),
			        "Level 4",DIVIDE([Visits_AC],CALCULATE([Visits_AC],ALLSELECTED(Areas[LEVEL_4])))
			    ),
			BLANK())
		lineageTag: 7abdc7b4-0564-4139-a1ca-5d7edc51fece

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Promo_MS_In_Regions_Paginated_Managed = IF( CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Promo TS%"),[Promo_MS_In_Regions_Paginated_TopN],BLANK())
		lineageTag: d3de714d-2483-4d79-8b84-fec8a5e8679b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Stock_MS_In_Regions_Paginated_TopN =
			
			var currentPage=SELECTEDVALUE(SelectPages[Value])
			var itemsPerPage=[TOP]
			var beginTop=itemsPerPage*(currentPage-1)+1
			var endTop=itemsPerPage*currentPage
			var currentRank=[RegionRankByVol]
			return if([IsTotalByDimRegion]||(currentRank>=beginTop && currentRank<=endTop),
			    switch(SELECTEDVALUE(RegionLevel[RegionLevelName]),
			        "Level 1",DIVIDE([Distr_Stock_AC],CALCULATE([Distr_Stock_AC],ALLSELECTED(Areas[LEVEL_1]))),
			        "Level 2",DIVIDE([Distr_Stock_AC],CALCULATE([Distr_Stock_AC],ALLSELECTED(Areas[LEVEL_2]))),
			        "Level 3",DIVIDE([Distr_Stock_AC],CALCULATE([Distr_Stock_AC],ALLSELECTED(Areas[LEVEL_3]))),
			        "Level 4",DIVIDE([Distr_Stock_AC],CALCULATE([Distr_Stock_AC],ALLSELECTED(Areas[LEVEL_4])))
			    ),
			BLANK())
		lineageTag: 87f3d2ad-4a47-4fa9-91b3-ea168d94f9be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Stock_MS_In_Regions_Paginated_Managed = IF(CONTAINS( ALLSELECTED(SelectColumns[ColumnName]), SelectColumns[ColumnName], "Stock TS%"),[Stock_MS_In_Regions_Paginated_TopN],BLANK())
		lineageTag: 83c86edf-0586-4a39-9499-d0cb577ae4a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PRT_Rank_AC_Ranked = if([RankByPRT]<=[TOP],[RankByPRT],BLANK())
		formatString: 0
		lineageTag: 3e763b32-e8f6-4d9b-8282-3f5ed46a6e18

	column Value
		isHidden
		formatString: 0
		lineageTag: 29da0010-d81b-4706-95aa-c8cfe2bebff1
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _M_ = calculated
		mode: import
		source = {{BLANK()}}

	annotation PBI_Id = 4390a17f170d4cd08adcc479b1d99541

