table _Measures_
	lineageTag: f668ac20-b48e-456b-9410-f33b39ccd939

	measure 'Sales AC' = [Distr_Sales_Dyn_AC_All_Periods]
		lineageTag: a6ef298e-68ad-4b37-8e71-1140ac496a9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales PY' = [Market_Sales_Dyn_PY_All_Periods]
		lineageTag: dc8580ec-7a3d-49dc-b20f-7698d8830583

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PRT AC' = [PRT_Dyn_AC_All_Periods]
		isHidden
		lineageTag: 2eb85eae-d765-4a95-b877-4d18b5d23b2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PRT PY' = [PRT_Dyn_PY_All_Periods]
		isHidden
		lineageTag: 83ca1b22-148e-4465-a347-cae46f6c0314

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price AC' = [Market_Price_Dyn_AC_All_Periods]
		lineageTag: f39bba0c-b794-4d2c-a3ce-08754ef3ef3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price PY' = [Market_Price_Dyn_PY_All_Periods]
		lineageTag: 893a9e85-f025-48d4-9ce9-ced15fc8e306

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MS = [Distr_Sales_Dyn_AC_All_Periods]/[Market_Sales_Dyn_AC_Total_Dim]
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 69621374-b6f1-4132-9826-638c5b438b75

	measure GR = if([Market_Sales_Dyn_PY_All_Periods]>0,divide([Distr_Sales_Dyn_AC_All_Periods],[Market_Sales_Dyn_PY_All_Periods])-1,BLANK())
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 50cfc77d-3b7f-4526-ab2b-b64520ffed71

	measure EI = [MS]/([Market_Sales_Dyn_PY_All_Periods]/[Market_Sales_Dyn_PY_All_Periods_Total_Dim])*100
		formatString: 0
		isHidden
		lineageTag: c85e5ab0-d841-4d84-8ba9-78837ecd212c

	column Value
		isHidden
		formatString: 0
		lineageTag: d06cdd3c-4357-490d-9483-e37abddb4c32
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures_ = calculated
		mode: import
		source = {{BLANK()}}

	annotation PBI_Id = 5491a56ed4f9457b94fcd8e51e431d0a

