table Areas
	lineageTag: 461d262d-6b0e-4479-b9f3-215880f25305

	column POLYGON_ID
		dataType: string
		lineageTag: 739a34d9-57c4-44d7-acc1-e52d3915f9a5
		summarizeBy: none
		sourceColumn: POLYGON_ID

		annotation SummarizationSetBy = Automatic

	column AREA_ID
		dataType: int64
		formatString: 0
		lineageTag: 38531923-1134-489f-a60a-c666c432270a
		summarizeBy: none
		sourceColumn: AREA_ID

		annotation SummarizationSetBy = Automatic

	column USER_ID
		dataType: int64
		formatString: 0
		lineageTag: b0f28371-996f-4d43-9452-a26aa69c2dd8
		summarizeBy: count
		sourceColumn: USER_ID

		annotation SummarizationSetBy = Automatic

	column BU_ID
		dataType: int64
		formatString: 0
		lineageTag: 4564e89d-c4fb-4a89-98a4-3aeaad55ebcc
		summarizeBy: count
		sourceColumn: BU_ID

		annotation SummarizationSetBy = Automatic

	column VERSION_ID
		dataType: int64
		formatString: 0
		lineageTag: f9e81315-a8e8-4a48-a6ad-82a457aef76c
		summarizeBy: count
		sourceColumn: VERSION_ID

		annotation SummarizationSetBy = Automatic

	column VERSION_NAME
		dataType: string
		lineageTag: 29938bf6-10e6-4c0a-9035-66849db5c15b
		summarizeBy: none
		sourceColumn: VERSION_NAME

		annotation SummarizationSetBy = Automatic

	column BU_VERSION
		dataType: string
		lineageTag: 7d000b65-00bb-4199-83fd-7da9297deeae
		summarizeBy: none
		sourceColumn: BU_VERSION

		annotation SummarizationSetBy = Automatic

	column area_id_from_geo
		dataType: double
		lineageTag: a073a68c-79b3-41ea-ad22-c77f20deb9d4
		summarizeBy: sum
		sourceColumn: area_id_from_geo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BU
		dataType: string
		lineageTag: 30572026-e525-4149-a426-37022fd0ca24
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	column COLOR
		dataType: string
		lineageTag: a593cc0e-b967-47c1-a638-0e6dd50f56ad
		summarizeBy: none
		sourceColumn: COLOR

		annotation SummarizationSetBy = Automatic

	column LEVEL_4
		dataType: string
		lineageTag: 0ef1a647-2135-4512-971a-d9f712bcd573
		summarizeBy: none
		sourceColumn: LEVEL_4

		annotation SummarizationSetBy = Automatic

	column LEVEL_0
		dataType: string
		lineageTag: 7b881397-e31b-42a7-87b2-db97d9ea2d49
		summarizeBy: none
		sourceColumn: LEVEL_0

		annotation SummarizationSetBy = Automatic

	column LEVEL_3
		dataType: string
		lineageTag: 680e2bbe-143e-4cd9-8647-54df07da80cf
		summarizeBy: none
		sourceColumn: LEVEL_3

		annotation SummarizationSetBy = Automatic

	column LEVEL_2
		dataType: string
		lineageTag: ead82691-450b-47aa-a487-1088b83c002d
		summarizeBy: none
		sourceColumn: LEVEL_2

		annotation SummarizationSetBy = Automatic

	column LEVEL_1
		dataType: string
		lineageTag: 4523e004-ee1b-4676-956a-8de934c0c918
		summarizeBy: none
		sourceColumn: LEVEL_1

		annotation SummarizationSetBy = Automatic

	column IS_COVERED
		dataType: int64
		formatString: 0
		lineageTag: 6de7489c-8182-4a7d-b2fa-0b8fdd3d78cf
		summarizeBy: sum
		sourceColumn: IS_COVERED

		annotation SummarizationSetBy = Automatic

	column UserCulture
		dataType: string
		lineageTag: 4bcaebcd-36ab-4441-b888-218bd07de19e
		summarizeBy: none
		sourceColumn: UserCulture

		annotation SummarizationSetBy = Automatic

	column AREA_NAME
		dataType: string
		lineageTag: a12f4556-4af5-4086-aff3-de41c8410977
		summarizeBy: none
		sourceColumn: AREA_NAME

		annotation SummarizationSetBy = Automatic

	column MAP_NAME
		dataType: string
		lineageTag: 0ab5d514-211b-461b-b735-ccfde6581206
		summarizeBy: none
		sourceColumn: MAP_NAME

		annotation SummarizationSetBy = Automatic

	column CLIENT_ID
		dataType: int64
		formatString: 0
		lineageTag: c90eddde-2e7c-414f-8ec1-a5b25a3e25a8
		summarizeBy: none
		sourceColumn: CLIENT_ID

		annotation SummarizationSetBy = Automatic

	column CLIENT_NAME
		dataType: string
		lineageTag: b667afd9-1c72-41d4-9ebc-dcc7d2e54f72
		summarizeBy: none
		sourceColumn: CLIENT_NAME

		annotation SummarizationSetBy = Automatic

	column ORG_NAME
		dataType: string
		lineageTag: 5e927bc2-9f01-4daa-b483-ef9392289c09
		summarizeBy: none
		sourceColumn: ORG_NAME

		annotation SummarizationSetBy = Automatic

	column CHAIN_NAME
		dataType: string
		lineageTag: 23cc3171-2b99-4582-90ac-604e2c09a95f
		summarizeBy: none
		sourceColumn: CHAIN_NAME

		annotation SummarizationSetBy = Automatic

	column CLIENT_TYPE_ORG
		dataType: string
		lineageTag: 3d7a60a0-1e45-43d8-a828-681ea697cdf6
		summarizeBy: none
		sourceColumn: CLIENT_TYPE_ORG

		annotation SummarizationSetBy = Automatic

	column ADDRESS
		dataType: string
		lineageTag: 94f5a6b5-ca28-423b-8a6b-fc232c4bb7da
		summarizeBy: none
		sourceColumn: ADDRESS

		annotation SummarizationSetBy = Automatic

	column CITY
		dataType: string
		lineageTag: 6ef7320b-c812-4c5b-8b47-ca01d88cbbcd
		summarizeBy: none
		sourceColumn: CITY

		annotation SummarizationSetBy = Automatic

	partition Areas = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces=Source{[Id="Workspaces"]}[Data],
				    DATA_LAYERS_ = Workspaces{[workspaceId=_WS_ID_]}[Data]{[dataflowId=_SO_TL_FLOW_ID_]}[Data]{[entity="DATA_LAYERS",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(DATA_LAYERS_,{{"POLYGON_ID", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","","Uncovered",Replacer.ReplaceValue,{"LEVEL_3"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","","Uncovered",Replacer.ReplaceValue,{"LEVEL_2"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","","Uncovered",Replacer.ReplaceValue,{"LEVEL_1"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value2",{"AREA_NAME"}),
				    // Filter Areas by restricts
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"AREA_ID"}, AreasSRC, {"AREA_ID"}, "AreasSRC", JoinKind.Inner),
				    #"Expanded AreasSRC" = Table.ExpandTableColumn(#"Merged Queries", "AreasSRC", {"UserCulture", "AREA_NAME"}, {"AreasSRC.UserCulture", "AreasSRC.AREA_NAME"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded AreasSRC",{{"AreasSRC.UserCulture", "UserCulture"}, {"AreasSRC.AREA_NAME", "AREA_NAME"}}),
				    Res=if Table.HasColumns(#"Renamed Columns1",{"MAP_NAME"}) then #"Renamed Columns1" else Table.AddColumn(#"Renamed Columns1", "MAP_NAME", each [BU],Text.Type),
				    #"Added Custom" = Table.AddColumn(Res, "MAP_NAME_FIX", each [MAP_NAME]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"MAP_NAME_FIX", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"MAP_NAME"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"MAP_NAME_FIX", "MAP_NAME"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"area_name_eng", "area_name_ukr", "area_name_rus"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns2", {"POLYGON_ID"}, PolygonsAndClients, {"DATA_LAYER_ID"}, "PolygonsAndClients", JoinKind.LeftOuter),
				    #"Expanded PolygonsAndClients" = Table.ExpandTableColumn(#"Merged Queries1", "PolygonsAndClients", {"CLIENT_ID"}, {"PolygonsAndClients.CLIENT_ID"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Expanded PolygonsAndClients",{{"PolygonsAndClients.CLIENT_ID", "CLIENT_ID"}}),
				    #"Merged Queries2" = Table.NestedJoin(#"Renamed Columns2", {"CLIENT_ID", "UserCulture"}, Clients, {"CLIENT_ID", "UserCulture"}, "Clients", JoinKind.LeftOuter),
				    #"Expanded Clients" = Table.ExpandTableColumn(#"Merged Queries2", "Clients", {"CLIENT_NAME", "ORG_NAME", "CHAIN_NAME", "CLIENT_TYPE_ORG", "ADDRESS", "CITY"}, {"Clients.CLIENT_NAME", "Clients.ORG_NAME", "Clients.CHAIN_NAME", "Clients.CLIENT_TYPE_ORG", "Clients.ADDRESS", "Clients.CITY"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Expanded Clients",{{"Clients.CLIENT_NAME", "CLIENT_NAME"}, {"Clients.ORG_NAME", "ORG_NAME"}, {"Clients.CHAIN_NAME", "CHAIN_NAME"}, {"Clients.CLIENT_TYPE_ORG", "CLIENT_TYPE_ORG"}, {"Clients.ADDRESS", "ADDRESS"}, {"Clients.CITY", "CITY"}})
				in
				    #"Renamed Columns3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

