table Brand_GR_Iterator
	isHidden
	lineageTag: d7880c85-2530-4375-b013-bcffa1728383

	measure 'Brand_GR_Iterator Value' = SELECTEDVALUE('Brand_GR_Iterator'[Brand_GR_Iterator])
		formatString: 0
		isHidden
		lineageTag: c99aae7f-4985-4eb4-a332-a2b2e2639cb9

	measure Test = SELECTEDVALUE(Groups[PRODUCT_NAME_TREE.2])=""
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isHidden
		lineageTag: 9ff4d1e8-3728-4e0a-b2dc-30680b7ae950

	column Brand_GR_Iterator
		isHidden
		formatString: 0
		lineageTag: 58dd1156-1248-44db-9637-e5697f6c1cff
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Brand_GR_Iterator = calculated
		mode: import
		source = GENERATESERIES(1, 3, 1)

	annotation PBI_Id = 84652cce5ec141d38b95119e330f107b

