table Captions
	isHidden
	lineageTag: b8cfdb14-855a-45f7-96d3-9b90f4041a1e

	measure Caption_Version = "v. "&[Version]
		isHidden
		lineageTag: 0160c8ab-3826-4422-93e0-46ca3c53832a

	measure Caption_Copyright = "PROXIMA RESEARCH © 2023"
		isHidden
		lineageTag: 7e1a0202-4c4f-4663-a317-32fa04009bd7

	measure Caption_Page_Name_Market_Rating = var s="Market rating" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 3d91a7bf-7741-422c-b4df-2e11b99ab04e

	measure Caption_Main_Header = var s="{COUNTRY} pharmaceuticals market" var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s) RETURN SUBSTITUTE(ss,"{COUNTRY}",[Country_Name])
		isHidden
		lineageTag: 8781e7f8-6b5b-47b5-b8b5-b227b7b3145e

	measure Caption_Header_3 = ```
			
			var filterStr=[Current_Filters]
			return [Selected_Periods_List]&if(len(filterStr)>0,", "&filterStr)
			
			```
		isHidden
		lineageTag: 8cf56e81-c50b-47ed-84af-8c530cd7570d

	measure Caption_Header_2 =
			
			var currentMeasure=SELECTEDVALUE(SelectMeasures[MeasureName])
			var currentAggrType=[Current_Aggr_Type]
			var s="{DATA_TYPE} sales in {MEASURE}"
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			var sss=SUBSTITUTE(SUBSTITUTE(ss,"{DATA_TYPE}",[Current_Data_Type]),"{MEASURE}",currentMeasure)
			RETURN sss&", "&currentAggrType
		isHidden
		lineageTag: 301f5518-b10d-412e-87a3-b1da19a357f0

	measure Caption_Page_Name_Market_Overview = var s="Market overview" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 6a3ba4f7-6eba-4b4b-b713-1547b65d43de

	measure Caption_Page_Name_Group_Analysis = var s="Group analysis" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: dfd7e0c6-63f7-45b8-93e0-393b3364c32b

	measure Caption_KPI_Market_Sales = var s="Distr sales (month)" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 8bbcde3e-27a8-4e27-b81f-6f6d530dac6a

	measure Caption_KPI_Distr_Sales_Month_AC =
			
			var num=[Distr_Sales_Month_AC]
			var lg=LOG10(abs(num))
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K")
			return FORMAT(num,fmt)
		isHidden
		lineageTag: 6036ab61-091c-4808-b90a-3f3b3970aa41

	measure Caption_KPI_Distr_GR_Month_PY =
			
			var gr=[Distr_GR_Month_PY]
			return FORMAT(gr,"▲+0.0% △PY;▼-0.0% △PY")
		isHidden
		lineageTag: 08346080-8e62-43b6-805b-c30af35fa997

	measure Caption_KPI_Market_GR_PP =
			
			var gr=[Market_GR_PP]
			return FORMAT(gr,"▲+0.0% △PP;▼-0.0% △PP")
		isHidden
		lineageTag: 38914a79-cd7c-49d3-a9b0-cfa31d84cbe0

	measure Caption_KPI_Promo = var s="Promotions (month)" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 33f23ac8-0746-43a5-afa0-c597724192b8

	measure Caption_KPI_Stock = var s="Stock monitoring" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 5c006f2e-79c6-425b-a4ee-39bf41dc7a2d

	measure Caption_KPI_Distr_Sales_FC = var s="Distr sales (forecast)" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: de7a63b1-7eaf-449e-8174-3baf52b60593

	measure Caption_KPI_MO_Rank = var s="Self rank" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 8881fc27-4e28-4dd9-bde5-dfab68feca8d

	measure Caption_KPI_Promo_Month_AC =
			
			var num=[Promo_Month_AC]
			var lg=LOG10(num)
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K")
			return FORMAT(num,fmt)
		isHidden
		lineageTag: f0433899-800f-447d-b69d-17f2a73069ad

	measure Caption_KPI_Promo_GR_Month_PY =
			
			var gr=[Promo_GR_Month_PY]
			return if(ISBLANK(gr),"--",FORMAT(gr,"▲+0.0% △PY;▼-0.0% △PY"))
		isHidden
		lineageTag: 948e7a20-5c41-4664-a92f-fa688821277c

	measure Caption_KPI_SelfMO_GR_PP =
			
			var gr=[SelfMO_GR_PP]
			return FORMAT(gr,"▲+0.0% △PP;▼-0.0% △PP")
		isHidden
		lineageTag: 2eacbc90-71a5-4e0c-ad10-4bd89cd37932

	measure Caption_Page_Name_GR_Indexes = var s="GR indexes" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 72637a42-9231-4529-88df-873b47934397

	measure Caption_KPI_Stock_AC =
			
			var num=[Distr_Stock_AC]
			var lg=LOG10(abs(num))
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K")
			return FORMAT(num,fmt)
		isHidden
		lineageTag: c54af078-c842-4622-840d-a83746d028c2

	measure Caption_KPI_Distr_Sales_Month_FC =
			
			var num=[Distr_Sales_Month_FC]
			var lg=LOG10(abs(num))
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K")
			return FORMAT(num,fmt)
		isHidden
		lineageTag: dc1dfb53-ca24-43bf-9ff5-0b686e36c66f

	measure Caption_KPI_SelfMO_GR_MS = Format(abs([SelfMO_GR_MS])*100,if([SelfMO_GR_MS]>0,"▲+0.0 △PY","▼-0.0 △PY"))
		isHidden
		lineageTag: 9a4d902f-64c3-4657-94eb-da1fd3b39256

	measure Caption_KPI_SelfMO_GR_EI =
			
			var ei1=[SelfMO_EI_AC]
			var ei2=[SelfMO_EI_PY]
			return FORMAT((ei1-ei2),"▲+0 △PY;▼-0 △PY")
		isHidden
		lineageTag: b59827c0-20f0-448e-9da5-4e9da65eefd9

	measure SelfMO_Rank =
			
			var RankMO=FILTER(SUMMARIZE(MarketOrgs,MarketOrgs[Market Org ID],"RankBySales",[Market_Sales_Rank_MO_AC]),[Market Org ID]=[SelfMO_ID])
			return sumx(RankMO,[RankBySales])
		formatString: 0
		isHidden
		lineageTag: e05f3615-0cff-4f01-937c-37d99cc22160

	measure Caption_KPI_SelfMO_Rank = Format([SelfMO_Rank],"#0")
		isHidden
		lineageTag: bfca5cf5-5086-41ed-b7c1-e1a63fa9abf9

	measure Market_Sales_Rank_MO_AC = RANKX(ALLSELECTED(MarketOrgs[Market Org ID]), [Distr_Sales_AC])
		formatString: 0
		isHidden
		lineageTag: 7769903b-d007-42fb-a80c-78f0e9822fea

	measure SelfMO_Rank_PY =
			
			var RankMO=FILTER(SUMMARIZE(MarketOrgs,MarketOrgs[Market Org ID],"RankBySales",[Market_Sales_Rank_MO_PY]),[Market Org ID]=[SelfMO_ID])
			return sumx(RankMO,[RankBySales])
		isHidden
		lineageTag: b39c5d7c-a144-433c-b7fa-f63333e474c1

	measure Market_Sales_Rank_MO_PY = RANKX(ALLSELECTED(MarketOrgs[Market Org ID]), [Distr_Sales_PY])
		formatString: 0
		isHidden
		lineageTag: 18d4a610-6fdb-48f6-935d-98df3efc0ce4

	measure SelfMO_GR_Rank = [SelfMO_Rank]-[SelfMO_Rank_PY]
		formatString: 0
		isHidden
		lineageTag: 4ae3c9b3-31c2-4a00-b6b4-b02533d78cca

	measure Caption_KPI_MO_GR_Rank =
			
			var delta=[SelfMO_GR_Rank]
			return FORMAT((delta),"▲+0 △PY;▼-0 △PY")
		isHidden
		lineageTag: ddbbc425-5342-468c-abc8-ef616eb7ce2c

	measure Caption_KPI_SelfMO_Rank_PY =
			
			var gr=[SelfMO_Rank_PY]
			return FORMAT(gr,"0 PY")
		isHidden
		lineageTag: de0ff6de-444c-47a6-88a8-7a8415ed394f

	measure Caption_Page_Name_GR_Indexes_2 = "GR indexes (2)"
		isHidden
		lineageTag: 71e0616d-a27b-4b44-b1cc-d5d164a5b309

	measure Caption_KPI_Market_USD_GR_Min =
			
			var MinGR=[Market_GR_USD_Min]
			return FORMAT(MinGR,"▲+0.0%;▼-0.0%")
		isHidden
		lineageTag: 2981bd7f-a5a8-4793-b7d6-def56729275a

	measure Caption_Page_Name_Market_Forecast = var s="Market forecast" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 8001ceec-378a-4d6f-a7f6-fa2c38a2660e

	measure Caption_Page_Name_Market_Dynamic = var s="Market dynamic" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 53a7fa19-df89-492d-aaa7-3ad0d6f6c361

	measure Caption_Page_Name_Export_Data = var s="Export data" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 6835ae5f-4b6f-4897-8538-649395681d86

	measure Caption_Page_Name_Glossary = var s="Glossary" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: d1049a4a-3d74-46c9-80d9-682322162b9c

	measure Caption_Page_Works_Only_In_Desktop_Mode = "This page works only in desktop mode!"
		isHidden
		lineageTag: 1216eb8a-e6d4-4ea5-9b6e-8503239e2d35

	measure Caption_Page_Switch_To_Desktop_Mode = "If yo want to use this page you need to switch to desktop mode!"
		isHidden
		lineageTag: 10d8793b-2294-4f69-bb7c-161386fe1b52

	measure Caption_KPI_SelfMO_EI_PP = FORMAT([SelfMO_EI_PP],"#0")
		isHidden
		lineageTag: 7c18603f-3a41-477d-a668-2dbb74d36d76

	measure Caption_KPI_SelfMO_GR_MS_PP = Format(abs([SelfMO_GR_MS_PP]*100),if([SelfMO_GR_MS_PP]>0,"▲+0.0 △PP","▼-0.0 △PP"))
		isHidden
		lineageTag: 6dd18c0c-0df8-4804-96f3-a352781e881e

	measure Caption_KPI_SelfMO_GR_EI_PP =
			
			var ei1=[SelfMO_EI_AC]
			var ei2=[SelfMO_EI_PP]
			return FORMAT((ei1-ei2),"▲+0 △PP;▼-0 △PP")
		isHidden
		lineageTag: dfb69aaf-bfd0-4073-a4b5-a257a891298c

	measure Caption_Page_Name_Penetration = var s="Penetration" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 7d3b82b6-b520-4dfe-a3e3-d056bd54d496

	measure Caption_Page_Name_Ecom = var s="E-com" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: ac0c259c-dd8f-4f11-af01-a5c6244434c0

	measure Caption_Page_Name_GR_Analysis = var s="GR analysis" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: e0e4db5b-a257-44d3-99c1-8dc0bec4a2d6

	measure Caption_Ecom_Not_Allow = "This page is not allowed for this role"
		isHidden
		lineageTag: 6d28e1e9-6807-4990-9fef-8a94cce6a864

	measure Caption_Page_Name_Price_Analysis = var s="Price analysis" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: a2f121cf-e94b-425c-95e8-d79f31b26991

	measure SelfMO_GR_MS_PP = [SelfMO_MS_AC]-[SelfMO_MS_PP]
		formatString: 0.00000
		isHidden
		lineageTag: d2616812-bcf6-424e-839d-bf96006070c6

	measure SelfMO_GR_MS = [SelfMO_MS_AC]-[SelfMO_MS_PY]
		formatString: 0.00000
		isHidden
		lineageTag: ec639efb-589c-43fe-951b-ca8f30a2469a

	measure Caption_Settings = var s="Settings" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: def7ce6c-fe4b-4ef3-a791-48ea6725b039

	measure Caption_Close = var s="Close" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 0bf92767-2252-4972-b4ea-fad99aa5da93

	measure Caption_Page = var s="Page" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 5c686179-59f7-4259-904b-c1c4fc0eea83

	measure Caption_Header_2_Export =
			
			var currentAggrType=SELECTEDVALUE(Aggr[AGGR_TYPE])
			var s="{DATA_TYPE} sales"
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			var sss=SUBSTITUTE(ss,"{DATA_TYPE}",[Current_Data_Type])
			RETURN sss&", "&currentAggrType
		isHidden
		lineageTag: 7bf02570-d145-44fd-b632-5148eea8d7aa

	measure Caption_Glossary_1 = var s="Designation of data types" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 444d95ca-94dd-46ed-b2ed-1430a7d0260e

	measure Caption_Glossary_2 = var s="Color schema" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: a5666440-f15a-4d33-b4c4-257e7c7dc5af

	measure Caption_Glossary_3 = var s="Settings – customizing the display of charts" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: ee566bec-1b3f-49ce-b434-de7bda3ab18b

	measure Caption_Glossary_4 = var s="Filters" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 24b90ea1-761f-4a08-bc2f-58998eb140cf

	measure Caption_Glossary_1_Content = var s="Glossary_Content_1" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: e6be9c47-b8da-41c6-b77a-1dc7aab8f63e

	measure Caption_Glossary_2_Content = ```
			
			var s="Glossary_Content_2" 
			var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
			return SUBSTITUTE(ss,"{CURRENCY}",_CURRENCY_[Currency_Name])
			```
		isHidden
		lineageTag: 8f1ed0c0-f9c4-4030-8225-36335c0d193f

	measure Caption_Glossary_4_Content = var s="Glossary_Content_4" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 7e8c760f-cbb4-4566-af25-9716137fa96d

	measure Caption_Glossary_3_Content = var s="Glossary_Content_3" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 4e85f951-fa1e-46b7-8fd2-5011588b0010

	measure Caption_KPI_Market_Price = var s="Weighted cost ({MEASURE})" var ss=CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s) return SUBSTITUTE(ss,"{MEASURE}",SELECTEDVALUE(SelectMeasures[MeasureName]))
		isHidden
		lineageTag: 6bedd5fd-ad52-452c-a898-95cf16ae5fdf

	measure Caption_KPI_Market_Price_AC =
			
			var num=[Market_Price_AC]
			var lg=LOG10(num)
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K","##0.0")
			return FORMAT(num,fmt)
		isHidden
		lineageTag: 32f7f234-6b6a-4b26-8f11-0affbd7664e5

	measure Caption_KPI_Price_GR_PY =
			
			var gr=[Price_GR_PY]
			return FORMAT(gr,"▲+0.0% △PY;▼-0.0% △PY")
		isHidden
		lineageTag: c305d538-69ad-446a-9820-afa58bfca351

	measure Caption_KPI_Price_GR_PP =
			
			var gr=[Price_GR_PP]
			return FORMAT(gr,"▲+0.0% △PP;▼-0.0% △PP")
		isHidden
		lineageTag: 01e2a93e-d311-493e-a61e-e47d7de4103b

	measure Caption_KPI_Distr_Sales_Month_dPL =
			
			var gr=[Distr_Sales_Month_dPL]
			var lg=LOG10(abs(gr))
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K")
			return FORMAT(gr,"+"&fmt&";-"&fmt)&" △PL"
		lineageTag: e28e3245-2b6b-45af-b788-d3fc524dbb5c

	measure Caption_KPI_Distr_Sales_PE =
			
			var gr=[Distr_Sales_Month_PL]
			return if(ISBLANK(gr),"0.0% P",FORMAT(gr,"0.0% P"))&"E"
		lineageTag: 021dc848-837c-461e-8628-3573c09834df

	measure Caption_KPI_Distr_Sales_Month_PE =
			
			var gr=[Distr_Sales_Month_PE]
			return if(ISBLANK(gr),"0.0% P",FORMAT(gr,"0.0% P"))&"E"
		lineageTag: f1444069-a2c2-47c3-92de-ec220cb69bc7

	measure Caption_KPI_Promo_Month_dPL =
			
			var gr=[Promo_Month_dPL]
			var lg=LOG10(abs(gr))
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K")
			return FORMAT(gr,"+"&fmt&";-"&fmt)&" △PL"
		lineageTag: 4451d6a7-35cd-4e69-96b1-17600b72a8c6

	measure Caption_KPI_Promo_Month_PE =
			
			var gr=[Promo_Month_PE]
			return if(ISBLANK(gr),"0.0% P",FORMAT(gr,"0.0% P"))&"E"
		lineageTag: 82aa947d-bd37-4488-b8a5-a393a762bb94

	measure Caption_KPI_Distr_Sales_FC_PE = var s="Distr sales PE (forecast)" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		lineageTag: b0a7c0dc-79ac-467c-b793-87a97c2faaa4

	measure Caption_KPI_Distr_Sales_PE_Month_FC =
			
			var gr=[Distr_Sales_PE_Month_FC]
			return if(ISBLANK(gr),"0.0%",FORMAT(gr,"0.0%"))
		lineageTag: efb35e8a-c055-42a9-bbea-e3fbced793eb

	measure Caption_KPI_Stock_dPWD =
			
			var gr=[Stock_dPWD]
			var lg=LOG10(abs(gr))
			var fmt=SWITCH(TRUE(),lg>=9,"##0,,,.0bn",lg>=6,"##0,,.0M",lg>3,"##0,.0K","##0")
			return FORMAT(gr,"+"&fmt&";-"&fmt)&" △PWD"
		lineageTag: befda9be-c786-401e-a330-857f98be0cf2

	measure Caption_KPI_Stock_GR_PWD =
			
			var gr=[Distr_Stock_GR_PWD]
			return FORMAT(gr,"▲+0.0% △PWD;▼-0.0% △PWD")
		lineageTag: 5ffa2817-e4de-4cb7-837a-d6cfeb747e8d

	measure Caption_KPI_PRT = var s="Penetration" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		lineageTag: 02f7ea92-c931-4764-97f4-a116c2fd47c5

	measure Caption_KPI_PRT_AC =
			
			var num=[PRT_AC]
			return FORMAT(num,"#0.0%")
		lineageTag: e1328cbe-5445-4117-9cfe-885b178e1c30

	measure Caption_KPI_PRT_dPWD =
			
			var gr=[PRT_dPWD]
			return FORMAT(gr,"▲+0.0pp △PWD;▼-0.0pp △PWD")
		lineageTag: a83ccbd6-eb51-4edf-9b0d-30d77da16c87

	measure Caption_KPI_Pharmacy_Count_Total_AC =
			
			var num=[Stock_Clients_Count_Total_AC]
			return FORMAT(num,"#0")
		lineageTag: aa8e9e82-547b-41f5-bf42-3f49bfca5bf2

	measure Caption_KPI_Pharmacy_Count_Total = var s="Pharmacy count (total)" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		lineageTag: 4dedd1c8-9917-49e5-b609-94f9321f21f0

	measure Caption_KPI_Pharmacy_Count_WO_Stock = var s="Pharmacy count (w/o stock)" RETURN CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		lineageTag: b979be43-2a88-4c60-8d02-7049cb6327a8

	measure Caption_KPI_Pharmacy_Count_WO_Stock_AC =
			
			var num=[Stock_Clients_Count_WO_Stock_AC]
			return FORMAT(num,"#0")
		lineageTag: 0505e1a5-af93-4ef4-932c-6d4cdb5eb1e0

	column Value
		isHidden
		formatString: 0
		lineageTag: e123ae39-de11-42aa-a9f2-40e96301d2b0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Captions = calculated
		mode: import
		source = {{BLANK()}}

	annotation PBI_Id = 68de696fb83b4e359060195f6198ff7d

