table DataStock
	lineageTag: 78ba731f-29d2-439a-95da-a9249a99357c

	column DT
		dataType: int64
		formatString: 0
		lineageTag: e1ec2add-6a15-413e-9c1d-39d6bc1d8cac
		summarizeBy: sum
		sourceColumn: DT

		annotation SummarizationSetBy = Automatic

	column PERIOD_ID
		dataType: int64
		formatString: 0
		lineageTag: bf9eee3e-f9bb-4ca1-b6be-703945ffe841
		summarizeBy: none
		sourceColumn: PERIOD_ID

		annotation SummarizationSetBy = Automatic

	column DRUGS_ID
		dataType: int64
		formatString: 0
		lineageTag: 50745820-704e-4af3-8814-aed208e53090
		summarizeBy: none
		sourceColumn: DRUGS_ID

		annotation SummarizationSetBy = Automatic

	column CLIENT_ID
		dataType: int64
		formatString: 0
		lineageTag: b9acb2a0-82a8-4c6e-9865-09a1c099fe36
		summarizeBy: none
		sourceColumn: CLIENT_ID

		annotation SummarizationSetBy = Automatic

	column PCS
		dataType: double
		lineageTag: e3ce2a3a-b9d0-4e45-9bd3-562a122a8843
		summarizeBy: sum
		sourceColumn: PCS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TABS
		dataType: double
		lineageTag: 1760dbe4-e3e0-4d99-935c-360e9bbdcc8b
		summarizeBy: sum
		sourceColumn: TABS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DDD
		dataType: double
		lineageTag: ab22a80f-a2da-4bad-acdb-5072a5eb7ad5
		summarizeBy: sum
		sourceColumn: DDD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DataStock = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    SO_MONTHLY_ = Source{[Id="Workspaces"]}[Data]{[workspaceId=_WS_ID_]}[Data]{[dataflowId=_DATA_FLOW_ID_]}[Data]{[entity="STOCK_DAILY",version=""]}[Data],
				    #"Added Custom" = Table.AddColumn(SO_MONTHLY_, "DT", each 3),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"DT", Int64.Type}}),
				    DistinctDrugs=Table.Distinct(Table.SelectColumns(Drugs,{"DRUGS_ID","DRUG_FORM_NUMBER","DDD_AMOUNT"}),"DRUGS_ID"),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"DRUGS_ID"}, DistinctDrugs, {"DRUGS_ID"}, "Drugs", JoinKind.Inner),
				    #"Expanded Drugs" = Table.ExpandTableColumn(#"Merged Queries", "Drugs", {"DRUG_FORM_NUMBER", "DDD_AMOUNT"}, {"Drugs.DRUG_FORM_NUMBER", "Drugs.DDD_AMOUNT"}),
				    #"Added Custom2" = Table.AddColumn(#"Expanded Drugs", "TABS", each [PCS]*[Drugs.DRUG_FORM_NUMBER]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom2", "DDD", each [PCS]*[Drugs.DDD_AMOUNT]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"TABS", type number}, {"DDD", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"Drugs.DRUG_FORM_NUMBER", "Drugs.DDD_AMOUNT"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

