table Drugs
	lineageTag: fe1d2a70-b33f-4fb2-8d80-de00503f0e77

	column DRUGS_ID
		dataType: int64
		formatString: 0
		lineageTag: 61c25761-4ce4-4a3f-9787-8f96d6cf287a
		summarizeBy: none
		sourceColumn: DRUGS_ID

		annotation SummarizationSetBy = Automatic

	column Domestic/Foreign
		dataType: string
		lineageTag: 7d0cc8d0-2208-4751-ba09-9033394717b1
		summarizeBy: none
		sourceColumn: Domestic/Foreign

		annotation SummarizationSetBy = Automatic

	column Domestic/Foreign(maker)
		dataType: string
		lineageTag: 9c12e2c0-4702-4b5a-a65e-4bc7a7615729
		summarizeBy: none
		sourceColumn: Domestic/Foreign(maker)

		annotation SummarizationSetBy = Automatic

	column INN
		dataType: string
		lineageTag: 93db17d0-e62c-4249-b8cd-6df623d30178
		summarizeBy: none
		sourceColumn: INN

		annotation SummarizationSetBy = Automatic

	column 'Full medication name'
		dataType: string
		lineageTag: ae583c97-3d81-4afe-aa56-58cf38d76c33
		summarizeBy: none
		sourceColumn: Full medication name

		annotation SummarizationSetBy = Automatic

	column DRUG_FORM_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 8402c726-a03e-42b8-ad28-d8bd8b979635
		summarizeBy: sum
		sourceColumn: DRUG_FORM_NUMBER

		annotation SummarizationSetBy = Automatic

	column DrugForm
		dataType: string
		lineageTag: e81d4c39-ae50-45ba-8370-8e4ffd3071f2
		summarizeBy: none
		sourceColumn: DrugForm

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 5c59e6f2-d033-4cab-8f50-a4fd1fc57046
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column DRUG_NAME
		dataType: string
		lineageTag: 42cfc778-eb39-4537-a260-a88c74facc57
		summarizeBy: none
		sourceColumn: DRUG_NAME

		annotation SummarizationSetBy = Automatic

	column BRAND_ID
		dataType: int64
		formatString: 0
		lineageTag: 9126c6ed-64c1-452d-b661-bc9add3b830d
		summarizeBy: count
		sourceColumn: BRAND_ID

		annotation SummarizationSetBy = Automatic

	column Brand+Corporation
		dataType: string
		lineageTag: 0a5bcd19-31bb-4852-a5f5-751420ee8e31
		summarizeBy: none
		sourceColumn: Brand+Corporation

		annotation SummarizationSetBy = Automatic

	column 'Brand+Market Org'
		dataType: string
		lineageTag: d2dc3e24-aa00-45a9-ae3e-1f1750ecb5a4
		summarizeBy: none
		sourceColumn: Brand+Market Org

		annotation SummarizationSetBy = Automatic

	column 'Brand+EphMRA 1'
		dataType: string
		lineageTag: ef0819f7-4eb9-480c-aa57-a3babab4e719
		summarizeBy: none
		sourceColumn: Brand+EphMRA 1

		annotation SummarizationSetBy = Automatic

	column 'Market Org ID'
		dataType: int64
		formatString: 0
		lineageTag: 336910fc-590f-4e08-bf78-e22604f5b16f
		summarizeBy: count
		sourceColumn: Market Org ID

		annotation SummarizationSetBy = Automatic

	column 'Market Org'
		dataType: string
		lineageTag: 21df2886-ccfc-4918-89d2-5db132139837
		summarizeBy: none
		sourceColumn: Market Org

		annotation SummarizationSetBy = Automatic

	column Maker
		dataType: string
		lineageTag: 51e1e418-dfd7-49f7-b700-9917604080f1
		summarizeBy: none
		sourceColumn: Maker

		annotation SummarizationSetBy = Automatic

	column Corporation
		dataType: string
		lineageTag: 31e8af3e-d6e7-4c85-835d-22c6d71b04bd
		summarizeBy: none
		sourceColumn: Corporation

		annotation SummarizationSetBy = Automatic

	column 'ATC Code (1)'
		dataType: string
		lineageTag: c9eec1cd-240c-4ed2-aa14-8e3c889c1297
		summarizeBy: none
		sourceColumn: ATC Code (1)

		annotation SummarizationSetBy = Automatic

	column 'ATC Code (2)'
		dataType: string
		lineageTag: 8167e64a-bbe0-448d-be72-58a351daebf0
		summarizeBy: none
		sourceColumn: ATC Code (2)

		annotation SummarizationSetBy = Automatic

	column 'ATC Code (3)'
		dataType: string
		lineageTag: fb1f8d20-9816-4a2f-874b-f3fcdb74eea0
		summarizeBy: none
		sourceColumn: ATC Code (3)

		annotation SummarizationSetBy = Automatic

	column 'ATC Code (4)'
		dataType: string
		lineageTag: 351d20f2-8403-40c3-864c-a9ebf1ce1f0c
		summarizeBy: none
		sourceColumn: ATC Code (4)

		annotation SummarizationSetBy = Automatic

	column 'ATC Code (5)'
		dataType: string
		lineageTag: 3f0d90fa-de00-4e26-a134-35cb0c1447b3
		summarizeBy: none
		sourceColumn: ATC Code (5)

		annotation SummarizationSetBy = Automatic

	column 'EphMRA Code (1)'
		dataType: string
		lineageTag: 5094aaa5-7588-4cf1-af18-cf501c7ca337
		summarizeBy: none
		sourceColumn: EphMRA Code (1)

		annotation SummarizationSetBy = Automatic

	column 'EphMRA Code (2)'
		dataType: string
		lineageTag: 2866b7c3-15b6-4e49-9986-07417241c62d
		summarizeBy: none
		sourceColumn: EphMRA Code (2)

		annotation SummarizationSetBy = Automatic

	column 'EphMRA Code (3)'
		dataType: string
		lineageTag: 70bced9d-e27c-48c2-bf86-ba58071c895e
		summarizeBy: none
		sourceColumn: EphMRA Code (3)

		annotation SummarizationSetBy = Automatic

	column 'EphMRA Code (4)'
		dataType: string
		lineageTag: 7f27e44b-096e-4fb1-8731-873a56201ad6
		summarizeBy: none
		sourceColumn: EphMRA Code (4)

		annotation SummarizationSetBy = Automatic

	column Cosmetic_1
		dataType: string
		lineageTag: 7be8608f-2355-4893-9180-bda266a3fdec
		summarizeBy: none
		sourceColumn: Cosmetic_1

		annotation SummarizationSetBy = Automatic

	column Cosmetic_2
		dataType: string
		lineageTag: 538ca306-76e1-45f7-93d8-17558d0e49d7
		summarizeBy: none
		sourceColumn: Cosmetic_2

		annotation SummarizationSetBy = Automatic

	column Cosmetic_3
		dataType: string
		lineageTag: 56d8658a-98e1-4dae-a213-5c911ae95375
		summarizeBy: none
		sourceColumn: Cosmetic_3

		annotation SummarizationSetBy = Automatic

	column Cosmetic_4
		dataType: string
		lineageTag: ba2d2f31-9382-4c38-9a96-1b21f732b6c7
		summarizeBy: none
		sourceColumn: Cosmetic_4

		annotation SummarizationSetBy = Automatic

	column Cosmetic_5
		dataType: string
		lineageTag: b00a5e7d-6215-4810-ab3d-f003da34cd3c
		summarizeBy: none
		sourceColumn: Cosmetic_5

		annotation SummarizationSetBy = Automatic

	column MC_1
		dataType: string
		lineageTag: 44e62487-4d1e-440a-8dd9-dfcc50b6a95b
		summarizeBy: none
		sourceColumn: MC_1

		annotation SummarizationSetBy = Automatic

	column MC_2
		dataType: string
		lineageTag: 0b003852-afbd-4228-a9b3-b8fd61356461
		summarizeBy: none
		sourceColumn: MC_2

		annotation SummarizationSetBy = Automatic

	column MC_3
		dataType: string
		lineageTag: 6d875e02-e0bd-4419-bbe3-52dab0456faa
		summarizeBy: none
		sourceColumn: MC_3

		annotation SummarizationSetBy = Automatic

	column MC_4
		dataType: string
		lineageTag: 8d7a51dc-cd9e-4468-abbf-055b7b5c7bd4
		summarizeBy: none
		sourceColumn: MC_4

		annotation SummarizationSetBy = Automatic

	column Market_Status
		dataType: string
		lineageTag: 1b417a25-6ed8-4279-946f-4e2a967642d8
		summarizeBy: none
		sourceColumn: Market_Status

		annotation SummarizationSetBy = Automatic

	column DDD_AMOUNT
		dataType: double
		lineageTag: 63018190-3c24-4f49-b3dd-91b0d11fe5ae
		summarizeBy: sum
		sourceColumn: DDD_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Brand_and_Form
		dataType: string
		lineageTag: ae88866b-d958-43dc-8200-54c2430f2a6c
		summarizeBy: none
		sourceColumn: Brand_and_Form

		annotation SummarizationSetBy = Automatic

	column doze
		dataType: string
		lineageTag: 137f2a88-4cba-4dfb-9961-b8979e4c288d
		summarizeBy: none
		sourceColumn: doze

		annotation SummarizationSetBy = Automatic

	column CatRxOTC
		dataType: string
		isHidden
		lineageTag: 5a1eb6b9-09ed-42cd-bdec-808d5984f9e2
		summarizeBy: none
		sourceColumn: CatRxOTC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: int64
		formatString: 0
		lineageTag: ebfd5c47-a453-4eed-ab8e-5ef60abf03cc
		summarizeBy: sum
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Rx/OTC
		dataType: string
		lineageTag: 2de8add3-cb79-44e4-916d-753597a1d283
		summarizeBy: none
		sourceColumn: Rx/OTC

		annotation SummarizationSetBy = Automatic

	column RxOTCNum
		dataType: string
		lineageTag: fd2d8539-00fe-4d2f-885d-3c1b994dabdd
		summarizeBy: none
		sourceColumn: RxOTCNum

		annotation SummarizationSetBy = Automatic

	column 'Licensee country'
		dataType: string
		lineageTag: bdee36b6-e08b-41c4-8758-8ef9dd44f9ce
		summarizeBy: none
		sourceColumn: Licensee country

		annotation SummarizationSetBy = Automatic

	column Corp_Country
		dataType: string
		lineageTag: 143346bb-46e4-411e-987a-9cabbed11c5e
		summarizeBy: none
		sourceColumn: Corp_Country

		annotation SummarizationSetBy = Automatic

	column 'NFC Code (1)'
		dataType: string
		lineageTag: fa5178c1-3c46-4a0b-9f81-f84650102caa
		summarizeBy: none
		sourceColumn: NFC Code (1)

		annotation SummarizationSetBy = Automatic

	column 'NFC Code (2)'
		dataType: string
		lineageTag: 879aec8f-7cc7-4e01-b2fd-b411aff4de7a
		summarizeBy: none
		sourceColumn: NFC Code (2)

		annotation SummarizationSetBy = Automatic

	column 'NFC Code (3)'
		dataType: string
		lineageTag: 5d6e6c28-e589-4bbe-8a76-ce9c58d68417
		summarizeBy: none
		sourceColumn: NFC Code (3)

		annotation SummarizationSetBy = Automatic

	column CN_1
		dataType: string
		lineageTag: 2cc0848c-62e0-4f76-9cb9-9d206e29349d
		summarizeBy: none
		sourceColumn: CN_1

		annotation SummarizationSetBy = Automatic

	column CN_2
		dataType: string
		lineageTag: 7a615243-c396-49ad-9a9f-fddc931d7af4
		summarizeBy: none
		sourceColumn: CN_2

		annotation SummarizationSetBy = Automatic

	column CN_3
		dataType: string
		lineageTag: 337f3132-8bdf-4d69-8b97-7bbbb035fac5
		summarizeBy: none
		sourceColumn: CN_3

		annotation SummarizationSetBy = Automatic

	column CORPORATION_ID
		dataType: int64
		formatString: 0
		lineageTag: 4ef5e659-ca77-487f-b224-ee3643875f48
		summarizeBy: count
		sourceColumn: CORPORATION_ID

		annotation SummarizationSetBy = Automatic

	column STM_STR
		dataType: string
		isHidden
		lineageTag: 2f1e39bc-69b9-4d4c-b76d-6f382679514a
		summarizeBy: none
		sourceColumn: STM_STR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Brand Form'
		dataType: string
		lineageTag: 610dd65f-a236-45ef-8b18-bce7cb049db2
		summarizeBy: none
		sourceColumn: Brand Form

		annotation SummarizationSetBy = Automatic

	column CategoryShortName
		dataType: string
		lineageTag: fa54ae04-de0b-461f-a19f-89a27f7756c7
		summarizeBy: none
		sourceColumn: CategoryShortName

		annotation SummarizationSetBy = Automatic

	column CategoryLongName
		dataType: string
		lineageTag: d8cb0542-ffa7-4882-98b1-0e4cb9a71eb9
		summarizeBy: none
		sourceColumn: CategoryLongName

		annotation SummarizationSetBy = Automatic

	column UserCulture
		dataType: string
		isHidden
		lineageTag: a4dfcae8-f9a4-4f34-8e95-34a447839c6d
		summarizeBy: none
		sourceColumn: UserCulture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cosmetic Name(1)'
		dataType: string
		lineageTag: 28816e68-8c85-4648-869b-91af3dc9e0d0
		summarizeBy: none
		sourceColumn: Cosmetic Name(1)

		annotation SummarizationSetBy = Automatic

	column 'Cosmetic Name(2)'
		dataType: string
		lineageTag: cf5f5190-b7ec-4433-959e-af85d6f6688b
		summarizeBy: none
		sourceColumn: Cosmetic Name(2)

		annotation SummarizationSetBy = Automatic

	column 'Cosmetic Name(3)'
		dataType: string
		lineageTag: 69b41974-3e00-4246-a865-e7ce19ffaaa2
		summarizeBy: none
		sourceColumn: Cosmetic Name(3)

		annotation SummarizationSetBy = Automatic

	column 'Cosmetic Name(4)'
		dataType: string
		lineageTag: a4714add-0ef1-4053-b180-2314cf3923c8
		summarizeBy: none
		sourceColumn: Cosmetic Name(4)

		annotation SummarizationSetBy = Automatic

	column 'Cosmetic Name(5)'
		dataType: string
		lineageTag: 8785549c-6691-4c03-8c3f-12c5bc4164d4
		summarizeBy: none
		sourceColumn: Cosmetic Name(5)

		annotation SummarizationSetBy = Automatic

	column 'MC Name(1)'
		dataType: string
		lineageTag: 3a7b59e8-b8e4-4510-9c72-0b6bc2ef39cf
		summarizeBy: none
		sourceColumn: MC Name(1)

		annotation SummarizationSetBy = Automatic

	column 'MC Name(2)'
		dataType: string
		lineageTag: ac65da21-41be-4c90-957f-1bbb12dc8c39
		summarizeBy: none
		sourceColumn: MC Name(2)

		annotation SummarizationSetBy = Automatic

	column 'MC Name(3)'
		dataType: string
		lineageTag: b0646288-f62b-4f28-9d21-b9254873011c
		summarizeBy: none
		sourceColumn: MC Name(3)

		annotation SummarizationSetBy = Automatic

	column 'MC Name(4)'
		dataType: string
		lineageTag: bf4dcb76-9dd3-4c54-8b6d-084f81c1db56
		summarizeBy: none
		sourceColumn: MC Name(4)

		annotation SummarizationSetBy = Automatic

	column INN_ID
		dataType: int64
		formatString: 0
		lineageTag: 6bea130f-616b-42f1-a166-27807752ea7f
		summarizeBy: count
		sourceColumn: INN_ID

		annotation SummarizationSetBy = Automatic

	column 'License Owner'
		dataType: string
		lineageTag: 407385dd-bf77-4b35-91cb-13d51907ed47
		summarizeBy: none
		sourceColumn: License Owner

		annotation SummarizationSetBy = Automatic

	column INN+NFC(1)
		dataType: string
		lineageTag: be72d9b5-8500-4418-91a4-79346fc7b96a
		summarizeBy: none
		sourceColumn: INN+NFC(1)

		annotation SummarizationSetBy = Automatic

	column INN+NFC(2)
		dataType: string
		lineageTag: 3531bed9-944c-49d9-ba67-b8ce481c3124
		summarizeBy: none
		sourceColumn: INN+NFC(2)

		annotation SummarizationSetBy = Automatic

	column INN+NFC(3)
		dataType: string
		lineageTag: dde7e171-ca26-4895-89b1-cf696d9c4911
		summarizeBy: none
		sourceColumn: INN+NFC(3)

		annotation SummarizationSetBy = Automatic

	column 'NFC (1)'
		dataType: string
		lineageTag: 40d60eaf-4f85-4234-9df0-a5e7907c3fda
		summarizeBy: none
		sourceColumn: NFC (1)

		annotation SummarizationSetBy = Automatic

	column 'NFC (2)'
		dataType: string
		lineageTag: 3a32be58-195c-4a56-8336-65fffc1a6f7a
		summarizeBy: none
		sourceColumn: NFC (2)

		annotation SummarizationSetBy = Automatic

	column 'NFC (3)'
		dataType: string
		lineageTag: d0108430-281e-4589-8bbd-c3a59cbfa1df
		summarizeBy: none
		sourceColumn: NFC (3)

		annotation SummarizationSetBy = Automatic

	column 'ATC Name (1)'
		dataType: string
		lineageTag: 3d966c0e-41cc-4880-b003-93a17a378437
		summarizeBy: none
		sourceColumn: ATC Name (1)

		annotation SummarizationSetBy = Automatic

	column 'ATC Name (2)'
		dataType: string
		lineageTag: ca6b5273-5ab3-4356-9554-9ef9d197aecd
		summarizeBy: none
		sourceColumn: ATC Name (2)

		annotation SummarizationSetBy = Automatic

	column 'ATC Name (3)'
		dataType: string
		lineageTag: b8c695df-3f2c-423b-a268-570bb0567ecd
		summarizeBy: none
		sourceColumn: ATC Name (3)

		annotation SummarizationSetBy = Automatic

	column 'ATC Name (4)'
		dataType: string
		lineageTag: ef86a9f8-4ff1-4690-8d19-107cb90257ab
		summarizeBy: none
		sourceColumn: ATC Name (4)

		annotation SummarizationSetBy = Automatic

	column 'ATC Name (5)'
		dataType: string
		lineageTag: 6e38c5eb-3109-4174-b8ed-d75eccb6e831
		summarizeBy: none
		sourceColumn: ATC Name (5)

		annotation SummarizationSetBy = Automatic

	column 'ATC (1)'
		dataType: string
		lineageTag: a6ffa80e-c313-49f9-9f2d-37d9cba1f654
		summarizeBy: none
		sourceColumn: ATC (1)

		annotation SummarizationSetBy = Automatic

	column 'ATC (2)'
		dataType: string
		lineageTag: 62538ba9-2d49-4669-8cc5-97ad47195f23
		summarizeBy: none
		sourceColumn: ATC (2)

		annotation SummarizationSetBy = Automatic

	column 'ATC (3)'
		dataType: string
		lineageTag: 2ab3bf84-ef9d-4adb-95bc-54026f94823a
		summarizeBy: none
		sourceColumn: ATC (3)

		annotation SummarizationSetBy = Automatic

	column 'ATC (4)'
		dataType: string
		lineageTag: ea897e24-2c80-407b-83f9-70961e821954
		summarizeBy: none
		sourceColumn: ATC (4)

		annotation SummarizationSetBy = Automatic

	column 'ATC (5)'
		dataType: string
		lineageTag: 49aaa72b-9ddf-46d5-bde9-59d6b8c0a42d
		summarizeBy: none
		sourceColumn: ATC (5)

		annotation SummarizationSetBy = Automatic

	column Rx/CHC/Gx
		dataType: string
		lineageTag: 71e0ce38-59cc-4405-9fb9-bf51be69970b
		summarizeBy: none
		sourceColumn: Rx/CHC/Gx

		annotation SummarizationSetBy = Automatic

	column Rx/CHC/Gx/DBU
		dataType: string
		lineageTag: d309ce83-623e-43a4-a671-09a481e74dd1
		summarizeBy: none
		sourceColumn: Rx/CHC/Gx/DBU

		annotation SummarizationSetBy = Automatic

	column 'Rx Orign/Vaccine/CHC/Gx'
		dataType: string
		lineageTag: 6794517f-273c-453b-9159-fb486de30b7b
		summarizeBy: none
		sourceColumn: Rx Orign/Vaccine/CHC/Gx

		annotation SummarizationSetBy = Automatic

	column RX/OTC/Oncology
		dataType: string
		lineageTag: 4e52c024-7e90-4457-9907-018f95459339
		summarizeBy: none
		sourceColumn: RX/OTC/Oncology

		annotation SummarizationSetBy = Automatic

	column 'NV RX/OTC/Oncology'
		dataType: string
		isHidden
		lineageTag: cdd5c52b-b7fd-4986-9bd5-a4c8f44ac2b0
		summarizeBy: none
		sourceColumn: NV RX/OTC/Oncology

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RX/OTC/Oncology/Bio
		dataType: string
		lineageTag: 5d829494-65c4-4856-a90d-911899debb83
		summarizeBy: none
		sourceColumn: RX/OTC/Oncology/Bio

		annotation SummarizationSetBy = Automatic

	column BAD1
		dataType: string
		lineageTag: 135b032b-454c-4579-92e0-85da949c91f6
		summarizeBy: none
		sourceColumn: BAD1

		annotation SummarizationSetBy = Automatic

	column BAD2
		dataType: string
		lineageTag: bd06375d-71bc-4a68-85d0-ca23ea23074d
		summarizeBy: none
		sourceColumn: BAD2

		annotation SummarizationSetBy = Automatic

	column 'BAD Name(1)'
		dataType: string
		lineageTag: 217d5667-bcdf-45c5-9a50-5b1ee48063ef
		summarizeBy: none
		sourceColumn: BAD Name(1)

		annotation SummarizationSetBy = Automatic

	column 'BAD Name(2)'
		dataType: string
		lineageTag: b9e94ab5-c86d-4d35-aeb0-43c6c3876179
		summarizeBy: none
		sourceColumn: BAD Name(2)

		annotation SummarizationSetBy = Automatic

	column SDDD_AMOUNT
		dataType: string
		lineageTag: 623767a8-378d-4259-a1fb-b8b19595eeb6
		summarizeBy: none
		sourceColumn: SDDD_AMOUNT

		annotation SummarizationSetBy = Automatic

	column IU_AMOUNT
		dataType: string
		lineageTag: 64e84d02-2979-4ce6-a004-634b8e278b2f
		summarizeBy: none
		sourceColumn: IU_AMOUNT

		annotation SummarizationSetBy = Automatic

	column MU_AMOUNT
		dataType: string
		lineageTag: d87ce834-d76d-4245-9680-10985e24aa49
		summarizeBy: none
		sourceColumn: MU_AMOUNT

		annotation SummarizationSetBy = Automatic

	column SanofiSpecCorp
		dataType: string
		isHidden
		lineageTag: c0988544-0805-49e2-a206-945cf2d0bc6b
		summarizeBy: none
		sourceColumn: SanofiSpecCorp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SanofiSpecCorpNew
		dataType: string
		isHidden
		lineageTag: f116d6c1-ea02-41e2-9274-a6141d717a1e
		summarizeBy: none
		sourceColumn: SanofiSpecCorpNew

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SanofiSpecBrand
		dataType: string
		isHidden
		lineageTag: a441b6b6-9517-4494-a1c7-f116b90d91b6
		summarizeBy: none
		sourceColumn: SanofiSpecBrand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SanofiSpecBrandSpecCorp
		dataType: string
		isHidden
		lineageTag: 53be0ec1-78d4-47ed-8519-3084973b5688
		summarizeBy: none
		sourceColumn: SanofiSpecBrandSpecCorp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TevaSpecCorp
		dataType: string
		isHidden
		lineageTag: f111c98b-8914-472e-958a-21bf68ca3bf1
		summarizeBy: none
		sourceColumn: TevaSpecCorp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column KRKASpecBrand
		dataType: string
		lineageTag: 4898bb5f-03a9-49f6-a5e9-10214ebf4d0b
		summarizeBy: none
		sourceColumn: KRKASpecBrand

		annotation SummarizationSetBy = Automatic

	column TakedaSpecBrand
		dataType: string
		isHidden
		lineageTag: 8a7ad388-5751-4220-9ac5-491f1a9e5baf
		summarizeBy: none
		sourceColumn: TakedaSpecBrand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ServierDrugName
		dataType: string
		isHidden
		lineageTag: a4b8b319-c974-41e5-8a7d-40bf4dfe37a8
		summarizeBy: none
		sourceColumn: ServierDrugName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NaturwarenSpecBrand
		dataType: string
		isHidden
		lineageTag: 85456fab-35fb-435a-ac57-0db04db398ae
		summarizeBy: none
		sourceColumn: NaturwarenSpecBrand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'COVID Vaccine'
		dataType: string
		lineageTag: 6917e690-05f8-4fa2-b2f3-be9b7755018a
		summarizeBy: none
		sourceColumn: COVID Vaccine

		annotation SummarizationSetBy = Automatic

	column C17083_FLAG
		dataType: string
		isHidden
		lineageTag: 2c0400e5-22ae-4cee-add2-dc695a8331f5
		summarizeBy: none
		sourceColumn: C17083_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column C15253_FLAG
		dataType: string
		isHidden
		lineageTag: 3bac4467-f352-4aeb-821d-f6048830ad97
		summarizeBy: none
		sourceColumn: C15253_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column C37771_FLAG
		dataType: string
		isHidden
		lineageTag: 2faa9c27-7c84-41b7-a05a-3310dbedffed
		summarizeBy: none
		sourceColumn: C37771_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column C15252_FLAG
		dataType: string
		isHidden
		lineageTag: 23fe47e1-5db9-4224-b973-e0d2bd713946
		summarizeBy: none
		sourceColumn: C15252_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column C37734_FLAG
		dataType: string
		isHidden
		lineageTag: 37d37d0c-1c3b-4d25-8462-0b95147cc549
		summarizeBy: none
		sourceColumn: C37734_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column C42306_FLAG
		dataType: string
		isHidden
		lineageTag: 64bb7d22-9223-41d9-9d9a-19af41a06715
		summarizeBy: none
		sourceColumn: C42306_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MAIN_DRUGS_ID
		dataType: int64
		formatString: 0
		lineageTag: fa20d156-6228-4feb-8279-1610acc7eb3c
		summarizeBy: count
		sourceColumn: MAIN_DRUGS_ID

		annotation SummarizationSetBy = Automatic

	column IS_STM
		dataType: int64
		formatString: 0
		lineageTag: 31050507-7c8e-4bb9-9374-f1065c78491e
		summarizeBy: sum
		sourceColumn: IS_STM

		annotation SummarizationSetBy = Automatic

	column PACK_VOLUME
		dataType: string
		lineageTag: 341d093a-fbff-4cca-b554-3a9907361888
		summarizeBy: none
		sourceColumn: PACK_VOLUME

		annotation SummarizationSetBy = Automatic

	column Covid19
		dataType: string
		lineageTag: 7d03e381-6ce0-4939-a4db-8e89ec50b545
		summarizeBy: none
		sourceColumn: Covid19

		annotation SummarizationSetBy = Automatic

	column PTM
		dataType: string
		lineageTag: 3a74f1cb-577c-4615-8b55-905cf3e30235
		summarizeBy: none
		sourceColumn: PTM

		annotation SummarizationSetBy = Automatic

	column 'Maker country'
		dataType: string
		lineageTag: 7002b26a-e805-4bdd-9365-49a1fc3c89c3
		summarizeBy: none
		sourceColumn: Maker country

		annotation SummarizationSetBy = Automatic

	column NFC
		dataType: string
		lineageTag: 853c0393-ab7a-48a7-ad73-17e93f6de7e0
		summarizeBy: none
		sourceColumn: NFC

		annotation SummarizationSetBy = Automatic

	column DIVIDER
		dataType: string
		lineageTag: 806b8095-e5a9-4583-bdcd-8b9c0ab0868c
		summarizeBy: none
		sourceColumn: DIVIDER

		annotation SummarizationSetBy = Automatic

	column BRAND_AMOUNT
		dataType: string
		lineageTag: cbb086ed-c6e8-4349-93cb-3d21d8f2efbc
		summarizeBy: none
		sourceColumn: BRAND_AMOUNT

		annotation SummarizationSetBy = Automatic

	column DRUGS_TYPE_ID
		dataType: string
		lineageTag: 7e2f4beb-f109-436e-aa37-63ed2532b52b
		summarizeBy: none
		sourceColumn: DRUGS_TYPE_ID

		annotation SummarizationSetBy = Automatic

	column DRUGS_TYPE
		dataType: string
		lineageTag: 03dcf683-fa9e-4872-b849-f5fb92be5aad
		summarizeBy: none
		sourceColumn: DRUGS_TYPE

		annotation SummarizationSetBy = Automatic

	column Interchangeable_Flag
		dataType: string
		lineageTag: 1d9b9c7e-0173-42a8-b36f-0e3eda6a9f65
		summarizeBy: none
		sourceColumn: Interchangeable_Flag

		annotation SummarizationSetBy = Automatic

	column TOP_100_PRICE_DECREASE
		dataType: string
		lineageTag: 42168b0d-202b-4f15-9768-5f0768140502
		summarizeBy: none
		sourceColumn: TOP_100_PRICE_DECREASE

		annotation SummarizationSetBy = Automatic

	column ADD_PRICE_DECREASE
		dataType: string
		lineageTag: 4b188f23-e880-4f80-9bdd-a82fd783e52b
		summarizeBy: none
		sourceColumn: ADD_PRICE_DECREASE

		annotation SummarizationSetBy = Automatic

	column NATIONAL_CATALOG
		dataType: string
		lineageTag: 033590c3-8329-4c9f-857a-37238756d1c7
		summarizeBy: none
		sourceColumn: NATIONAL_CATALOG

		annotation SummarizationSetBy = Automatic

	column STM_PARENT_ID
		dataType: string
		lineageTag: f19ab6a6-dd83-42c8-acf9-402f4ae6ec74
		summarizeBy: none
		sourceColumn: STM_PARENT_ID

		annotation SummarizationSetBy = Automatic

	column YFSpecBrand
		dataType: string
		lineageTag: 1baaa200-439e-4f5a-958f-fafc71d277d7
		summarizeBy: none
		sourceColumn: YFSpecBrand

		annotation SummarizationSetBy = Automatic

	column HAS_HIDDEN_STM
		dataType: string
		lineageTag: 4ce552b4-9fc1-4697-9933-158b8b38fc1a
		summarizeBy: none
		sourceColumn: HAS_HIDDEN_STM

		annotation SummarizationSetBy = Automatic

	column CLN_1
		dataType: string
		lineageTag: 26fe85f0-2f28-41ef-af3f-c9e972b00401
		summarizeBy: none
		sourceColumn: CLN_1

		annotation SummarizationSetBy = Automatic

	column CLN_2
		dataType: string
		lineageTag: e2f30a9b-5f91-49ff-b991-97c8095add71
		summarizeBy: none
		sourceColumn: CLN_2

		annotation SummarizationSetBy = Automatic

	partition Drugs = m
		mode: import
		source = ```
				let
				    IsRestrictsDrugsCustom=Table.RowCount(Restricts_Drugs_Custom),
				    IsRestrictsDrugsAddrMarket=Table.RowCount(Restricts_Drugs_Addr_Market),
				    IsRestrictsDrugsCategory=Table.RowCount(Restricts_Drugs_Category),
				    IsRestrictsDrugsRxOTC=Table.RowCount(Restricts_Drugs_RxOTC),
				    IsRestrictsDrugsCatRxOTC=Table.RowCount(Restricts_Drugs_RxOTC_Category),
				    isRestrictsDrugsExists=IsRestrictsDrugsCustom+IsRestrictsDrugsCategory+IsRestrictsDrugsRxOTC+IsRestrictsDrugsCatRxOTC+IsRestrictsDrugsAddrMarket,
				    // if exists Restricts
				    Restricts=if IsRestrictsDrugsCustom>0 then 
				        Table.NestedJoin(DrugsSRC,{"DRUGS_ID"},Restricts_Drugs_Custom,{"DRUGS_ID"},"R",JoinKind.Inner) 
				    else if IsRestrictsDrugsAddrMarket>0 then 
				        Table.NestedJoin(DrugsSRC,{"DRUGS_ID"},Restricts_Drugs_Addr_Market,{"DRUGS_ID"},"R",JoinKind.Inner) 
				    else if IsRestrictsDrugsCategory>0 and IsRestrictsDrugsRxOTC>0 then 
				        Table.NestedJoin(DrugsSRC,{"Cat_RxOTC"},Restricts_Drugs_RxOTC_Category,{"Cat_RxOTC"},"R",JoinKind.Inner) 
				    else if IsRestrictsDrugsCategory>0 and IsRestrictsDrugsRxOTC=0 then 
				        Table.NestedJoin(DrugsSRC,{"CategoryShortName"},Restricts_Drugs_Category,{"Cat"},"R",JoinKind.Inner) 
				    else if IsRestrictsDrugsCategory=0 and IsRestrictsDrugsRxOTC>0 then 
				        Table.NestedJoin(DrugsSRC,{"Rx/OTC"},Restricts_Drugs_RxOTC,{"Rx/OTC"},"R",JoinKind.Inner) else DrugsSRC,
				    RestrictsDone = if isRestrictsDrugsExists>0 then Table.RemoveColumns(Restricts,{"R"}) else DrugsSRC,
				    Removed=Table.RemoveColumns(RestrictsDone,{"LAUNCH_DATE",  "Bad_1", "Bad_2"}),
				    #"Changed Type" = Table.TransformColumnTypes(Removed,{{"Market Org ID", Int64.Type}, {"DRUG_FORM_NUMBER", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",".",",",Replacer.ReplaceText,{"DDD_AMOUNT"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"DDD_AMOUNT", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "RxOTCNum", each if [#"Rx/OTC"]="Rx" then 1 else if [#"Rx/OTC"]="OTC" then 0 else 2),
				    #"Added Custom" = Table.AddColumn(#"Added Custom1", "CatRxOTC", each Number.ToText([Category])&"_"&Number.ToText([#"RxOTCNum"])),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each [DRUGS_ID] <> null and [DRUGS_ID] <> ""),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Cat_RxOTC"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"VTM", "PTM"}})//,
				    // #"Added Custom2" = Table.AddColumn(#"Removed Columns", "Cosmetic Name(1)", each [Cosmetic_1], type text),
				    // #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Cosmetic Name(2)", each [Cosmetic_2],type text),
				    // #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Cosmetic Name(3)", each [Cosmetic_3],type text),
				    // #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Cosmetic Name(4)", each [Cosmetic_4],type text),
				    // #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Cosmetic Name(5)", each [Cosmetic_5],type text),
				    // #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Bad Name(1)", each [BAD1],type text),
				    // #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Bad Name(2)", each [BAD2],type text),
				    // #"Added Custom9" = Table.AddColumn(#"Added Custom8", "MC Name(1)", each [MC_1],type text),
				    // #"Added Custom10" = Table.AddColumn(#"Added Custom9", "MC Name(2)", each [MC_2],type text),
				    // #"Added Custom11" = Table.AddColumn(#"Added Custom10", "MC Name(3)", each [MC_3],type text),
				    // #"Added Custom12" = Table.AddColumn(#"Added Custom11", "MC Name(4)", each [MC_4],type text)
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

