table Groups
	isHidden
	lineageTag: d11fa841-70c1-48e3-b271-f264ec725782

	column DRUGS_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b2d26f63-43d0-473e-a83f-33a09efcf068
		summarizeBy: none
		sourceColumn: DRUGS_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PRODUCT_NAME
		dataType: string
		isHidden
		lineageTag: bffa9cd5-f5ab-4289-8c22-f4a684844584
		summarizeBy: none
		sourceColumn: PRODUCT_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRODUCT_NAME_TREE.1'
		dataType: string
		isHidden
		lineageTag: a9eaaa4a-f123-45ba-af61-96abc335b444
		summarizeBy: none
		sourceColumn: PRODUCT_NAME_TREE.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRODUCT_NAME_TREE.2'
		dataType: string
		isHidden
		lineageTag: ea758994-1464-4d55-bc85-353c2feb4ab4
		summarizeBy: none
		sourceColumn: PRODUCT_NAME_TREE.2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRODUCT_NAME_TREE.3'
		dataType: string
		isHidden
		lineageTag: 9b01b3c1-3574-4a68-99a6-4f798d993759
		summarizeBy: none
		sourceColumn: PRODUCT_NAME_TREE.3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IS_LOCAL
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3a50493f-9072-46b4-aa27-bcaa8d71923d
		summarizeBy: sum
		sourceColumn: IS_LOCAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IS_ADDRESSABLE_MARKET
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 31709e5c-1bc3-4900-ac53-009e1b5b48f3
		summarizeBy: sum
		sourceColumn: IS_ADDRESSABLE_MARKET

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORGANIZATION
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2510c9ec-e892-48ae-8875-198d62afe9be
		summarizeBy: sum
		sourceColumn: ORGANIZATION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GROUP_ID
		dataType: string
		isHidden
		lineageTag: 86aaa6d3-e183-4115-a7ab-b0e966dd5b37
		summarizeBy: none
		sourceColumn: GROUP_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NODE_ID
		dataType: string
		isHidden
		lineageTag: bfb696f6-c7cc-420e-9815-2e0838eea157
		summarizeBy: none
		sourceColumn: NODE_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NODE_TREE
		dataType: string
		isHidden
		lineageTag: 54b32be8-fd22-409a-a82d-d45bcfbdd7f0
		summarizeBy: none
		sourceColumn: NODE_TREE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GROUP_NAME
		dataType: string
		isHidden
		lineageTag: 0b270cb9-012d-41c7-b9a2-39eb5433f060
		summarizeBy: none
		sourceColumn: GROUP_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORG_ID
		dataType: string
		isHidden
		lineageTag: 373b2d7c-a5a2-4861-9445-1512a0123c50
		summarizeBy: none
		sourceColumn: ORG_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column USER_ID
		dataType: string
		isHidden
		lineageTag: 63e08f57-a5aa-4d9c-857a-67655060b72a
		summarizeBy: none
		sourceColumn: USER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FIELD1
		dataType: string
		isHidden
		lineageTag: f86b9ce4-9f3d-41ee-a54b-54f63b524d5a
		summarizeBy: none
		sourceColumn: FIELD1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FIELD2
		dataType: string
		isHidden
		lineageTag: eaf31a16-0abb-4cd6-80be-88c8a21ac012
		summarizeBy: none
		sourceColumn: FIELD2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FIELD3
		dataType: string
		isHidden
		lineageTag: ce114065-0e39-4890-853e-6891f41a8a12
		summarizeBy: none
		sourceColumn: FIELD3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FIELD4
		dataType: string
		isHidden
		lineageTag: 898c4494-c2d9-4043-beeb-d482f7a1ee14
		summarizeBy: none
		sourceColumn: FIELD4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FIELD5
		dataType: string
		isHidden
		lineageTag: 75107b48-e81e-4e16-92e6-0f959410adfd
		summarizeBy: none
		sourceColumn: FIELD5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TAG
		dataType: string
		isHidden
		lineageTag: 3930f918-8d8f-42d5-8707-dd78e05db930
		summarizeBy: none
		sourceColumn: TAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'TREE.0'
		dataType: string
		isHidden
		lineageTag: 5839c86b-a2a1-4de7-95a8-d09bea5f45c1
		summarizeBy: none
		sourceColumn: TREE.0

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRODUCT_NAME_TREE.4'
		dataType: string
		isHidden
		lineageTag: 6ea279f2-7cf4-44f8-a306-3d0585b57c3c
		summarizeBy: none
		sourceColumn: PRODUCT_NAME_TREE.4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PRODUCT_NAME_TREE.5'
		dataType: string
		isHidden
		lineageTag: 8aca6759-278a-4f9c-9bb5-0da404689345
		summarizeBy: none
		sourceColumn: PRODUCT_NAME_TREE.5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Groups = m
		mode: import
		source =
				let
				   Source = GroupsSRC,
				    #"Added Custom" = Table.AddColumn(Source, "IS_ADDRESSABLE_MARKET", each 1),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"IS_ADDRESSABLE_MARKET", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

