table Logo
	isHidden
	lineageTag: e5f385c6-52c7-49ea-b511-36f17516c333

	column value
		dataType: string
		isHidden
		lineageTag: 15f59760-4048-4884-a899-55f2a657ad7c
		summarizeBy: none
		sourceColumn: value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		isHidden
		lineageTag: 6ac174f5-a9cf-4c71-850f-e0034d05c302
		summarizeBy: none
		sourceColumn: Logo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Logo = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Logos = Source{[Id="Workspaces"]}[Data]{[workspaceId=_WS_ID_]}[Data]{[dataflowId=_MISC_FLOW_ID_]}[Data]{[entity="LOGO",version=""]}[Data],
				    SelfLogoName = Table.SelectRows(Restricts, each [table]="Restricts" and [field]="Logo"),
				    SelfLogoNameFiltered = Table.RemoveColumns(SelfLogoName,{"project_name", "role_id", "role_name", "property_id", "table", "field"}),
				    SelfLogo=Table.NestedJoin(SelfLogoNameFiltered,{"value"},Logos,{"name"},"LL",JoinKind.Inner),
				    #"Expanded LL" = Table.ExpandTableColumn(SelfLogo, "LL", {"logo"}, {"LL.logo"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded LL",{{"LL.logo", "Logo"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

