table MapUrls
	lineageTag: 41bf818c-9a28-478e-9eae-0ca1ca76f22b

	column COUNTRY
		dataType: string
		lineageTag: e4e100e2-4da7-4fc2-9a71-8c7110f07884
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column TYPE
		dataType: string
		lineageTag: b76cf5c9-cbae-486c-9904-8dba79631191
		summarizeBy: none
		sourceColumn: TYPE

		annotation SummarizationSetBy = Automatic

	column COMPANY
		dataType: string
		lineageTag: c6127663-00a2-4abb-a8a3-e432e8f2a5f2
		summarizeBy: none
		sourceColumn: COMPANY

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 6e2728f2-c593-4925-be1a-05b31c61e5a5
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column EXPIRED
		dataType: string
		lineageTag: 86c08cd6-c564-4a74-9f32-b9e4b1a2548b
		summarizeBy: none
		sourceColumn: EXPIRED

		annotation SummarizationSetBy = Automatic

	partition MapUrls = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    URL_ = Source{[Id="Workspaces"]}[Data]{[workspaceId=_WS_ID_]}[Data]{[dataflowId=_MAP_URL_FLOW_ID_]}[Data]{[entity="MAP_URL",version=""]}[Data],
				    MapName= "sonapharm",
				    #"Filtered Rows" = Table.SelectRows(URL_, each ([COUNTRY]=_COUNTRY_) and (List.Contains({"GEO","COUNTRY"},[TYPE])) and  ([COMPANY]="" or [COMPANY]=MapName))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

