table PeriodsLinks
	isHidden
	lineageTag: 0798587e-a7ec-4c11-8c91-d07904b6e083

	column Period
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 339018e6-feca-4ee2-9753-4896da3464df
		summarizeBy: none
		sourceColumn: Period

		variation Variation
			isDefault
			relationship: fe0706ad-b471-40a9-81c9-48a3e90a2b5c
			defaultHierarchy: LocalDateTable_ce202fe6-3b82-4628-8266-ddc6cf2b3c87.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PERIOD_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6027616a-2b39-4aa5-8bbd-636e45cdd732
		summarizeBy: none
		sourceColumn: PERIOD_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PeriodPY
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e396d61-e4f7-4aec-906e-81a6ac4a8e2c
		summarizeBy: none
		sourceColumn: PeriodPY

		variation Variation
			isDefault
			relationship: 7c3f7b8a-1d4f-4d14-b209-b378c317b4b3
			defaultHierarchy: LocalDateTable_952d10cf-c69e-4dd7-8a70-50854290457a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FP
		dataType: string
		lineageTag: 4e2cfb83-a5a9-47fe-a0e7-8b3e9b340625
		summarizeBy: none
		sourceColumn: FP

		annotation SummarizationSetBy = Automatic

	partition PeriodsLinks = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    WS = Workspaces{[workspaceId=_WS_ID_]}[Data],
				    DF = WS{[dataflowId=_DATA_FLOW_ID_]}[Data],
				    PERIODS_LINKS_ = DF{[entity="PERIODS_LINKS",version=""]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(PERIODS_LINKS_,{"WEEK_ID", "MONTH_ID", "MONTH_K", "WEEK_K"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [PERIOD_ID] >= GetMinPeriodID),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"Period", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"Period"}, PeriodsPYSameWD, {"period"}, "PeriodsPYSameWD", JoinKind.LeftOuter),
				    #"Expanded PeriodsPYSameWD" = Table.ExpandTableColumn(#"Merged Queries", "PeriodsPYSameWD", {"period_py"}, {"PeriodsPYSameWD.period_py"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PeriodsPYSameWD",{{"PeriodsPYSameWD.period_py", "PeriodPY"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"PeriodPY", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "FP", each if [PERIOD_ID]<=GetMaxPeriodID then 0 else 1)
				in
				    #"Added Custom"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

