table SlicerHeaders
	isHidden
	lineageTag: 1f668e45-7da1-465f-8cee-bf1b4e25b0d1

	measure Header_Measure = var s="Measure" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 4e5e3343-d8a1-4973-8e60-002fb693c9d8

	measure Header_Aggregation = var s="Aggregation" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 5de4c670-1fd4-4e3d-adab-db44c2052453

	measure Header_Dimension = (var s="Dimension" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s))
		isHidden
		lineageTag: ae18d29c-d077-4f26-84e9-78b297805040

	measure Header_Period = (var s="Period" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s))
		isHidden
		lineageTag: c1923661-c11f-400c-b26b-357048dad042

	measure Header_Top = (var s="Top" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s))
		isHidden
		lineageTag: 241f53f8-381f-40c2-8b0f-c003ea8dd6d7

	measure Header_Self_MO = (var s="Self Market Org" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s))
		isHidden
		lineageTag: 04925d14-a693-4b54-9b17-147c7236ec57

	measure Header_Language = var s="Language" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: dad5bc10-7589-4429-94f3-c3bb37d0be6d

	measure Header_Expr_Type = var s="Expression type" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 1293aa06-42d6-4044-aa4b-610806181642

	measure Header_Period_Filter = var s="Period filter" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 5329e933-d1ec-4378-abc7-e361ce9edafa

	measure Header_Level = var s="Level" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: a06f52d4-9a69-494f-a986-9fce7a28c088

	measure Header_Group = var s="Group" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: f84f3f78-9eb8-473a-8259-56985c29a267

	measure Header_Penetratoin_Type = var s="Penetration type" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 34ac4fc0-de9d-4fc2-b6da-afec230c7364

	measure Header_Category = (var s="Category" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s))
		isHidden
		lineageTag: 01003c74-6fdd-42fa-add0-2a677f554d89

	measure Header_Export_Fields = var s="Export fields" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: bc17fb33-fcf4-4c20-a94e-7243ce6cb177

	measure Header_Export_Measures = var s="Export measures" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 131d83b6-0139-423d-9a46-128cc39922e7

	measure Header_Aggregate_Days = var s="Aggregate days" return CALCULATE(SELECTEDVALUE(T[dst],s),T[src]=s)
		isHidden
		lineageTag: 94502410-bcef-4ea1-8f8e-7dc016d1d251

	column Value
		isHidden
		formatString: 0
		lineageTag: 111ccb0c-b3bd-4eee-83cf-85d06a627fce
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition SlicerHeaders = calculated
		mode: import
		source = {{BLANK()}}

	annotation PBI_Id = 79c59c1aa4f6428d8e5bef12def2bfbe

