table T
	isHidden
	lineageTag: 3a1eed97-1482-4c28-896b-fcb2940466fc

	column src
		dataType: string
		isHidden
		lineageTag: 00e88628-b4c9-489c-97ad-17b2cf85bd8a
		summarizeBy: none
		sourceColumn: src

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserCulture
		dataType: string
		isHidden
		lineageTag: 138da9f2-70bd-4364-941f-c055b2000f99
		summarizeBy: none
		sourceColumn: UserCulture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dst
		dataType: string
		isHidden
		lineageTag: f7da4b04-ceea-4c8f-9d86-84e08271b1f0
		summarizeBy: none
		sourceColumn: dst

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition T = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    LABELS_ = Source{[Id="Workspaces"]}[Data]{[workspaceId=_WS_ID_]}[Data]{[dataflowId=_TRANSLATIONS_FLOW_ID_]}[Data]{[entity="LABELS",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(LABELS_,{{"language", "UserCulture"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

