table Tags
	lineageTag: b1c6640d-3ee0-48bc-86b2-ca8f9e1e6137

	column GROUP_ID
		dataType: string
		lineageTag: 1f8a0420-6784-4c1d-b80e-16aa6ccfcb2b
		summarizeBy: none
		sourceColumn: GROUP_ID

		annotation SummarizationSetBy = Automatic

	column TAG
		dataType: string
		lineageTag: b53da9e0-a618-4e54-9203-3a6be2864fc3
		summarizeBy: none
		sourceColumn: TAG

		annotation SummarizationSetBy = Automatic

	partition Tags = m
		mode: import
		source =
				let
				   Source = Table.Distinct(Table.SelectColumns(Groups,{"GROUP_ID","TAG"})),
				    Custom1 = Table.TransformColumns(Source,{"TAG",each Text.Split(_,",")}),
				    Custom2 = Table.ExpandListColumn(Custom1,"TAG")
				in
				    Custom2

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

