table TranslateGRIndexes
	isHidden
	lineageTag: 5f1d9b28-cf8f-46d0-aecc-c65f6cd54552

	column UserCulture
		dataType: string
		isHidden
		lineageTag: 43efc9ec-4495-4ffd-9975-9da37b0f14b8
		summarizeBy: none
		sourceColumn: UserCulture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IndexName
		dataType: string
		isHidden
		lineageTag: 35cf2e81-caf8-49c6-9298-9f65707bc9cf
		summarizeBy: none
		sourceColumn: IndexName
		sortByColumn: id

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f5d9d874-9609-4d1a-89f2-5972e5e3682f
		summarizeBy: sum
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition TranslateGRIndexes = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    LABELS_ = Source{[Id="Workspaces"]}[Data]{[workspaceId=_WS_ID_]}[Data]{[dataflowId=_TRANSLATIONS_FLOW_ID_]}[Data]{[entity="GRINDEXES",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(LABELS_,{{"id", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

